### ISSUE TITLE
Collect W8/W9

### ISSUE THREAD

**Issue by super3** [Storj/storjshare-gui#114]
- [ ] Implement notification of form in installer
- [ ] @gordonwritescode Investigate form callback
- [ ] @MrFancyMonocle Add option to link users to online W8/W9 form on http://driveshare.org
- [ ] Discuss pairing options
- [ ] Implement paring options

**Comment by littleskunk** [comment]
One stupid question. Lets say i am a stupid dataserv-client user. I installed it but i did not read the manual. I reach the payout limit in 20 days. We need a notification. Otherwise i will write some bad reputation. It would look like a scam...

**Comment by subwolf** [comment]
If payouts are in SJCX, a changing value, how can you track this?

**Comment by super3** [comment]
Its the value at the time of payment.

**Comment by subwolf** [comment]
Think a lot of people might change their minds when that comes into play.

**Comment by super3** [comment]
So we can perhaps have a notification field on install and/or include it in
the EULA that they accept on install.

Shawn

**Comment by jeantil** [comment]
Am I correct to think that this is only for test group payout and it won't be relevant in distributed mode ...

**Comment by super3** [comment]
@jeantil Incorrect. This is relevant to any payout in a test group or not.

**Comment by JeremyPepper2** [comment]
I'm glad to see this being thought of up front!  Compliance is a HUGE (and costly) part of any real business undertaking! Kudos to you guys.

**Comment by super3** [comment]
Thankfully most users will not have to encounter this. For the users who do
it will be encrypted and not have to be accessed by us for most cases. We
have it easy compared to other Bitcoin startups

**Comment by JeremyPepper2** [comment]
Can this not be accomplished - for most users - by having them pay with a credit card?  Once a user reaches a certain payout limit the system can just run a soft credit check on them (or we can do that up front).  Anyone who pays in Bitcoin (if that's an option) would have to provide additional KYC documentation at that point.  For those of us on the farming end it's different.  I fully expect to file any of the income I generate as business income for example.  But I'm thinking this part of the UX can probably be made transparent for all credit card users.

I'm not sure what kind of legal status that puts us in, but without credit card payments available, I think the system would be of dubious initial merit to users anyway (anathema, I know, but still true I think).

**Comment by super3** [comment]
Users buying storage will not have to do this. Only users receiving
income(farmers). This KYC is not triggered until they are about to hit
$600. I mined Bitcoin since 2012 and never ever hit close to $600 at the
time I mined them.

**Comment by JeremyPepper2** [comment]
Ah, I see, wrong users.  In that case, no big deal.  I hope I far exceed $600 in revenue, and I'm way more than happy to provide tax ID when the time comes.

However, I'm not imagining the Storj network as a mining type initiative where payouts are made in diminutive (and speculative) sums of SJCX though, so I'm hoping there are truly substantial payouts and tons of users over the $600 amount.  I don't expect the cost of storage space to scale quite like bitcoin mining chip technology.  This is an established market with cost models that seem to be less razor thin on profits than Bitcoin mining (which I gave up long ago).

**Comment by super3** [comment]
This will not be on the DriveShare website instead of in client. See the issue here: https://github.com/Storj/driveshare.org/issues/17

**Comment by super3** [comment]
This issue has been added to https://github.com/Storj/storj.io/issues/22. Don't think it makes sense to keep it around here.
