### ISSUE TITLE
Solve the diskspace hack from #83

### ISSUE THREAD

**Issue by bookchin** [Storj/storjshare-gui#135]

**Comment by super3** [comment]
I think we should try to solve this in the v0.7 release. Think the best way to do it in including the feature in storjnode or dataserv-client, which has to deal with that anyways.

**Comment by gordonwritescode** [comment]
I agree that it is preferable to abstract this to a lower level, though if that's the case, we should not assign this issue to a release milestone on this project given that the release cycle for the project in which this does get implemented may not align with a 0.7.x driveshare release. 

My suggestion is to leave it in the backlog without a milestone and once a fix is issued in dataserv client or storjnode, we can pull it into the active milestone at that time.

**Comment by super3** [comment]
@gordonwritescode Sounds agreeable. Dropping milestone and moving into backlog.

**Comment by bookchin** [comment]
This should do it: https://www.npmjs.com/package/fd-diskspace
