### ISSUE TITLE
Launch Driveshare at User Login not working (Windows 10, Driveshare-gui v0.5.1)

### ISSUE THREAD

**Issue by allen7575** [Storj/storjshare-gui#190]
I think there should be an option which enabled "start at minimized". So that I can autorun it under windows without any drivershare screen.

**Comment by littleskunk** [comment]
Already implemented. https://cloud.githubusercontent.com/assets/6333390/12154684/3c1edb12-b4c1-11e5-8449-4ed706bf89ea.jpg

**Comment by allen7575** [comment]
But it seems dosen't work for me....

**Comment by littleskunk** [comment]
A glance in the crystal ball don't work for me. I don't understand what your problem is. A better description would help.

Install the latest driveshare-gui version (at the moment v0.5.1)
Activate "Display in System Tray" and "Launch Driveshare at User Login" (Screenshot was from v0.5.0)
Reboot your PC and login with the same user. Open the system tray. Remember that windows hides the icon in the system tray. You have to look into the system tray drop down menu to see every system tray icon.

Join us on slack if you have more questions. http://slack.storj.io/

**Comment by allen7575** [comment]
I followed your step, but after reboot, there are no any driveshare instance start with windows, even system tray icon. I also checked task manager, there are no any driveshare instance. 

So I use autoruns(an application that can check all auto start instance) to check if there are any driveshare instance in registry ,scheduled task or services. But I found nothing.

Therefore, If I want to auto start it, I must manually add it in scheduled task. But every time I reboot my PC, I can see window of driveshare on my screen. I must manually close this window to hide it on system tray.

Any idea?

**Comment by littleskunk** [comment]
Confirmed. I can reproduce the bug. I will work on it later.

**Comment by littleskunk** [comment]
The old version 0.5.0 can add and remove the registry key (HKEY_USERS\<user id>\SOFTWARE\Microsoft\Windows\CurrentVersion\Run). The new version 0.5.1 can't add or remove the registry key. @gordonwritescode fix please.

Workaround for now:
Install driveshare-gui 0.5.0. Deactivate and activate "Launch Driveshare at User Login". That should give you the registry key. Update to driveshare-gui 0.5.1. The update will not effect the registry key.

**Comment by gordonwritescode** [comment]
@mrfancymonocle

**Comment by allen7575** [comment]
OK, But I do not want to reinstall it. Is there any command argument that can enable "start at minimized"? I want to manually add it.

**Comment by littleskunk** [comment]
No there is no command. Follow the workaround steps or add the registry key yourself or wait for the bugfix.

**Comment by Velociraptor85** [comment]
Does not work for 0.7.5

**Comment by super3** [comment]
Can also confirm that StorjShare did not seem to automatically launch at startup. Uninstalled and deleted user data, and then reinstalled a fresh copy. 

@littleskunk Can you see if you can reproduce on a clean system.

**Comment by littleskunk** [comment]
Will be fixed with the next version. Current version 0.7.5.
