### ISSUE TITLE
Update to latest core and use LevelDB storage adapter

### ISSUE THREAD

**Issue by bookchin** [Storj/storjshare-gui#221]
We are going to have to custom compile leveldown for electron. Ugh.

Moose is doing it, so I guess we can too: https://github.com/moose-team/friends/blob/master/package.json#L94

**Comment by gordonwritescode** [comment]
Apparently this is easy as:

```
npm install
cd node_modules/level/node_modules/leveldown
env HOME=~/.electron-gyp && node-gyp rebuild --target=0.28.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell
```
