### ISSUE TITLE
v0.8.0 installation not working on windows

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#227]
First Problem on windows is this line: https://github.com/littleskunk/storjshare-gui/blob/master/package.json#L29

I had to changed `env HOME=~/.electron-gyp` to `set HOME=%userprofile%/.electron-gyp`. That way I was able to install it but not able to build a binary. The path is to long for windows.

```
File: failed opening file "C:\storjshare-gui\tmp\storjshare\resources\app\node_modules\storj\node_modules\leveldown\node_modules\prebuild\node_modules\ghreleases\node_modules\ghutils\node_modules\jsonist\node_modules\bl\node_modules\readable-stream\node_modules\core-util-is\package.json"
```

**Comment by littleskunk** [comment]
flatten-packages and npm3 are not the solution or it is a new issue.

npm start looks good but after installing the binary I have this:

![windows-gui](https://cloud.githubusercontent.com/assets/6333390/15915373/20b033c0-2de9-11e6-85cf-aa2bf8a81d7b.jpg)

**Comment by bookchin** [comment]
what's in the developer tools log?

**Comment by littleskunk** [comment]
Expected output (npm start):
```
[Vue warn]: Error when evaluating expression "tab.active": TypeError: Cannot read property 'active' of undefinedwarn @ C:\storjshare-gui\build\node_modules\vue\dist\vue.common.js:1014
C:\storjshare-gui\build\node_modules\vue\dist\vue.common.js:10025 Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
```

Actual output (start binary):
```
Uncaught Error: EPERM: operation not permitted, write
C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:10025 Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
```

It looks like flatten-packages is working but we have a new bug. Something is wrong with the NSIS. I will try to get a full log or any other usefull information.

**Comment by littleskunk** [comment]
https://github.com/electron/electron/issues/2033

Reason for this error: stdout somewhere in the code. I will find it. We are so close :)

I am able to start the binary out of a cmd window. That way it has stdout.

**Comment by littleskunk** [comment]
No that was not the problem. I will revert it. Debuging with the developer console gives me a full stack trace.

```
<exception>: Error: EPERM: operation not permitted, write at Error (native) at Object.fs.writeSync (fs.js:706:20) at SyncWriteStream.write (fs.js:2059:6) at Object.execSync (child_process.js:514:20) at _diskSpace (C:\Program Files (x86)\Storj Share\resources\app\node_modules\fd-diskspace\bin\index.js:119:32) at diskSpaceSync (C:\Program Files (x86)\Storj Share\resources\app\node_modules\fd-diskspace\bin\index.js:171:10) at Vue.methods.getFreeSpace (file:///C:/Program%20Files%20(x86)/Storj%20Share/resources/app/client.js:473:19) at Vue.getFreeSpace (C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:216:72) at Vue.methods.showTab (file:///C:/Program%20Files%20(x86)/Storj%20Share/resources/app/client.js:233:12) at Vue.showTab (C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:216:54)
code: "EPERM"
errno: -4048
message: "EPERM: operation not permitted, write"
stack: "Error: EPERM: operation not permitted, write↵    at Error (native)↵    at Object.fs.writeSync (fs.js:706:20)↵    at SyncWriteStream.write (fs.js:2059:6)↵    at Object.execSync (child_process.js:514:20)↵    at _diskSpace (C:\Program Files (x86)\Storj Share\resources\app\node_modules\fd-diskspace\bin\index.js:119:32)↵    at diskSpaceSync (C:\Program Files (x86)\Storj Share\resources\app\node_modules\fd-diskspace\bin\index.js:171:10)↵    at Vue.methods.getFreeSpace (file:///C:/Program%20Files%20(x86)/Storj%20Share/resources/app/client.js:473:19)↵    at Vue.getFreeSpace (C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:216:72)↵    at Vue.methods.showTab (file:///C:/Program%20Files%20(x86)/Storj%20Share/resources/app/client.js:233:12)↵    at Vue.showTab (C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:216:54)"
```

**Comment by bookchin** [comment]
Ughhh.... This happened with the last disk space issue too. For whatever reason, one the binary is packaged, it doesn't have permission to execute the command to get the diskspace.

**Comment by bookchin** [comment]
Which I have no idea how to fix Windows crazy permissions system or why a userland application is not allowed to execute a user permissioned command.

**Comment by bookchin** [comment]
https://stackoverflow.com/questions/34982443/eperm-error-in-nodejs-when-calling-execsync

?

**Comment by bookchin** [comment]
If that fixes it I guess we can fork that fd-diskspace module and change it.

**Comment by littleskunk** [comment]
If I start the binary from the comand line it is attached to the stdout of that command line. Everything is running fine. No permission problem.

The Problem is that executing the exe file will not attach any stdout. Onle console.log and console.error are allowed.

Your link looks good. I will try it.

**Comment by littleskunk** [comment]
Fixed and open pull request for fd-diskspace. Switched to my fork as long as the pull request is not merged.
