### ISSUE TITLE
LevelDOWN is not a valid Win32 application

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#228]
I installed storjshare-gui with quick and dirty hack https://github.com/Storj/storjshare-gui/issues/227

Pressed the start button and nothing worked. This error message was on the console:
```
Uncaught LevelUPError: Failed to require LevelDOWN (%1 is not a valid Win32 application.
\\?\C:\storjshare-gui\build\node_modules\storj\node_modules\leveldown\build\Release\leveldown.node). Try `npm install leveldown` if it's missing
```

**Comment by littleskunk** [comment]
Quick and dirty hack number 2: https://github.com/Storj/storjshare-gui/blob/a798e2856c1b8bb3f3a88b9eafe04533ea7a1d1e/package.json#L29

Changed `x64` to `ia32`
`"postinstall": "node ./tasks/app_npm_install && cd ./app/node_modules/storj/node_modules/leveldown && set HOME=%userprofile%/.electron-gyp && node-gyp rebuild --target=0.36.12 --arch=ia32 --dist-url=https://atom.io/download/atom-shell",`

**Comment by bookchin** [comment]
That's correct, once bridge is updated today this should work. Do you know a way to set the flags so that these options are called on windows?

**Comment by littleskunk** [comment]
Let me try to fix it.

**Comment by littleskunk** [comment]
I was able to fix it. I removed `env HOME=~/.electron-gyp` because Home / Userprofile is default and working very good on both systems. I removed --arch as well. Default is working fine for this as well. It will detect the current architecture and use it for compiling.

**Comment by bookchin** [comment]
Nice!

**Comment by littleskunk** [comment]
Fixed :)
