### ISSUE TITLE
Logfile and loglevel

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#233]
I love the storjshare-cli loglevel. The additional informations are awesome. I would like to see the same for storjshare-gui.

It would be nice if storjshare-gui could write a logfile in the background. In case of a crash the logfile would be very usefull.

**Comment by super3** [comment]
Related to: https://github.com/Storj/storjshare-cli/issues/78

**Comment by bookchin** [comment]
https://github.com/Storj/storjshare-gui/issues/244

**Comment by aleitner** [comment]
#260

**Comment by littleskunk** [comment]
Building binaries for the pull request. Lets try it out. Can't wait for a good GUI logging

**Comment by bookchin** [comment]
Closed by #260
