### ISSUE TITLE
Upnp enable in Windows 

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#237]
When installing / configuring make sure UPNP is on in Windows

netsh advfirewall firewall set rule group="Network Discovery" new enable=Yes

**Comment by computeronix** [comment]
FYI if client is installed on server
Follow this (will have to check/enable a couple services)

https://support.microsoft.com/en-us/kb/2722035

**Comment by 1credit** [comment]
I'd like to comment that many consider UPnP as a security risk, with programs opening ports on firewalls that the consumer may not even be aware of.  It is convenient, but please make sure that usage is called out by name ("UPnP") and not buried in some other descriptor.

**Comment by super3** [comment]
This is something that could be added to documentation, but shouldn't be the responsibility of the GUI.
