### ISSUE TITLE
Storj Share hangs at "preparing" after update to 0.8.2 from 0.7.5

### ISSUE THREAD

**Issue by darkbluelight** [Storj/storjshare-gui#239]
Hi everyone, I'm on Debian 64-bit, Kernel 4.3.0-1. Storj Share 0.7.5 worked, but 0.8.2 no longer. The GUI shows up and still shows all the correct data and settings, but after clicking "start" it hangs at "preparing".
In the developer tools console I've got the following two entries:

The first entry:
/opt/storjshare/resources/app.asar/node_modules/vue/dist/vue.common.js:1014
[Vue warn]: Error when evaluating expression "tab.active": TypeError: Cannot read property 'active' of undefined
warn `@` /opt/storjshare/resources/app.asar/node_modules/vue/dist/vue.common.js:1014

/opt/storjshare/resources/app.asar/node_modules/vue/dist/vue.common.js:10025
Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools

The second entry:
/opt/storjshare/resources/app.asar/node_modules/storj/node_modules/levelup/lib/util.js:54

Uncaught LevelUPError: Failed to require LevelDOWN (Could not locate the bindings file. Tried:
 → /opt/storjshare/resources/app.asar/node_modules/storj/node_modules/leveldown/build/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/storj/node_modules/leveldown/build/Debug/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/storj/node_modules/leveldown/build/Release/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/storj/node_modules/leveldown/out/Debug/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/storj/node_modules/leveldown/Debug/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/storj/node_modules/leveldown/out/Release/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/storj/node_modules/leveldown/Release/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/storj/node_modules/leveldown/build/default/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/storj/node_modules/leveldown/compiled/5.1.1/linux/x64/leveldown.node). Try `npm install leveldown` if it's missing

**Comment by littleskunk** [comment]
New binary ready. This time it is running on debian. Tomorrow I will try the new binary on ubuntu and publish it.

**Comment by littleskunk** [comment]
Good news. The new binary is working on ubuntu and debian. I replaced the latest binary. Please download and install it again.

**Comment by darkbluelight** [comment]
Nice, it's working again.
