### ISSUE TITLE
Still Broke v0.8.2 storjshare-gui.osx64.dmg

### ISSUE THREAD

**Issue by gregbenner** [Storj/storjshare-gui#240]
<img width="506" alt="screen shot 2016-06-12 at 7 20 02 pm" src="https://cloud.githubusercontent.com/assets/1177690/15994470/5f476f6c-30d3-11e6-893c-a5a2ec50a24a.png">

<img width="695" alt="screen shot 2016-06-12 at 7 22 52 pm" src="https://cloud.githubusercontent.com/assets/1177690/15994472/67e64cec-30d3-11e6-904f-e3cddd09e493.png">

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/bridge/issues/91
