### ISSUE TITLE
Prevent infinite 'No Tunnelers' alerts - still not fixed for me

### ISSUE THREAD

**Issue by darkbluelight** [Storj/storjshare-gui#242]
Hi, after #239 was fixed I could run Storj Share again, but around a minute later I started to get the "no tunnelers" alerts :(, see #224.
So at the moment I'm still not able to run it. For details about my system see #239. There is no useful message in the developer console imo.

**Comment by littleskunk** [comment]
Reason for this: https://github.com/Storj/core/issues/172

**Comment by super3** [comment]
Can confirm. Getting infinite "No Tunnelers" alerts again.

**Comment by super3** [comment]
@bryanchriswhite @bookchin @boshevski How do we handle this better on the GUI application? We don't want to suppress the error, but we need display it better and a message box that you can never close. 

If the application should draw attention to itself once(when it fails to connect on start or disconnects from currently connected), after that it should display a prominent message that it has not found tunnelers and is not able to connect. It should not continue to draw attention to itself after we already know that it is broken.

**Comment by rasheedmoore** [comment]
rpc call c98efb42b89ab1b09a9c8dab648c145d381a1618 timed out
{info} [Fri Jun 17 2016 11:27:13 GMT-0700 (PDT)]
sending OPEN_TUNNEL message to {"protocol":"0.7.0","address":"storj-adm-002.storj.space","port":4260,"nodeID":"94fb7882343b21ec027452fd574e9d8f225f9c28","lastSeen":1466188033166}
{warn} [Fri Jun 17 2016 11:27:15 GMT-0700 (PDT)]
missing or empty reply from contact
{warn} [Fri Jun 17 2016 11:27:28 GMT-0700 (PDT)]
missing or empty reply from contact
{warn} [Fri Jun 17 2016 11:27:33 GMT-0700 (PDT)]
rpc call c929388a9aa7587586cf57e7f7300ba56b4036f2 timed out
{info} [Fri Jun 17 2016 11:27:33 GMT-0700 (PDT)]
sending OPEN_TUNNEL message to {"protocol":"0.6.16","address":"75.70.181.20","port":4000,"nodeID":"6750e22dd6f96e111f6c0f89f12170d85764c717","lastSeen":1466188053167}
{warn} [Fri Jun 17 2016 11:27:48 GMT-0700 (PDT)]
missing or empty reply from contact
{warn} [Fri Jun 17 2016 11:27:53 GMT-0700 (PDT)]
rpc call eef892876dec787848714f8e68119237f691f9dd timed out
{info} [Fri Jun 17 2016 11:27:53 GMT-0700 (PDT)]
sending OPEN_TUNNEL message to {"protocol":"0.7.0","address":"104.196.135.20","port":8532,"nodeID":"9fa08a5994082f67086cbb00900f0a1e0502e245","lastSeen":1466188073171}
{warn} [Fri Jun 17 2016 11:28:08 GMT-0700 (PDT)]
missing or empty reply from contact
{warn} [Fri Jun 17 2016 11:28:13 GMT-0700 (PDT)]
rpc call 1f1be79113bc04740c9c994d0a86b17c3d460a6a timed out
{info} [Fri Jun 17 2016 11:28:13 GMT-0700 (PDT)]
sending OPEN_TUNNEL message to {"protocol":"0.6.10","address":"api.storj.io","port":57322,"nodeID":"c4c081fe65a47e993bb6d49ebc36fcfa5cca48b1","lastSeen":1466188093064}
{warn} [Fri Jun 17 2016 11:28:17 GMT-0700 (PDT)]
missing or empty reply from contact
