### ISSUE TITLE
Upgrade to v0.8.2: Javascript Error on install

### ISSUE THREAD

**Issue by markayre** [Storj/storjshare-gui#243]
On Windows, upgraded to v0.8.2. Removed the previous version and started to install the latest update and received the following error (see attachment).
![screen shot 2016-06-14 at 16 04 53](https://cloud.githubusercontent.com/assets/11960543/16062719/ef00dff4-3249-11e6-93db-962c8224f7a6.png)

Rebooted the server and completely uninstalled the application (leaving user data in place) and got the same error.

**Comment by littleskunk** [comment]
%appdata%\Storj Share\settings.json is corrupted. If you can reproduce it please let us know so we can fix it.

**Comment by markayre** [comment]
Removing the Storj Share directory from the AppData directory resolved the issue, for some reason the settings.json became empty during the upgrade. 

Was not able to reproduce when i tried the full steps again (uninstalled v8.2, installed v7.5 and ran for a few minutes, upgraded to v8.2). 

Only issue i had was during the uninstallation of v8.0.2, ticking remove personal data did not delete directory in AppData.

Thanks @littleskunk for the prompt fix!
