### ISSUE TITLE
6.0 KB Free Space When I have actually 290GB - 300GB free space to share with STORJ SHARE

### ISSUE THREAD

**Issue by JorgMarkwald** [Storj/storjshare-gui#247]
I was redirected here to report a bug/issue. I'm running STORJ Share on Mac OS X 10.11. I've been using older versions of STORJ share in the past and I didn't have this issue ... so when i saw this i thought it's a bug that will get fixed in the next release. But I've been updating ever since and it still shows 6.0 KB (tried formatting the partition in various formats but gave me the same result). The log keeps updating and I can see that STORJ is working so this makes me think it's just a UI issue ... I have the space and it's working it's just the visual number that the user receives being faulty.

Hope this will be fixed soon.
Jorg

**Comment by littleskunk** [comment]
Please try again with this binary: https://github.com/Storj/storjshare-gui/releases/download/v0.8.4/storjshare-gui.osx64.diskspacehotfix.dmg

If it works I will create a pull request: https://github.com/SuperPaintman/fd-diskspace

**Comment by mattaickin** [comment]
Have downloaded this update. I am sharing 100GB but Storjshare reports 119.9MB freespace.

still reports inacurate free space amount.

**Comment by littleskunk** [comment]
`df -k` and storage location please

**Comment by JorgMarkwald** [comment]
I'm also using the latest version. That's when I decided I should report this since it hasn't been fixed.
Now it shows me I have -1024 B 
... 
![screen shot 2016-06-22 at 09 29 56](https://cloud.githubusercontent.com/assets/20070653/16256656/6294ceae-385c-11e6-9b2c-abec9d92f77c.png)
![screen shot 2016-06-22 at 09 31 00](https://cloud.githubusercontent.com/assets/20070653/16256681/7912adea-385c-11e6-8ada-591218a73dc2.png)

**Comment by littleskunk** [comment]
the latest version still has the bug. Only the hotfix version please.

**Comment by JorgMarkwald** [comment]
... the hotfix now shows me "Free Space: 278.4 GB"

**Comment by littleskunk** [comment]
Perfect. I will work on a pull request (https://github.com/SuperPaintman/fd-diskspace).

**Comment by JorgMarkwald** [comment]
Excellent!

**Comment by littleskunk** [comment]
Will be fixed with the next release.
