### ISSUE TITLE
*Bug* Storjshare GUI Mac OSX

### ISSUE THREAD

**Issue by mattaickin** [Storj/storjshare-gui#249]
Just downloaded latest update to Storjshare for Mac - Storj Share 0.8.4 Core Library 1.2.8 Protocol 0.7.0 that addresses disk space available issue.

Bug 1 -  When Storjshare GUI is running, other Mac apps hang on launch. Force quit is needed. Have to quit Storjshare before loading another app successfully. When Storjshare is running - other apps lockup and hang.

Bug 2 - Internet connection slows down to an appalling speed for at least an hour on 1st / 2nd launches of Storjshare. Seems to resolve itself after it has been running for a few hours.

**Comment by littleskunk** [comment]
Bug 1: I was not able to reproduce it. Safari was working without any problem while storjshare GUI was running. Do you have any additional information?

Bug 2: Storjshare will need some download bandwidth (renter uploading files to you). Is your shared storage full now? Than it will stop downloading new shards and you have the full download bandwidth for yourself.

**Comment by mattaickin** [comment]
Avid Pro Tools hangs for the duration that Storjshare is running. Have to
quit Storjshare to release PT hang. Possible memory leak ?


From:  littleskunk <notifications@github.com>
Reply-To:  Storj/storjshare-gui
<reply+0132533d6fcc1dc0f3c2b22490cc4faf9ed64525707a28f692cf000000011383efca9
2a169ce09a0f2c9@reply.github.com>
Date:  Thu, 23 Jun 2016 11:43:22 -0700
To:  Storj/storjshare-gui <storjshare-gui@noreply.github.com>
Cc:  Matt Aickin <matt@mattaickin.com>, Author <author@noreply.github.com>
Subject:  Re: [Storj/storjshare-gui] *Bug* Storjshare GUI Mac OSX (#249)


Bug 1: I was not able to reproduce it. Safari was working without any
problem while storjshare GUI was running. Do you have any additional
information?

Bug 2: Storjshare will need some download bandwidth (renter uploading files
to you). Is your shared storage full now? Than it will stop downloading new
shards and you have the full download bandwidth for yourself.


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Storj/storjshare-gui/issues/249#issuecomment-228145609>
, or mute the thread
<https://github.com/notifications/unsubscribe/ATJTPfQzaZ99Gh8GBvocR34rKiWpzD
2aks5qOtPKgaJpZM4I7L8D> .

**Comment by littleskunk** [comment]
Lets wait for this fix: https://github.com/Storj/storjshare-cli/issues/95
