### ISSUE TITLE
Resizing the GUI window doesn't have expected behavior.

### ISSUE THREAD

**Issue by Zoltu** [Storj/storjshare-gui#252]
When I resize the `Storj Share` GUI window, I expect the log box to resize to fill the space and the various UI elements to remain docked to the bottom/top/left/right sides.  However, when I resize instead what happens is I get a small log window in the middle with the UI elements snapped around it and a ton of whitespace all over:

![image](https://cloud.githubusercontent.com/assets/886059/16365547/f3e43b2a-3bb7-11e6-8f78-b3a2a62f0c39.png)

**Comment by bookchin** [comment]
I'm going to close this in favor of #266 - we will be reworking the UI.
