### ISSUE TITLE
Do not allow users to browse the web via the GUI without full navigation control.

### ISSUE THREAD

**Issue by Zoltu** [Storj/storjshare-gui#253]
At the moment, I can click on the `STORJ SHARE` icon/button in the top left of the GUI which will navigate me (inside the GUI) to the STORJ website.  Unfortunately, there is no back/forward buttons so I am unable to get back to the GUI.  The only solution I have found is to restart the application.

Either add forward/back buttons or simply don't let the GUI act as a web browser.

**Comment by boshevski** [comment]
Clicking on the logo should open up the browser, not display the website inside the GUI.

**Comment by Zoltu** [comment]
In that case some more relevant information:

Windows 10
Edge setup as the default browser.

**Comment by boshevski** [comment]
Thanks @aleitner for the fix.
