### ISSUE TITLE
GUI white screen of death

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#257]
Please add here any information you have. It will help us to find the reason.

**Comment by matanbr** [comment]
Started on the last version (0.8.7) , noticed that RAM usage is increased to around 1000MB during the first hour than the crash happen.
by the way cpu usage on this version is also higher than previous, around 30-50% all the time of use, didnt had it before.
Windows 8.1

**Comment by littleskunk** [comment]
That looks like https://github.com/Storj/storjshare-cli/issues/95

Anyone else with the same result?

**Comment by mo35** [comment]
same as above , when it works (not always , usually i have to restart gui couple times to start receiving  shards , most of times its just sits there and does nothing , background processes just running no cpu usage or ram increase , nat via upnp works) , but when it works ram usage is quite noticable , usualy when consumed ram reaches ~1gb , gui stops responding (black window) , all background processes dies.

**Comment by trippypippy** [comment]
I am having the same issue although I have not noticed the RAM spike mentioned in other posts. I am using Server2012R2 and after a random amount of time running 0.8.8 windows just goes completely black and stops working (no shards). The only way of getting it to start working is to "Quit" the program and start it again. When it is actually working I get shards and everything seems ok with no unusual messages in the log.

**Comment by Blackwolfen** [comment]
Same issue, first it makes many shards and then becomes black. No real reason, ports and all looks good.

**Comment by Blackwolfen** [comment]
Had the same issue today again, i had the developer zone open and it said target disconected, and also in the log of the developer zone i saw could not send telemetric data and stuff.
That issue is getting really annyoing :)

**Comment by Blackwolfen** [comment]
And yesterday i saw in the developer console that around each 10 - 20 time file is in use error when it tried to access the db. Note i have only one Drive shared still it has somehow sync issues. Maybe they lead to a death lock?

**Comment by deadgray** [comment]
After few hours of working GUI client was nothing but black window, transfers seemed to stop too, but top bar with menu responsible, restart from that menu worked.

**Comment by trippypippy** [comment]
Further to what Blackwolfen said I am also seeing a lot of "Failed to Collect telemetry data" with a red number to the left which I assume is the number of tries that have failed (currently 3). Eventually followed by a black screen.

**Comment by littleskunk** [comment]
Please open cmd / terminal to start Storjshare GUI. After GUI crash please check cmd / terminal for any error output.

If you have some debug skill you can create memory snapshots (Developer console->Profiles) . Upload them as ZIP file if you don't know how to read them.

My GUI crashed while I created memory Snapshots. I will try again to be sure.
```
[13624:0704/145315:FATAL:memory_win.cc(38)] Out of memory, size = 25165812
Backtrace:
        (No symbol) [0x002AC8E7]
        (No symbol) [0x002A6E27]
        GetHandleVerifier [0x00308B0E+188270]
        callnewh [0x5A84B3BE+24]
        fcloseall [0x5A82DAB8+34686]
        v8::TypeSwitch::match [0x5486BEAD+1405]
        v8::TypeSwitch::match [0x5491BF13+722403]
        v8::TypeSwitch::match [0x5491D378+727624]
        v8::TypeSwitch::match [0x54910D46+676886]
        v8::TypeSwitch::match [0x5491ACD4+717732]
        v8::TypeSwitch::match [0x5491875E+708142]
        v8::TypeSwitch::match [0x5496DE41+1058065]
        icu_54::IDNAInfo::reset [0x01DAA096+1012838]
        icu_54::IDNAInfo::reset [0x01DA9E6D+1012285]
        icu_54::RegexPattern::operator!= [0x01A43C7C+1882748]
        icu_54::RegexPattern::operator!= [0x01A4CB4B+1919307]
        icu_54::BreakIterator::isBufferClone [0x00395501+215953]
        icu_54::TimeZone::setID [0x00949C5C+5113900]
        icu_54::TimeZone::setID [0x00948FB8+5110664]
        icu_54::TimeZone::setID [0x00949E6D+5114429]
        icu_54::TimeZone::setID [0x009031B7+4824455]
        icu_54::MessagePattern::partSubstringMatches [0x02616EEE+3768542]
        icu_54::MessagePattern::partSubstringMatches [0x02588A25+3185685]
        icu_54::RuleBasedBreakIterator::operator!= [0x00BEA67D+872317]
        icu_54::RuleBasedBreakIterator::operator!= [0x00BEAA1C+873244]
        GetHandleVerifier [0x002F92D5+124725]
        IsSandboxedProcess [0x015D0FF5+163813]
        IsSandboxedProcess [0x015D081D+161805]
        IsSandboxedProcess [0x015D06DD+161485]
        IsSandboxedProcess [0x015D128F+164479]
        GetHandleVerifier [0x002F92D5+124725]
        (No symbol) [0x002C37EC]
        (No symbol) [0x002C2C84]
        GetHandleVerifier [0x002FB49A+133370]
        (No symbol) [0x002C35E0]
        (No symbol) [0x002C359D]
        icu_54::TimeZone::setID [0x0091E8FB+4936907]
        icu_54::BreakIterator::isBufferClone [0x003D288E+466718]
        icu_54::BreakIterator::isBufferClone [0x003D273D+466381]
        icu_54::BreakIterator::isBufferClone [0x003CFBC3+455251]
        (No symbol) [0x0016663D]
        icu_54::Transliterator::setID [0x0221453C+184620]
        BaseThreadInitThunk [0x743838F4+36]
        RtlUnicodeStringToInteger [0x775F5DE3+595]
        RtlUnicodeStringToInteger [0x775F5DAE+542]
        (No symbol) [0x00000000]
```

**Comment by trippypippy** [comment]
Hi The GUI crashed again but this time console was open and I got this message "Inspected Target dosconnected" Once it reloads we will attach to it automatically.

Hope this helps.

**Comment by RedRockMining** [comment]
Unchecked "Send Telemetry Reports". No crashes for 22 hours and counting.

**Comment by byterunner13** [comment]
After few hours of working GUI client was nothing but black window, transfers seemed to stop too, but top bar with menu responsible, restart from that menu worked.

**Comment by littleskunk** [comment]
I created a few RAM snapshots and it looks like to many loglines. I created a new binary with loglevel warn. If you like you can install it and try it again.
https://github.com/Storj/storjshare-gui/releases/download/v0.8.8/storjshare-gui.win32.loglevel.warn.exe

This is not a fix. It is only a workaround and will show us if that is realy the reason for the crash. Lets see how long this version will work without a crash.

Keep in mind that you need a few restart to get a connection to a close node that will send you contracts (core issue). Start your node and wait 5 minutes. Watch for the following logline. If you don't get this line restart your node and try again.
```
{error} [Mon Jul 04 2016 21:36:43 GMT+0200 (Mitteleuropäische Sommerzeit)]
Contract no longer open to offers
```

**Comment by matanbr** [comment]
Well it's like you said , it doesnt fix the problem it's just delaying it.
but at least now it crashed after almost 12 hours ...

**Comment by littleskunk** [comment]
My GUI node with loglevel off is still running with 70MB. -> The log window is the problem. I will try to fix it.

**Comment by RedRockMining** [comment]
Yup, mine crashed too, overnight. Not sure how long, but before I went to bed, one had grown to around 500MB.

**Comment by byterunner13** [comment]
now i'm getting the flag no tunnelers found

**Comment by littleskunk** [comment]
http://stackoverflow.com/questions/8032928/can-i-trigger-javascripts-garbage-collection

**Comment by littleskunk** [comment]
I have to give up. It looks like this code line is the problem:
https://github.com/Storj/storjshare-gui/blob/75b246ac6ac74b3f2082c5f477c714661d91f048/app/lib/logger.js#L48

My memory snapshot is full of log line strings. The garbage collector doesn't delete the old strings and I don't understand the reason for this. Every time this line of code is executed I have one more sting in my memory.

**Comment by RedRockMining** [comment]
I'm not sure how #266 will change this, but using the latest code (0.8.9) this has now turned into a WSD (White Screen of Death) however now, when I select View->Reload I get a javascript error identical to #270, however I can also reproduce #270 without a WSD, i.e. while Storjshare is running.

**Comment by matanbr** [comment]
any chance to make a new binary with loglevel warn for 0.8.9 ?

**Comment by littleskunk** [comment]
@RedRockMining #266 will come with GUI v0.9.0.

@matanbr Give me a few minutes.

**Comment by littleskunk** [comment]
Hotfix:
https://github.com/Storj/storjshare-gui/releases/download/v0.8.9/storjshare-gui.loglevel.info.exe
Same loglevel as the normal GUI release but the reload button is working.

https://github.com/Storj/storjshare-gui/releases/download/v0.8.9/storjshare-gui.loglevel.warn.exe
Reduced logging. This version will crash a few hours later. Watch for `Contract no longer open for offer` to be sure it is running fine.

https://github.com/Storj/storjshare-gui/releases/download/v0.8.9/storjshare-gui.loglevel.off.exe
No logging. This version should not crash and run for days. You can only look into your shard directory to see if it is running fine.

**Comment by MeijeSibbel** [comment]
What i found so far:

- I only get a white-screen on the GUI when storj auto-starts after windows booting.
- After manually resetting the GUI no further issues occur.

**Comment by littleskunk** [comment]
@MeijeSibbel that looks like a new issue. I would expect the "white" screen of death after a few hours. If you get it asap it must be something else. If you can reproduce it please open a new issue. Developer console error messages would help.

**Comment by MeijeSibbel** [comment]
@littleskunk I can reproduce it by just restarting my windows 10 machine and letting storjshare pop-up automatically, it will pop-up with the white screen. Something is not working when the program is first called after booting the PC, the auto-start is messing with the GUI. i hope this info helps.

**Comment by RedRockMining** [comment]
Updated to v0.9.0 this morning just to see if anything had changed, but it looks like it hasn't. Still getting WSD after about an hour and Javascript error #270. Re-downgraded to loglevel.off, which is working fine.  Please let us know how you would like us to proceed.

**Comment by littleskunk** [comment]
@RedRockMining did you notice the advanced options? You can now configurate the loglevel yourself.

**Comment by RedRockMining** [comment]
I didn't, thanks! I'll try Show Errors Only and see how that goes.

**Comment by Felmane** [comment]
This a general view of my gui client. This was taken about 30 minutes after it was running. The memory usage is as You can see about 700mb. 5 minutes later it dropped around 520mb, only to rise up to 600mb 10 minutes later.

![storjiowsod](https://cloud.githubusercontent.com/assets/20446942/16842477/f489a66c-49dd-11e6-8f9b-3443c8907f02.png)

It is running on a fresh install of Win10 Pro 64bit. The hardware is an Acer Laptop 5755G (i7-2670QM - 4gb of ram).
Shards folder is empty, farmer.db folder is shown in the screenshot.

There are 4 processes of Electron in the task manager. The first shown in the screenshot with a CPU usage from 12% to 18%., the other 3 use about 0.1% - 0.3% of processor and from 12mb to 36mb of ram. (I guess the extra processes are for the connections? Since im setup to tunnel up to 3 connections)

The WSOD (white screen of death) happens an hour or two after start. It starts automatically at Windows boot and no problems occur at startup unlike what described by @MeijeSibbel .
Once it happened when I lost connection to the internet, the other times I cannot be certain since I would find it after unlocking the laptop (from the win login screen) or by connecting through remote desktop connection. Maybe it is somehow related?

I tried to set the log level to "debug" too, but there doesn't seem to be anything out of the ordinary.
Hope this helps. If you can tell where are the logs stored i can send you those too.

**Comment by littleskunk** [comment]
@Felmane Configurate loglevel off and it will run for days without any crash. https://storj.readme.io/docs/storjshare-troubleshooting-guide#logfile-and-loglevel
