### ISSUE TITLE
Upgrading GUI without closing Storj GUI

### ISSUE THREAD

**Issue by NutterzUK** [Storj/storjshare-gui#258]
As a user, when prompted about an update, I would like to download and install the latest version of Storj GUI so that I can always be up to date.

After following the link to get the binary (.exe) file, the installation fails unless I remember to close the existing storj GUI. Tested on Windows 10.

![image](https://cloud.githubusercontent.com/assets/1153406/16515111/e8910ef2-3f67-11e6-9e41-00970a576f82.png)

Possible solutions:

- Prompt the user to close any existing storj clients.
-  Close storj before updating.

**Comment by pinetor** [comment]
Also a Win10 User.
For me it was not a matter of "closing" the gui. I had to go to Task Mgr to END all the open ( 3) storj entries there.
