### ISSUE TITLE
Error: Invalid report supplied(…) undefined

### ISSUE THREAD

**Issue by pinetor** [Storj/storjshare-gui#269]
I was a TGB user for several months with no issues. I took a break and now hope to re-join for TGB. However when installing the new client on WIN10 I get the following issue:
```
Vue warn]: Error when evaluating expression "tab.active": TypeError: Cannot read property 'active' of undefinedwarn @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:1019
C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:10069 Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
client.js:420 [telemetry] sending report Object
client.js:422 [telemetry] null Success
client.js:420 [telemetry] sending report Object {storage: Object, bandwidth: Object, contact: Contact, payment: "12PV3X6Rq2kL9jdfuZD72NVP7Gh5jM6kvi"}
client.js:422 [telemetry] Error: Invalid report supplied(…) undefined
client.js:420 [telemetry] sending report Object {storage: Object, bandwidth: Object, contact: Contact, payment: "12PV3X6Rq2kL9jdfuZD72NVP7Gh5jM6kvi"}
client.js:422 [telemetry] Error: Invalid report supplied(…) undefined
client.js:420 [telemetry] sending report Object {storage: Object, bandwidth: Object, contact: Contact, payment: "12PV3X6Rq2kL9jdfuZD72NVP7Gh5jM6kvi"}
client.js:422 [telemetry] Error: Invalid report supplied(…) undefined
client.js:420 [telemetry] sending report Object {storage: Object, bandwidth: Object, contact: Contact, payment: "12PV3X6Rq2kL9jdfuZD72NVP7Gh5jM6kvi"}
client.js:422 [telemetry] Error: Invalid report supplied(…) undefined
```

repeating log entries:

```
{info} [Thu Jul 07 2016 21:32:42 GMT-0500 (Central Daylight Time)]
sending FIND_NODE message to {"protocol":"0.7.1","address":"108-90-22-140.lightspeed.cicril.sbcglobal.net","port":4000,"nodeID":"6735793f6e1041678aee205901fa7dc6548a10f6","lastSeen":1467945162954}
{error} [Thu Jul 07 2016 21:32:43 GMT-0500 (Central Daylight Time)]
failed to handle message, reason: Unexpected end of JSON input
 ```

**Comment by littleskunk** [comment]
Please klick on the Objects to open them and give us the full report.

**Comment by bookchin** [comment]
Those two issues are unrelated. The first I assume is a bug in the telemetry report (either storage or bandwidth). The other is a misbehaving farmer and nothing to worry about.

**Comment by pinetor** [comment]
As requested from the console:
Object {storage: Object, bandwidth: Object, contact: Contact, payment: "12PV3X6Rq2kL9jdfuZD72NVP7Gh5jM6kvi"}bandwidth: Objectcontact: Contactpayment: "ArQsssH92ReAe1xV+O/9HQcHtiI/L4OFeqKDDZvVIdlr4+XblCsrIxkc6nP1A0BE/KcGiQNPz0ebPNB+SxdCEPdOHSxTIU3GBCGRnwNC6gRoVXIexBsWp3+BNajhhYBOPJBxuf0dJUmwk3GlL/mQToQrXU7NcpNxxBiBddAa2jIr"signature: "Hwyg+jWGyxCNSZRoAp2clgxclMcFCKb2rbyU4s3NjBnPP+RKDl9zvqgacr93Gs/AH1oe8W4DTAv9Aow1Kno3l/8="storage: Objecttimestamp: 1468200670826__proto__: Object
client.js:422 [telemetry] Error: Invalid report supplied(…) undefined


Sorry for the lateness in responding.. I was out of town over the weekend

**Comment by littleskunk** [comment]
Please open the storage, bandwidth and contact Object as well.

**Comment by pinetor** [comment]
As requested:
Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
client.js:389 [telemetry] sending report Object {storage: Object, bandwidth: Object, contact: Contact, payment: "12PV3X6Rq2kL9jdfuZD72NVP7Gh5jM6kvi"}bandwidth: Objectdownload: 18.03upload: 1.84__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()contact: Contactaddress: Object#: "192.168.1.150"@: Objectdt:dt: "string"xmlns:dt: "urn:schemas-microsoft-com:datatypes"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()lastSeen: 1468292219008nodeID: "f2fb9e7299cb410d668e5653f01c469699695c17"port: 52290protocol: "0.7.1"__proto__: AddressPortContactconstructor: Contact(options)arguments: (...)caller: (...)length: 1name: "Contact"prototype: AddressPortContactsuper_: AddressPortContact(options)__proto__: ()<function scope>__proto__: Contact_createNodeID: ()constructor: AddressPortContact(options)toString: ()valid: ()__proto__: Objectpayment: "ArQsssH92ReAe1xV+O/9HQcHtiI/L4OFeqKDDZvVIdlr4+XblCsrIxkc6nP1A0BE/KcGiQNPz0ebPNB+SxdCEPdOHSxTIU3GBCGRnwNC6gRoVXIexBsWp3+BNajhhYBOPJBxuf0dJUmwk3GlL/mQToQrXU7NcpNxxBiBddAa2jIr"signature: "HyiYpDymgFbtqR03OTnOK+X+Vab5a2TRPtCDHHKYOFKsNfXCguaStpq4xJ910T614jJB4vFYrXip//4MLCGkmKk="storage: Objectfree: 536870912000used: 0__proto__: Objecttimestamp: 1468292270635__proto__: Object

**Comment by littleskunk** [comment]
I reproduced it as good as I can but my report is working fine:

[telemetry] sending report Object {storage: Object, bandwidth: Object, contact: Contact, payment: "18KGUfU2BXUm1e1KtCCrmz1Mdum4rGNvWt"}bandwidth: Objectdownload: 2.15upload: 2.05__proto__: Objectcontact: Contactaddress: "192.168.1.150"lastSeen: 1468303316986nodeID: "8f22f4efdacf9de3333f8cb2e28f6e534173d705"port: 52290protocol: "0.7.1"__proto__: AddressPortContactpayment: "A26kqAzY6n1jHM074AsGUqftTD1498HeikMrjzek7j+7vedSfAN18R2oq2kayDTscwVdPRaYWwcw6a0lCi8eZKu/5RPqEDzgN005PMJqouOp68uC8ZJMv1cfNsMlDoNv1ZOKlOyMga2iswOiqS+2XXRHpzfO2EgDnZACj1y21MvA"signature: "H7BhkNen6i9EF1ej3pfDZz7dPQtHwPV5p0/8Y8JKpak6IcWL0WZk/YPGwNJb0kZTyMmWUUYdtV8Y11ahemEUvPM="storage: Objectfree: 536870912000used: 0__proto__: Objecttimestamp: 1468303317104__proto__: Object

**Comment by littleskunk** [comment]
Contactaddress: Object#: "192.168.1.150"@: Objectdt:dt: "string"xmlns:dt: "urn:schemas-microsoft-com:datatypes"proto: Object__defineGetter__: defineGetter()defineSetter: defineSetter()lookupGetter: lookupGetter()lookupSetter: lookupSetter()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get proto: proto()set proto: proto()proto: Object__defineGetter__: defineGetter()defineSetter: defineSetter()lookupGetter: lookupGetter()lookupSetter: lookupSetter()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get proto: proto()set proto: proto()

The main difference is the IP address. In your case it is not only a simple string. Do you use UPnP? If so the problem could be this line of code: https://github.com/Storj/core/blob/master/lib/network/transport.js#L87

**Comment by littleskunk** [comment]
@pinetor please try this version: https://github.com/Storj/storjshare-gui/releases/download/v0.9.1/storjshare-gui.telemetry.hotfix.exe

**Comment by littleskunk** [comment]
I was not able to reproduce the error on a linux system but at least my bugfix doesn't throw any new error.

**Comment by pinetor** [comment]
@littleskunk I apologize for not getting back sooner. 
The new version DID correct the telemetry logging issues. I continue to fail to connect to the network. I have done all I can on the PC that I use, and believe that it may be an issue with my routers firewall. At this time I cannot change the current setup without disrupting other local network resources. This may change in future if I get off the AT&T network.
