### ISSUE TITLE
StorjShare - blank

### ISSUE THREAD

**Issue by allx1** [Storj/storjshare-gui#271]
Hi,

After running the StorjShare I can only see a 'blank' StorjShare - see the file attached. 
The only button that is working is the reload one, which leads to a JavaScript Error.I have the latest version of the StorjShare. 

Ales

![storj_blank](https://cloud.githubusercontent.com/assets/17143942/16682918/34c68ef6-44fd-11e6-8d37-5de722d1c1ac.JPG)
![storj_blank_2](https://cloud.githubusercontent.com/assets/17143942/16682929/4ab0940a-44fd-11e6-8585-63dacd5c9b7c.JPG)

**Comment by littleskunk** [comment]
Duplicate: #257 and #270

**Comment by allx1** [comment]
I think that deleting some old setting/files might help, but I do not know which ones...
