### ISSUE TITLE
JS stacktrace

### ISSUE THREAD

**Issue by soeren-b-c** [Storj/storjshare-gui#273]
The gui freezes.
Terminal output below. I run storj from the .deb file

$ ./storjshare

<--- Last few GCs --->

4790566 ms: Mark-sweep 1094.2 (1418.7) -> 1088.7 (1418.7) MB, 105.0 / 20.0 ms [allocation failure] [GC in old space requested].
4790663 ms: Mark-sweep 1088.7 (1418.7) -> 1088.7 (1418.7) MB, 96.2 / 16.1 ms [allocation failure] [GC in old space requested].
4791138 ms: Mark-sweep 1088.7 (1418.7) -> 1100.6 (1403.7) MB, 473.8 / 377.1 ms [last resort gc].
4791609 ms: Mark-sweep 1100.6 (1403.7) -> 1112.5 (1403.7) MB, 471.1 / 380.1 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3d2db7214a59 
1: get [/home/storj/storj-deb-install/opt/storjshare/resources/app.asar/node_modules/vue/dist/vue.common.js:~573] pc=0xb99bd3f0014
2: arguments adaptor frame: 1->2
3: stringToFragment(aka stringToFragment) [/home/storj/storj-deb-install...

Can't reproduce, but has happened 2-3 times.

**Comment by littleskunk** [comment]
Out of memory like https://github.com/Storj/storjshare-gui/issues/257
