### ISSUE TITLE
CLI 1.3.1 Unhandled Error

### ISSUE THREAD

**Issue by doodlemania2** [Storj/storjshare-gui#274]
Multiple consistent errors to a host causes upload to fail, other shards succeed though:

[info]   Contract negotiated with: {"protocol":"0.7.1","address":"misker.xyz","port":9001,"nodeID":"2051a93b67b55aad24713a4f621dc5bdd0ae7f97","lastSeen":1468101884057}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 162.255.119.249:9001
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)

Should try again then move to another host (and ideally mark that host as unhealthy somehow).

**Comment by bookchin** [comment]
Implemented in core 2.0.0
