### ISSUE TITLE
Log wrapping

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-gui#279]
This is a copy of a request referenced in one of the cli issue threads.

Please implement a log wrapping function to limit the amount of space used by log files.  At log level 3, on one node of the cli, I am generating about a GB of log per day.  Suspect having a wrapping function based on size and/or time (e.g. limit to 100MB, limit to the last 4 hours of activity) would be quite beneficial.

**Comment by super3** [comment]
@1credit Sorry but have to close this for priority sake. If you select log level 3 you are just going to get big logs. This is not the case for average users.
