### ISSUE TITLE
SJCX balance not showing

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-gui#280]
Running 0.9.1 and not seeing my SJCX balance.  Did not see it in the previous two releases either.  Running under Windows 7.

Problem tracked down to a leading space in settings.json's address field.

Recommend sanity checking that field during initial configuration to assure its valid.

**Comment by mabelcorn** [comment]
Hi, I have exactly the same problem.

Storj Share 4.0.8
Core Library 6.0.11
Protocol 1.0.0

My counterwallet shows 33.4443 SJCX (yeah, I know it's nothing :P) but the gui shows 0.

Just letting you know as this "account balance" is one of the indicators showing user that actually system is working - well, 0 tells wrongly it's not.
