### ISSUE TITLE
Bandwidth Controls

### ISSUE THREAD

**Issue by christopherai** [Storj/storjshare-gui#281]
It would be nice to have settings to throttle and control bandwidth usage. I know this can be done through a good router but scheduling is a hard to find feature. Many ISP's allow unlimited bandwidth usage during off peak hours. Having a scheduler built into the UI will make it easy to throttle the bandwidth during peak internet usage periods. Many farmers with ISPs that have bandwidth limits would find this useful.

A minimum speed setting of 1mb/s or something like that should be enforced in order to not effectively turn off the farmer.

Example of scheduler taken from bittorrent client:
![scheduler](https://cloud.githubusercontent.com/assets/20424483/16777449/715f7dcc-481e-11e6-920c-75dc3589a7a3.jpg)

**Comment by super3** [comment]
There are 3rd party programs and system configurations you can use to limit Storj Share's bandwidth usage. While this is a feature we would like in the future, to focus on it now would be premature. You can bring it back up again in 2-3 months.
