### ISSUE TITLE
v0.9.1 Windows Still Crashes Frequently

### ISSUE THREAD

**Issue by WilhelmGGW** [Storj/storjshare-gui#283]
WHITE SCREEN OF DEATH. Just as in previous versions.

I have installed on three Widows 7 machines, and every one of them has crashed at least once in the first 24 hours.

**Comment by sigwo** [comment]
I had this happen as well. I clicked 'View' -> 'Reload' (or ctrl+r) and all is well. Not preferred, but could be a workaround.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/257
