### ISSUE TITLE
Networking basics document might help resolve issues

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-gui#284]
After haunting the Slack support channels for a few days, I noticed a pattern of issue all centered around the network configuration.  I suspect a basic network document would be useful to help educate people on what IP addresses are, what DHCP is, DNS, UPnP, "ports", etc.

To that end, I humbly submit the attachment.
[Networking 101 for Storj Users.docx](https://github.com/Storj/storjshare-gui/files/367518/Networking.101.for.Storj.Users.docx)

**Comment by bookchin** [comment]
This is sweet. I'm going to see if we can add this to http://docs.storj.io/

**Comment by 1credit** [comment]
Thanks!

**Comment by super3** [comment]
@1credit Mind emailing this to me at shawn [at] storj.io? We can also give you a bounty for this.

**Comment by bookchin** [comment]
@super3 can't you click and download? :confused:

**Comment by super3** [comment]
@bookchin This is worth the $200 bounty we have for content. Wanted to move the payment details and discussion out of Github since 1credit doesn't have an email listed on Github.

**Comment by super3** [comment]
Moved to email. Closing.
