### ISSUE TITLE
Problem updating Ubuntu with Storj installed

### ISSUE THREAD

**Issue by mariuspo** [Storj/storjshare-gui#287]
Package Versions

Ubuntu 16.04
Storj Share : 0.9.1
Core Library: v1.4.0
Protocol: 0.7.1

node --version not installed
Expected Behavior

sudo apt-get upgrade working
Actual Behavior

Errors were encountered while processing:
storjshare
E: Sub-process /usr/bin/dpkg returned an error code (1)

Steps to Reproduce

    sudo apt-get update
    sudo apt-get upgrade

**Comment by super3** [comment]
There has been a new release since you made this issue. Please confirm that this issue still exists: 
https://github.com/Storj/storjshare-gui/releases/tag/v1.0.0

**Comment by mariuspo** [comment]
It's fixed, thank you!
