### ISSUE TITLE
Failed to collect telemetry data Win 10 GUI 1.0.0

### ISSUE THREAD

**Issue by pjpavel** [Storj/storjshare-gui#289]
client.js:326 Failed to collect telemetry data(anonymous function) @ client.js:326
done @ C:\Program Files (x86)\Storj Share\resources\app\lib\utils.js:21
(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:52
done @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:241
(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:44
(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\lib\utils.js:34
(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\lib\utils.js:15
(anonymous function) @ fs.js:117

**Comment by littleskunk** [comment]
Please klick on the Objects to open them and give us the full report.

**Comment by remeika1994** [comment]
remeika
7:01 PM function send() {
         utils.getDirectorySize(tab.storage.path, function(err, size) {
           if (err) {
             return console.error('Failed to collect telemetry data');
           }
7:02 userdata.saveConfig(function(err) {
       self.transitioning = false;
7:02 if (tab.farmer) {
       tab.wasRunning = false;
       tab.farmer().leave(function() {
         if (self.userdata.appSettings.reportTelemetry) {
           self.stopReportingTelemetry(tab);

**Comment by heunland** [comment]
#300 is related to this

**Comment by heunland** [comment]
additional information user remeika1994 posted on the slack: https://storjcommunity.slack.com/archives/storjshare/p1469376114002588

unction send() {
         utils.getDirectorySize(tab.storage.path, function(err, size) {
           if (err) {
             return console.error('Failed to collect telemetry data');
           }

[11:02]  
userdata.saveConfig(function(err) {
       self.transitioning = false;

[11:02]  
if (tab.farmer) {
       tab.wasRunning = false;
       tab.farmer().leave(function() {
         if (self.userdata.appSettings.reportTelemetry) {
           self.stopReportingTelemetry(tab);

**Comment by remeika1994** [comment]
thank you very much :)

**Comment by bioloo** [comment]
Get this issue 
![1](https://cloud.githubusercontent.com/assets/20647349/17111689/fd8d860c-52a2-11e6-899a-22078e7d9502.jpg)

**Comment by Miskerest** [comment]
I also have this issue, though I am behind a NAT as my main internet connection is via LTE. I would be happy to post whatever logs you may need.

![image](https://cloud.githubusercontent.com/assets/14872607/17255346/d292de84-5586-11e6-97d2-462ccdc75c1a.png)

i'm also not getting any SJCX, not sure if it's a bug or not, or if my client really isn't sending telemetry data/client data.
