### ISSUE TITLE
GUI client for Rapsberry Pi

### ISSUE THREAD

**Issue by pcatana** [Storj/storjshare-gui#292]
Hi guys! 
I think it's the time to make this request. 
I've been reading the slack channels and there's questions about how to set up a raspberry pi to work with storj. 
Guys, we would love to have a client for this device. 

PS: And of course, keep up with the good work.

**Comment by super3** [comment]
We are working on this right now for an upcoming conference. We will post the documentation when we are done.

**Comment by super3** [comment]
@pcatana I misspoke. The GUI will not be supported on the rasberry pi. Electron, the framework we use for the GUI does not support it. If you want to run Storj Share for the rasberry pi you must use https://github.com/storj/storjshare-cli
