### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by soeren-b-c** [Storj/storjshare-gui#295]
I also suffer from the "White screen of death". Don't know if these issues are related, but opening now as new issue, as this doesn't happen every time I encounter White screen of Death.

I get lines like these in the logs from time to time. Notice that the farmer.db/LOG has a timestamp of 1900/01/00

from farmer.db/LOG:
1900/01/00-00:00:00.981515 7f4f7f4e4700 Compaction error: IO error: /home/storj/mount-disks/storj-seagate_ST3500418AS/farmer.db/027266.ldb: Too many open files
1900/01/00-00:00:00.418562 7f6585e0d700 Compaction error: IO error: /home/storj/mount-disks/storj-seagate_ST3500418AS/farmer.db/027699.ldb: Too many open files

From .config/Storj/Drive-1_2016-7-21.log:
{error} [Thu Jul 21 2016 09:45:27 GMT+0200 (CEST)] IO error: /home/storj/mount-disks/storj-seagate_ST3500320AS/farmer.db/313747.ldb: Too many open files

My system:
Storj Share 1.0.0
Core Library 2.0.2
Protocol 0.7.1

Ubuntu 16.04
Linux 4.4.0-31-generic

**Comment by super3** [comment]
@soeren-b-c Please upgrade to https://github.com/Storj/storjshare-gui/releases/tag/v1.0.1 which should fix that issue.
