### ISSUE TITLE
GUI 1.0.1 SLOW memory growth

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-gui#296]
Shortly after launch the primary Storj Share.exe process settles in with a memory commit footprint of ~116MB on my PC running under Windows 7.

After running for about 11 hours, I see a committed memory footprint varying from ~180mb to 190mb, implying there is a slow memory leak.

Warning and Error logfile attached.
[Drive-0_2016-7-22.zip](https://github.com/Storj/storjshare-gui/files/378090/Drive-0_2016-7-22.zip)

**Comment by Blackwolfen** [comment]
growth happens as well but it still counts shards for more than 5 hours so not sure where it ends...
Memory is at 450mb now started with around 120mb

**Comment by super3** [comment]
@1credit What version of the GUI are you using?

**Comment by 1credit** [comment]
1.0.1 of course

**Comment by aleitner** [comment]
Does memory usage grow when not farming? Does it drop after the initial shard count finishes?

**Comment by Blackwolfen** [comment]
Soooo after more than 9 hours its done... shards counted ... memory usage is around 400 mb it did go down a little but not as much as it was on start. 200 gb shards result in around 112657 contracts... 
But it not crashed so lets see how it evolves.

**Comment by 1credit** [comment]
My memory growth numbers were based on a restart after the shards were counted.  Not sure what you mean by "when not farming"?

**Comment by utdrmac** [comment]
+1 My windows gui (1.0.1) on a fresh restart shows a total of about 130MB (73MB, 16MB, 41MB) of RAM between 3 StorjShare.exe processes. (I've got 2 drive shares). Earlier this morning, after the GUI had been running all weekend, the total was above 200MB. One of my drives was 100% and the other was about 25%.

**Comment by littleskunk** [comment]
My CLI nodes is performaning a leveldb compact at the moment. Memory slowly growing. I would expect the same on the GUI.

If you have the problem on the GUI again. Please upload `farmer.db\LOG` file located in the storage directory. If you have more than one drive upload them all.
