### ISSUE TITLE
Launch Storj with a below normal priority.

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-gui#299]
Storj is suppose to be a background task - as such it should be launched with a below normal or perhaps even a low priority to minimize the impact it has on interactive processes.  Currently it is being launch at normal priority and therefore competes with those.

This is particularly important for desktop environments the GUI is designed to run on.

Current the GUI has a visible impact on other processes, such as Skype when screen sharing.

Priority should fix CPU competition.  Network competition may remain a problem and also needs to be addressed or adoption will be low within the general population.  Look at how BOINC does this for an outstanding example.

**Comment by 1credit** [comment]
Network utilization is becoming a problem on the GUI.  So far I've experienced complaints from clients getting grainy Skype shared screens, Skype lagging, and have had multiple occurrences of mail sending timing out to external smtp host (so far to a private mail server, google mail (gmail), and apple mail (me.com).

**Comment by bookchin** [comment]
This should get resolved as a result of this: https://github.com/Storj/core/issues/257 and https://github.com/Storj/core/issues/143

**Comment by bookchin** [comment]
Also, please read through this, as for why we cannot set priority: https://github.com/electron/electron/issues/2101

**Comment by 1credit** [comment]
Only thinking of this for the Windows GUI - Linux users are savvy enough to fiddle with nice values when they launch if they so desire.

**Comment by bookchin** [comment]
Understood, but unfortunately there is no way for us to set the priority using electron.
