### ISSUE TITLE
Hidden folder name for storage gives problems

### ISSUE THREAD

**Issue by pvdl** [Storj/storjshare-gui#301]
It gives problems when I use a hidden folder name like /home/user/.storjdrive for storage.
The connected peers stick to 1 and Contracts don't increase.
Also the folder name doesn't show up in the 'Drives' section of the systray icon.
  
When I change the folder name to e.g. /home/user/storjdrive, all went well.

Using Linux Mint 18. Storj Share 1.0.1.
Clean install.

**Comment by bookchin** [comment]
There should be no affect on network connectivity based on the drive path selected. I believe this is a result of https://github.com/Storj/core/issues/221
