### ISSUE TITLE
Windows progress bar GUI chews up CPU

### ISSUE THREAD

**Issue by utdrmac** [Storj/storjshare-gui#302]
I have the GUI open on Windows 7 (Quad i7, 16GB, 512GB ati graphics card). The blue progress bar, representing the amount of space used by contracts, has some constant animation, even when at 100% full. This is causing StorjShare.exe to use an unnecessary high amount of CPU (25%-50%) and makes overall responsiveness within the GUI extremely sluggish. Clicking on the menu in the upper right, next to the gear, to switch between drives takes a good 2-3 seconds to render and execute.

Please remove the animation of the progress bar. It is unnecessary fluff.

**Comment by bookchin** [comment]
Are you certain that the CPU usage is related to the progress bar animation? I tend to think otherwise. I'd be interested to see if you open the developer tools, inspect the DOM, and delete the progress bar, if this persists. 

I can't imagine that much CPU being used by a CSS animation, but rather the processing of incoming messages that your node is receiving.

**Comment by utdrmac** [comment]
You are correct in that I did not fully investigate this. I made an assumption because, usually, constant animations _are indeed_ a source of high CPU. But I will give your suggestion a try; delete the bar and see what happens. Can I flip this issue to be a feature request to remove the animation altogether? The animation is quite pointless.

**Comment by bookchin** [comment]
Of course, but if the animation ends up not being the source of the issue, I will have to respectfully defer the decision to remove it to @boshevski - who handles our UX stuff.

Let me know what you find, thanks for the report.

**Comment by bookchin** [comment]
This should get resolved with #259 and https://github.com/Storj/core/issues/143
