### ISSUE TITLE
Cannot get Storj GUI to initiate on Ubuntu LTS 14.04

### ISSUE THREAD

**Issue by thevinci** [Storj/storjshare-gui#303]
I get this in the crash report:
storjshare crashed with SIGABRT in node::SyncProcessRunner::TryInitializeAndRunLoop()

Looking at Dev Console, I get:
child_process.js:525 Uncaught Error: spawnSync /bin/sh EMFILEexports._errnoException @ util.js:949spawnSync @ child_process.js:460execSync @ child_process.js:516childProcess.(anonymous function) @ ELECTRON_ASAR.js:603_diskSpace @ /opt/storjshare/resources/app.asar/node_modules/fd-diskspace/bin/index.js:198diskSpaceSync @ /opt/storjshare/resources/app.asar/node_modules/fd-diskspace/bin/index.js:232getFreeSpace @ client.js:516(anonymous function) @ /opt/storjshare/resources/app.asar/node_modules/vue/dist/vue.common.js:216(anonymous function) @ client.js:569

**Comment by bookchin** [comment]
This looks like an issue with diskspace module.
