### ISSUE TITLE
Show 0 SJCX in wallet after a few seconds

### ISSUE THREAD

**Issue by FloGerlich** [Storj/storjshare-gui#310]
The latest version (GUI 1.0.3) shows me on startup that I have SJCX in my wallet, but after a few seconds it show 0 SJCX.

If I close "Storj Share" and reopen it, the same behaviour appears: A few seconds with the correct amount, then goes down to 0.

edit: after a while the correct amount shows up again. Really toggling between both.

**Comment by pvdl** [comment]
Saw this behavior also yesterday.
Using Linux Mint 18, With 1.0.3. (also version 1.0.2)

**Comment by super3** [comment]
@FloGerlich It would be extremely  helpful if you could record a small video or GIF of the behavior.

**Comment by utdrmac** [comment]
+1 this just happened to me as well. Balance shows correct then 1/2 sec later, goes back to 0

**Comment by utdrmac** [comment]
Seems to flip-flop back-n-forth between my balance and 0. Can't tell if it's happening every X seconds or from the result of some GUI interaction I'm doing.

**Comment by MeijeSibbel** [comment]
Same thing also happened to me, but only when my internet is unstable, meaning that i would not loose connection to my router, just the internet signal for a short instant, this is what triggers it on my machines every time. It gets resolved if i stop and then start storj again, rebooting the router also helped.

**Comment by MeijeSibbel** [comment]
Issue is still persisting in GUI v 1.04.
