### ISSUE TITLE
[telemetry] Error: certificate is not yet valid(…) undefined

### ISSUE THREAD

**Issue by qosmos01** [Storj/storjshare-gui#312]
Getting these errors in the developer view. Directed on slack to create issue. 

### Versions

Storj Share GUI 1.0.3
Core Library 2.0.7
Protocol 0.7.1
OS: Windows 2012R2

C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:1019 [Vue warn]: Error when evaluating expression "tab.active": TypeError: Cannot read property 'active' of undefinedwarn @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:1019
C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:10069 Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
client.js:407 [telemetry] sending report Objectbandwidth: Objectcontact: Contactpayment: "A6spLS42qGfgT5Ae69MaQ5UAfHAOkzdi0vp8ir62Z0mhbAgNIiErIEQesZ4lOV/UC3D7P+GsqwcBbBrNDSmzdr6OQ4u4cQn/r7iQv2Ht47gb15nMO2zUmkaPs0XebLpJVkHWV6CVsJPG48JbtqTGoLdLFGypdAugr0bSY6RCAHEY"signature: "IAAtDfGvvO/VwTFgW/TrP/GvD+WDyntC5MmL/Nqx2YxBBcRxcEWKtY4sbJlizv5we96vW0ZWX/sTivZaaB/aOzM="storage: Objecttimestamp: 1469487914035__proto__: Object
client.js:409 [telemetry] Error: certificate is not yet valid(…) undefined
client.js:407 [telemetry] sending report Objectbandwidth: Objectcontact: Contactpayment: "A6spLS42qGfgT5Ae69MaQ5UAfHAOkzdi0vp8ir62Z0mhbAgNIiErIEQesZ4lOV/UC3D7P+GsqwcBbBrNDSmzdr6OQ4u4cQn/r7iQv2Ht47gb15nMO2zUmkaPs0XebLpJVkHWV6CVsJPG48JbtqTGoLdLFGypdAugr0bSY6RCAHEY"signature: "IHEPgKfSYK5jtIAgozXmmGV6ZMAipCKSe/bSUEjr+twAA7Pm+Mmx63PWvFlMhnFdqoJVi+tyU52fDzPz2A7n5cw="storage: Objecttimestamp: 1469488213564__proto__: Object
client.js:409 [telemetry] Error: certificate is not yet valid(…) undefined
client.js:407 [telemetry] sending report Object
client.js:409 [telemetry] Error: certificate is not yet valid(…) undefined
client.js:407 [telemetry] sending report Object
client.js:409 [telemetry] Error: certificate is not yet valid(…) undefined
client.js:407 [telemetry] sending report Object

![image](https://cloud.githubusercontent.com/assets/20650196/17161160/68f0c4d2-53ab-11e6-8d52-587585b3fbcc.png)

**Comment by littleskunk** [comment]
SSL certificate was expired. Should be fixed now. If not please reopen the issue.
