### ISSUE TITLE
Feature request display percentage of used space even if the progress bar not visible

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#313]
### Versions

- **GUI Version:** v1.0.3
- **Operating System:** windows 8.1 pro

### Expected Behavior

The blue bar that is supposed to show you the percentage of used space.

### Actual Behavior

The blue bar that is supposed to show you the percentage of used space is completely absent, i only see a empty white box. It works fine on windows 10 machines.

### Steps to Reproduce

1. install and run the GUI in windows 8.1 pro

### Screenshots (Optional)

![screenshot_1](https://cloud.githubusercontent.com/assets/11735738/17172060/531741be-53eb-11e6-81eb-0c628576d45f.png)

**Comment by MeijeSibbel** [comment]
Due to the small amount of data stored relative to the total storage space the bar is so small that it's not visible. This is not a bug.

**Comment by littleskunk** [comment]
@aleitner Feature request:
Display the percentage in the middle even if the progress bar is not visible. That way the user are not confused why they don't see it.
