### ISSUE TITLE
How to break the GUI in one easy step...

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-gui#314]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** Windows 7

### Expected Behavior

Entering illegal values into fields will result in them not being accepted.
```

```

### Actual Behavior

Under Settings, Tunnel Drives, if you enter all "-1" to every field, the value will be accepted, and the GUI will be hosed:

http://puu.sh/qhWm4/fe1479fd6d.jpg

Note that restarting the GUI does NOT fix this, since the settings.json file has been updated.

Recovery if possible by manually editing the %appdata% settings.json file.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. See above.
2. ...
3. ...

### Screenshots (Optional)
http://puu.sh/qhWm4/fe1479fd6d.jpg
If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by bookchin** [comment]
We just need to perform validation on the input

**Comment by 1credit** [comment]
Totally agree.

**Comment by bookchin** [comment]
@aleitner need to cap the port nums at 65535

**Comment by 1credit** [comment]
OK, you beat me to it.  The results of using a port number like 67000 is:  http://puu.sh/qur7x/615fda5cfe.png

**Comment by 1credit** [comment]
While your coding validation things, it would be nice to validate the number of tunnel connections against the tunnel range.  It is my understanding that each connection uses a separate port, so specifying 10 connections but only 4 ports should generate a warning if non-zero port numbers are given.  Likewise specifying 3 ports but allocating a 98 port range should generate a warning.
