### ISSUE TITLE
'Used Space' goes through the 'Allocated Space' barrier

### ISSUE THREAD

**Issue by pvdl** [Storj/storjshare-gui#315]
### Versions

- **GUI Version:** v1.0.3
- **Operating System:** Linux Mint 18

### Expected Behavior

It may not occur that the Used Space exceeds the Allocate Space limit.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

If you set the Allocated Space, the Used Space doesn't respect this setting.
It exceeds this limit. 

Maybe it's worth to mention: I used the option 'Launch Storj at user login'

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Set a Allocated Space
2. Wait when the Used Space exceeds the limit

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 
![selectie_005](https://cloud.githubusercontent.com/assets/1476340/17242697/cf19ce74-5578-11e6-8cd9-97e14e7ecad5.png)

**Comment by super3** [comment]
This is been discussed in detail on https://github.com/Storj/storjshare-cli/issues/92.
Has to deal with how the OS interprets space. If it used GiB = 1024 MB or GB = 1000 MB.

**Comment by pvdl** [comment]
I'll try if your interpretation of 40x1024x1024x1024 = 42949672960 works in this case.

**Comment by pvdl** [comment]
It seems that in my case of 40 GB the Used Space stopped at 42.969 GB with 27499 contracts in total.

So we can conclude the Allocated Space mechanism works.
The Allocated Space uses GB ('1000'), and Used Space uses GiB ('1024')

If you look at the folder properties:
![selection_006](https://cloud.githubusercontent.com/assets/1476340/17343320/4fc0d5d6-58fd-11e6-9b6d-17509b3ebb8e.png)
It shows the total amount in GiB 

To make it consistent, the Allocated Space should be calculate with the factor 1024 in stead of 1000.

**Comment by pvdl** [comment]
A solution is to change this switch case:
```
            switch (tab.storage.unit) {
              case 'MB':
                totalSpace = totalSpace * Math.pow(1024, 2);
                break;
              case 'GB':
                totalSpace = totalSpace * Math.pow(1024, 3);
                break;
              case 'TB':
totalSpace = totalSpace * Math.pow(1024, 4);
```

Change '1024' to '1000'
