### ISSUE TITLE
[FEATURE] Add log message for payments received/paid out

### ISSUE THREAD

**Issue by Miskerest** [Storj/storjshare-gui#318]
### Versions

- **GUI Version:** v1.0.3
- **Operating System:** Windows 10 Insider Preview Build 14366

### Suggestion

It would be cool to see a log message that details information regarding the amount paid for a specific contract and/or amounts paid out to your payout address. Would such a feature be possible? I'd be more than willing to help in any way if I can.

**Comment by bookchin** [comment]
No, unfortunately until we get micro payments implemented this isn't feasible. Hang tight until then!
