### ISSUE TITLE
Removing a drive share incorrectly renumbers existing drives

### ISSUE THREAD

**Issue by utdrmac** [Storj/storjshare-gui#320]
### Versions

- **GUI Version:** v1.0.3
- **Operating System:** Win 7

### Expected Behavior

Drives/shares not to be renumbered

### Actual Behavior

shares are renumbered

### Steps to Reproduce

add multiple drives/shares. in my case, i had drive 0, 1, 2. I started 1 & 2. 0 was not running. in the drive menu you can see 0, 1 & 2. i deleted 0.  i expected 1 & 2 to remain. this did not happen. 1 was renamed to 0 and 2 was renamed to 1.

**Comment by littleskunk** [comment]
I did a short test myself. NodeID, storage location etc are correct. I don't see a problem with the new drive numeration. 

Only one detail could be wrong:
The new drive 0 is still writing into old drive 1 logfile. Not perfect but at the end the logfile is complete and has no missing lines. On restarting storjshare the new drive 0 will write a new logfile for drive 0. Maybe rename the logfile if that is possible but that would overwrite the old drive 0 logfile. 

Lets label this issue as discussion and see what the other devs think about it.

2 error messages on the developer console -> https://github.com/Storj/storjshare-gui/issues/322

**Comment by utdrmac** [comment]
Could we also change the way log files are rotated? Currently, log files rotate on UTC, regardless of what the local machine's TZ is. Very confusing to see todays date as 7/31/16 but the log file is 8/1/16.

**Comment by super3** [comment]
@utdrmac Please make a separate issue for that. There are over 100 open issues over the repos, so if its not in the title its going to get ignored.

**Comment by pvdl** [comment]
I did not test it, but what happens if you decrease the size of a current drive?
I should expect that also the contracts should decrease when the used space is already 100%.

**Comment by littleskunk** [comment]
@pvdl nothing will happen. The progress bar will show you max 100% and you will not get any new shards. After 90 days the first shards will expire and the used space will go down.

**Comment by bookchin** [comment]
Drives are tracked with a unique ID that is not shown to the user, so this is just a UX preference. The numbering is simply in the order of the list. 

The easiest solution here is to not use the numerical index to display, instead we can use the first few characters of the drive's ID. Both for the GUI display and the log file names.
