### ISSUE TITLE
Stop farming gracefully on removing a drive

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#322]
### Versions

Replace the values below with your own:

Storj Share 1.0.3
Core Library 2.0.7
Protocol 0.7.1

Windows 10

### Expected Behavior

Please describe the program's expected behavior.

I remove a drive while farming. I would expect a gracefull stop and remove.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Developer console print out some error messages.

One Tunnel is not open.
```
Uncaught Error: Tunnel is not open
TunnelClient.close	@	C:\Program Files (x86)\Storj Share\resources\app\node_modules\storj\lib\tunnel\client.js:107
(anonymous function)	@	C:\Program Files (x86)\Storj Share\resources\app\node_modules\storj\lib\tunnel\client.js:90
emitTwo	@	events.js:106
emit	@	events.js:191
cleanupWebsocketResources	@	C:\Program Files (x86)\Storj Share\resources\app\node_modules\ws\lib\WebSocket.js:950
emitNone	@	events.js:91
emit	@	events.js:185
endReadableNT	@	_stream_readable.js:926
_combinedTickCallback	@	internal/process/next_tick.js:74
_tickCallback	@	internal/process/next_tick.js:98
```

multiple times Uncaught Error: connect ECONNREFUSED 127.0.0.1:50776
```
Uncaught Error: connect ECONNREFUSED 127.0.0.1:50776
exports._errnoException	@	util.js:949
exports._exceptionWithHostPort	@	util.js:972
afterConnect	@	net.js:1080
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start Storjshare-gui and farm with 2 drives.
2. Remove one drive while it is running.
3. Wait a few minutes and watch for error messages on the developer console

**Comment by bookchin** [comment]
We need to ensure that `FarmerInterface#leave` gets called on remove.
