### ISSUE TITLE
No cancel / disagree on license accept; continues to run

### ISSUE THREAD

**Issue by utdrmac** [Storj/storjshare-gui#323]
On first start of the GUI, the license agreement is presented. There is no option for 'No' / 'Cancel' / 'Disagree'. If you simply close the window, storj continues to run in the background.

**Comment by bookchin** [comment]
I assume you are running OSX? The close button on  (like many other applications on OSX) simply hides the window. You have to quit the application from the menu to stop it, otherwise it will sit and wait for you to accept.

**Comment by bookchin** [comment]
Going to close this, but if I misunderstood the issue, let me know and I will reopen.

**Comment by utdrmac** [comment]
@bookchin Please re-open. This was on Ubuntu. If you click the "close window" button, and you have not accepted the license, the entire prog should quit. Should be similar behavior for all OSes.

**Comment by utdrmac** [comment]
Just tested this on OSX. You are correct that simply closing the window the app remains running. But that's pretty odd/weird/unusual for apps to do when not accepting the UL

**Comment by bookchin** [comment]
Do you have the minimize to tray option enabled?

**Comment by utdrmac** [comment]
This was a fresh, never-had-it-running on Mac before type scenario. I downloaded the DMG, copied the binary, ran it, did not accept the ULA and clicked the red close button. Icon stayed in dock.
