### ISSUE TITLE
Feature request:  "last mutation: x seconds"

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#326]
How about adding a "last mutation: x seconds" info filed/box to the GUI ?, sometimes the GUI doesn't start correctly or stops working after a while, a last mutation tab will help to show the user he or she is actually downloading/uploading shards.
With only a few shards you can just follow the shard count, but with 20k+ shards, remembering the previous number of total shards for a certain time interval does not work, which can lead to a storj instance that is running for a long time without actually working. This is happening to me allot, with things like internet dropouts and hardware glitches... With a countdown timer between the last downloaded/uploaded shard the user can clearly see the storj instance is working. By giving the filed/box a color( green - red ) the user can monitor the "health" of the storj instance.

**Comment by bookchin** [comment]
I like this idea, it will require this: https://github.com/Storj/core/issues/306

**Comment by bookchin** [comment]
@boshevski we have added the required event hooks into core to get this information for display, but would rather you determine how best to convey the information to the user. have some time to think about it and let us know?

**Comment by super3** [comment]
@bookchin @boshevski Btw, is currently traveling.

**Comment by super3** [comment]
Believe @boshevski is working on this.

**Comment by super3** [comment]
Correction. @boshevski is done, and has passed to @aleitner
