### ISSUE TITLE
OSX Instance Fails to restart without rebooting computer

### ISSUE THREAD

**Issue by digidan** [Storj/storjshare-gui#328]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** OSX 10.11.5 El Capitan

### Expected Behavior

After the program crashes or locks up or stops responding I should be able to end the process, or close the program and have it restart and be functional again.  

```

```

### Actual Behavior

The app restarts.  The first thing I notice is that the Used Space doesn't refresh and shows 0GB.  Peers may connect but no changes are shown in successful contracts or used space continues to show 0.  Eventually the storj share is running green button becomes unresponsive and the program must be killed.  Upon restart it seems the storj helper terminal app does not restart appropriately causing it to not start working again until reboot.  Even upon reboot (it starts automatically with machine) the first message is that a connection cannot be found.  The program must then be manually stopped and started again to work appropriately.  

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... Storj share either whitescreens or gives a drive error
2. ...close storj share and try to restart
3. ...restarts but does not show used space and peers connect but no contracts or space used changes.  
4..... eventually program freezes
5......repeat with same results over and over again until reboot to fix

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by bookchin** [comment]
This is related to #317 and will get resolved with #259 and https://github.com/Storj/core/issues/143
