### ISSUE TITLE
setting.json file corrupted

### ISSUE THREAD

**Issue by jackyq2015** [Storj/storjshare-gui#329]
After I reboot my pc, the setting.json file was corrupted and the file size is 0. I have 3 drive shared and is there any way I can generate this file from the farmer.db dirs?

The GUI can not start now giving error "unexpected end of json file".

Seems this file is getting refresh once a while to carry other info such as number of contract etc. I think it make more sense to leave this critical file untouched in case something happens.

**Comment by jackyq2015** [comment]
Just an update for this issue: I created the setting manually and filled in the old address and farm.db location. Now one of my 1G farm is recovered after 4 hours shard counting(meanwhile the GUI prompt "Counting Shards. This only happens once. This may take a moment, so grab a cocktail!" message).

Right now, I am recovering the 2nd drive whose usage is 2G. It already took 12 hours and still not finish. I checked the process and it seems it was not even reading the farmer.db file. I am not sure if it's hang or just slow. My assumption is reading the local db should be fast even it's not native call. 

The version information:
Storj Share 1.0.3
Core Library 2.0.7
Protocol 0.7.1
Windows 10.

**Comment by jackyq2015** [comment]
Finally, I stopped "counting shards" and fixed it manually. Here is the steps:
1. Install SqliteBrowser
2. open the C:\Users\[user]\AppData\Roaming\Storj Share\Local Storage\file__0.localstorage
3. Navigate the table and find the record key like: contractCount_4965e2d3ca37b259415adf499eb06da7c35541fe
4. Copy the 4965e2d3ca37b259415adf499eb06da7c35541fe, that's the id you should set for the setting.json file
If you have multiple drive, do the same. the order of the record is  sorted by creation time. Do not mess up with the drive.

Sometimes the leveldb is corrupted also. You need aptly from https://www.aptly.info/. In my case, it fixed one but failed to fix a 5G DB.

It's painful experience but hopefully you never have this issue and have fun.

**Comment by brad-pea** [comment]
Hi Jackyq2015 

So when you find out the ID using SqliteBrowser ... Where do you input that within the setting.json file ? Which entry does it override ? 

Thanks.

**Comment by brad-pea** [comment]
Ok I checked out my settings.json file and it already has the correct ID's in as per the file__0.localstorage .. therefore I dont think this will fix my issue #333 

Thanks.

**Comment by jackyq2015** [comment]
@brad-pea seems your leveldb is corrupted. You can try the utility I mentioned in #333. But as I said, it's no guarantee that can be fixed properly. I fixed one but another failed

**Comment by aleitner** [comment]
Closed with the release of 4.0.0. This issue should be eliminated with the latest kfs
