### ISSUE TITLE
Power Saver Settings for monitors in OSX cause WSOD

### ISSUE THREAD

**Issue by digidan** [Storj/storjshare-gui#331]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** OSX El Capitan 10.11.5

### Expected Behavior

Please describe the program's expected behavior
Expected behavior would be that the app works when going into power saving mode for monitors (not sleep mode).  

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

monitors turn off and about 90% of the time this disables the storj app with WSOD or io error with usb drive.  When power saver is engaged for monitors white screen of death will cause storj to become unresponsive even after restarting the app.  this tends to be white screen of death.  I have not experienced WSOD since disabling this feature but it instantly returned when turning back on power saver settings.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... time reached for monitors to power down
2. ... try to get monitors to turn back on by clicking or hitting keyboard
3. ... storj is either WSOD or io error showing in logs
app won't restart functionally without rebooting computer 

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/317
