### ISSUE TITLE
Payout address validation

### ISSUE THREAD

**Issue by frdwrd** [Storj/storjshare-gui#332]
The payout address field should only accept valid bitcoin addresses. 

* valid address prefix (1 or 3)
* only uses acceptable characters ([Base58Check encoding](https://en.bitcoin.it/wiki/Base58Check_encoding))
* 26 - 35 characters long
* [valid checksum](https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses)

At least 50 people have put in invalid information, some of which has been sensitive.

**Comment by bookchin** [comment]
We can just use `storj.deps.bitcore.Address.validate()`, will include in this week's release.

**Comment by frdwrd** [comment]
How easy is it to also validate in the CLI?

**Comment by bookchin** [comment]
Same.

**Comment by frdwrd** [comment]
Great. I'll open an issue there too.
