### ISSUE TITLE
GUI Still Counting Shards After 12+ Hours

### ISSUE THREAD

**Issue by brad-pea** [Storj/storjshare-gui#333]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** Windows 7 64 Bit

### Expected Behavior

Gui should open, count shards after X amount of time and then be able to farm ...

### Actual Behavior

Gui is opening, counting shards from 3 "drives" but still counting after 12+ hours ...

The way I have it set up is one folder, and then a folder each within then for each drive ... so Folder - Gui1, Gui2, Gui3

### Steps to Reproduce

Set up as above

### Screenshots (Optional)

Just showing counting shards, if needed i can supply.

**Comment by jackyq2015** [comment]
I created a similar issue #329 

A temporary solution was provided

**Comment by MeijeSibbel** [comment]
Same issue here, has been counting for 6 days non-stop until the white screen appears again. Then i restart everything and it starts counting again non-stop.

**Comment by MeijeSibbel** [comment]
What i noticed is that while the counting is going on, new shards are downloaded during the counting. If i would to guess i think that every shard that is downloaded during the counting causes the counting process to be restarted. I tested this out by cutting of my internet connection during the counting, and it worked!. now my GUI runs smoothly without the infinite counting loop.
