### ISSUE TITLE
Unable to disable tunnels

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-gui#338]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.5
- **Operating System:** Windows 7

### Expected Behavior

Specification of -1 to disable tunnels is now being reset to 0.  Previously, 0 meant "Default" and actually allowed 3 tunnel connections.  If 0 really means 0 this is fine, but is inconsistent with the use of 0 elsewhere to mean "default" (a bad shortcut in the first place).

```

```

<see above>

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
That issue was fixed with one of the last core releases. 0 will now disable tunnel connections.
```
{"level":"info","message":"you are configured to tunnel up to 0 connections","timestamp":"2016-08-10T01:07:15.173Z"}
```
