### ISSUE TITLE
GUI Displaying ZERO balance in funded SJCX address

### ISSUE THREAD

**Issue by JeremyPepper2** [Storj/storjshare-gui#343]
### Versions

- **GUI Version:** v1.0.6
- **Operating System:** OS X 10.11.6

### Expected Behavior

Displays the balance in a valid Counterwallet address

### Actual Behavior

A zero balance is displayed in the GUI window for an account with over 10,300 SJCX...

### Steps to Reproduce

1. Open app
2. Read zero balance...

### Screenshots (Optional)

![screen shot 2016-08-16 at 11 58 54 pm](https://cloud.githubusercontent.com/assets/11845884/17724129/81300cfc-640d-11e6-9f18-7b3a37692434.png)

![screen shot 2016-08-17 at 12 00 06 am](https://cloud.githubusercontent.com/assets/11845884/17724149/99ec0cbe-640d-11e6-855c-72b87292e079.png)

**Comment by super3** [comment]
@JeremyPepper2 We get that data from the [https://counterpartychain.io/api]( https://counterpartychain.io/api). Going to follow up with the owner to see if there is an issue there.

**Comment by keeper151515** [comment]
I am also getting the same issue... I did notice that it sometimes does appear after while or stoping and starting the service sometimes works. Very sporadic
