### ISSUE TITLE
storj-share is reading my whole c: drive

### ISSUE THREAD

**Issue by jackyq2015** [Storj/storjshare-gui#346]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.6
- **Operating System:** windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
it should only read/write the folder I specified for storage
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
it read all the files under c:\. It happened before. It brought to my notice that it was reading my system file also.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)
![storj-read-root](https://cloud.githubusercontent.com/assets/10520203/17753739/2f5dc2ec-649f-11e6-920a-ff5cc44739ce.png)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by bookchin** [comment]
This is probably from the calculation of free disk space. Storj Share will only write to the directory specified.

**Comment by jackyq2015** [comment]
I don't think calculating the free space need to go though each every files.

The [source code](https://github.com/SuperPaintman/fd-diskspace/blob/b49bee82e3432e8bd53850a2f879e5196d6835af/bin/index.js from fd-diskspace shows it call the following utility under windows:
``
'wmic logicaldisk get size,freespace,caption
``
