### ISSUE TITLE
IO error under windows

### ISSUE THREAD

**Issue by jhiswin** [Storj/storjshare-gui#347]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.6
- **Operating System:** Windows Server 2008 R2

### Expected Behavior

Getting this in the log file:
IO error: G:\storj\farmer.db/173921.ldb

Also this in the "LOG" file:
Compaction error: IO error: G:\storj\farmer.db/173825.ldb

**Comment by jackyq2015** [comment]
The slash may not be the issue.  it should be converted automatically. could be the physical storage issue(unattached?)

**Comment by super3** [comment]
Not enough info here.

**Comment by initjh** [comment]
The physical storage is internal storage 2x SATA RAID.
Maybe it's an issue with LevelDB?

**Comment by jhiswin** [comment]
The storage is 2x internal SATA drives in a RAID config.
I've also noticed that although space is being used, I'm no longer getting any successful contracts.  Seems to be the same time that this error starting popping up (could also just be coincidence).
@super3 what other info can I provide to help?

**Comment by bookchin** [comment]
Once the GUI 2 release is published today, you can try to use the new repair database feature to try and recover from what appears to be a corruption of your database. 

This can happen if you quit the program or it crashes during a compaction.
