### ISSUE TITLE
UDP Traffic???

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-gui#352]
### Versions

Replace the values below with your own:

- **GUI Version:**  2.0.3
- **Operating System:** Windows 10 (unfortunately)

### Expected Behavior

Only documented TCP/IP traffic will occur via the program.
```

```

### Actual Behavior

Seeing many UDP ports being listened on.

http://puu.sh/qHLmx/af8b8c0b5b.png

Fixed port numbers are specified in each of the 8 drives allocated.  Network Traversal in ENABLED in order to deal with changing DHCP provided addresses after site power outages. 
```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Crank up GUI
2. Open Windows Task Manager -> Resource Monitor
3. View Network Listening Ports

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
These ports are opened by electron itself: https://github.com/electron/electron/issues/5014

**Comment by 1credit** [comment]
That may be the reason, but it is NOT an explanation.  Why would a GUI interface need to open dozens of UDP ports?

http://puu.sh/qI6hI/63c69c3ab6.png

And what is it doing with those ports?  HUGE security concern here.

**Comment by littleskunk** [comment]
Ok I will reopen and try to find some informations about this.

**Comment by computeronix** [comment]
same thing on mac

[4:09]  
Storj\x20 752 i3user   32u  IPv6 0xd33e87aa99850043      0t0  UDP [fdb2:2c26:f4e4::21c:42ff:fe84:3e54]:53383
Storj\x20 752 i3user   33u  IPv4 0xd33e87aa99c8abcb      0t0  TCP *:49327 (LISTEN)
Storj\x20 752 i3user   34u  IPv6 0xd33e87aa9e8480fb      0t0  UDP [fdb2:2c26:f4e4::d433:7028:ab17:f9fd]:53384
Storj\x20 752 i3user   35u  IPv4 0xd33e87aa9e847c2b      0t0  UDP os-x-10.11.6.shared:54403
Storj\x20 752 i3user   36u  IPv6 0xd33e87aa9e8491d3      0t0  UDP [fdb2:2c26:f4e4::21c:42ff:fe84:3e54]:54404
Storj\x20 752 i3user   37u  IPv6 0xd33e87aa9984f90b      0t0  UDP [fdb2:2c26:f4e4::d433:7028:ab17:f9fd]:54405
Storj\x20 752 i3user   38u  IPv4 0xd33e87aa998502ab      0t0  UDP os-x-10.11.6.shared:57343
Storj\x20 752 i3user   40u  IPv6 0xd33e87aa9c15186b      0t0  TCP *:49334 (LISTEN)

[4:10]  
interesting note when you stop running storjshare  on windows the connections stop // on mac the connections stay open until program is closed

[4:11]  
this is the view after it is stopped; no more TCP but UDP still established

[4:11]  
Storj\x20 752 i3user   32u  IPv6 0xd33e87aa99850043      0t0  UDP [fdb2:2c26:f4e4::21c:42ff:fe84:3e54]:53383
Storj\x20 752 i3user   34u  IPv6 0xd33e87aa9e8480fb      0t0  UDP [fdb2:2c26:f4e4::d433:7028:ab17:f9fd]:53384
Storj\x20 752 i3user   35u  IPv4 0xd33e87aa9e847c2b      0t0  UDP os-x-10.11.6.shared:54403
Storj\x20 752 i3user   36u  IPv6 0xd33e87aa9e8491d3      0t0  UDP [fdb2:2c26:f4e4::21c:42ff:fe84:3e54]:54404
Storj\x20 752 i3user   37u  IPv6 0xd33e87aa9984f90b      0t0  UDP [fdb2:2c26:f4e4::d433:7028:ab17:f9fd]:54405
Storj\x20 752 i3user   38u  IPv4 0xd33e87aa998502ab      0t0  UDP os-x-10.11.6.shared:57343

[4:14]  
fyi this is the command i ran for those that want to test on mac (well unix lol)

[4:14]  
lsof -i | grep Storj

**Comment by computeronix** [comment]
Here is a test powershell for the windows side

[Get-NetworkStats-StorjShare.ps1.zip](https://github.com/Storj/storjshare-gui/files/428489/Get-NetworkStats-StorjShare.ps1.zip)

**Comment by computeronix** [comment]
UDP exists in Ubuntu as well

storjshar 2814 parallels   42u  IPv6  16473      0t0  TCP *:57465 (LISTEN)
storjshar 2814 parallels   45u  IPv4  18989      0t0  TCP ubuntu-linux-14.04-desktop.shared:44075->a80-101-109-52.adsl.xs4all.nl:4001 (ESTABLISHED)
storjshar 2814 parallels   50u  IPv4  16449      0t0  TCP *:58725 (LISTEN)
storjshar 2814 parallels   52u  IPv4  17161      0t0  TCP ubuntu-linux-14.04-desktop.shared:37374->a80-101-109-52.adsl.xs4all.nl:4000 (ESTABLISHED)
storjshar 2814 parallels   53u  IPv4  16462      0t0  UDP ubuntu-linux-14.04-desktop.shared:43929 
storjshar 2814 parallels   56u  IPv4  15643      0t0  UDP ubuntu-linux-14.04-desktop.shared:52742 
storjshar 2814 parallels   57u  IPv4  15627      0t0  UDP ubuntu-linux-14.04-desktop.shared:54714 
storjshar 2814 parallels   58u  IPv6  15628      0t0  UDP [fdb2:2c26:f4e4:0:3ddf:b569:c055:5d83]:37503 
storjshar 2814 parallels   59u  IPv6  15629      0t0  UDP [fdb2:2c26:f4e4:0:21c:42ff:fe02:1bf9]:35971 
storjshar 2814 parallels   60u  IPv6  15644      0t0  UDP [fdb2:2c26:f4e4:0:3ddf:b569:c055:5d83]:60341 
storjshar 2814 parallels   61u  IPv6  15645      0t0  UDP [fdb2:2c26:f4e4:0:21c:42ff:fe02:1bf9]:52705 
storjshar 2814 parallels   62u  IPv4  16453      0t0  UDP ubuntu-linux-14.04-desktop.shared:33863 
storjshar 2814 parallels   66u  IPv6  16454      0t0  UDP [fdb2:2c26:f4e4:0:3ddf:b569:c055:5d83]:55953 
storjshar 2814 parallels   67u  IPv6  16455      0t0  UDP [fdb2:2c26:f4e4:0:21c:42ff:fe02:1bf9]:38250 
storjshar 2814 parallels   68u  IPv6  16463      0t0  UDP [fdb2:2c26:f4e4:0:3ddf:b569:c055:5d83]:44126 
storjshar 2814 parallels   69u  IPv6  16464      0t0  UDP [fdb2:2c26:f4e4:0:21c:42ff:fe02:1bf9]:48592 
storjshar 2814 parallels   70u  IPv4  21392      0t0  TCP ubuntu-linux-14.04-desktop.shared:37386->a80-101-109-52.adsl.xs4all.nl:4000 (ESTABLISHED)
storjshar 2814 parallels   71u  IPv4  17189      0t0  TCP ubuntu-linux-14.04-desktop.shared:37376->a80-101-109-52.adsl.xs4all.nl:4000 (ESTABLISHED)
storjshar 2814 parallels   72u  IPv4  21245      0t0  TCP ubuntu-linux-14.04-desktop.shared:37378->a80-101-109-52.adsl.xs4all.nl:4000 (ESTABLISHED)
storjshar 2814 parallels   73u  IPv4  21255      0t0  TCP ubuntu-linux-14.04-desktop.shared:57573->host105.71.237.80.pppoe.alfatelplus.ru:6328 (ESTABLISHED)
storjshar 2814 parallels   79u  IPv4  21268      0t0  TCP ubuntu-linux-14.04-desktop.shared:57575->host105.71.237.80.pppoe.alfatelplus.ru:6328 (ESTABLISHED)
storjshar 2814 parallels   80u  IPv4  21320      0t0  TCP ubuntu-linux-14.04-desktop.shared:37384->a80-101-109-52.adsl.xs4all.nl:4000 (ESTABLISHED)

Command for Ubuntu

lsof -i | grep storjshar
