### ISSUE TITLE
Windows Firewall Rule adds TCP and UDP Exceptions

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#354]
### Versions

- **GUI Version:** v2.0.3
- **Operating System:** Windows 10

### Expected Behavior

```
Does GUI need both TCP and UDP port exceptions?
```

### Actual Behavior

```
When accepting the firewall rule changes it adds TCP and UDP exceptions
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install GUI
2. Run GUI
3. Start GUI
4. Say Yes to adding the firewall rule exceptions

### Screenshots (Optional)

<img width="958" alt="screen shot 2016-08-20 at 2 14 51 pm" src="https://cloud.githubusercontent.com/assets/19168174/17833004/7b954430-66e0-11e6-909c-a6eb96a6cd8c.png">

**Comment by bookchin** [comment]
Yeah the electron framework opens UDP ports for local IPC.
