### ISSUE TITLE
Mac Unidentified Developer

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#355]
### Versions

Replace the values below with your own:
- **GUI Version:** v2.0.3
- **Operating System:** Max OS X 10.11
### Expected Behavior

```
Application needs to be signed by code signing certificate
```
### Actual Behavior

```
Open application and receive the below screenshot

Workaround is to turn off Application Signing Review in Security
```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. Install app
2. Attempt to run it
### Screenshots (Optional)

![screen shot 2016-08-20 at 3 55 11 pm](https://cloud.githubusercontent.com/assets/19168174/17833551/a813447c-66ee-11e6-843b-c843fd129515.png)

**Comment by littleskunk** [comment]
https://github.com/Storj/storjshare-gui/issues/36

**Comment by super3** [comment]
@littleskunk [Electron - Signing a Mac Application](https://pracucci.com/atom-electron-signing-mac-app.html). Ready to go though this process again for Mac?

**Comment by super3** [comment]
Following [this guide](http://blog.metamorphium.com/2012/12/03/apple-duns/). Just applied for a number, and will wait for them to follow up.

**Comment by super3** [comment]
"Thank you for submitting your D-U-N-S Number request / update to D&B. It should be completed by 09/07/2016, or sooner." Its going to take a while.

**Comment by super3** [comment]
Ok I have the DUNS number. I am currently setting up the developer account for Apple. They have to verify me so it might take a few more days.

**Comment by bookchin** [comment]
:apple: === :poop:

**Comment by super3** [comment]
@bookchin Shhhh or they will remove all your 3.5mm jacks.

**Comment by super3** [comment]
@littleskunk "Your enrollment is being processed." Still waiting.

**Comment by super3** [comment]
Looks like this is not happening. I called Apple, and they said they would not process our application. They gave no info as to why.
