### ISSUE TITLE
Mac Storj GUI shows needs updated even though updated

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#356]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.3
- **Operating System:** Mac OS X 10.11

### Expected Behavior

Please describe the program's expected behavior.

```
Open program and only asks you to upgrade when needed
```

### Actual Behavior

```
Even though 2.0.3 is installed, it asks to upgrade
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install APP
2. Launch it

### Screenshots (Optional)

![screen shot 2016-08-20 at 3 59 52 pm](https://cloud.githubusercontent.com/assets/19168174/17833872/1858cc94-66f8-11e6-8583-a1b9d5fb6e6c.png)

**Comment by littleskunk** [comment]
Wrong screenshot?

**Comment by computeronix** [comment]
Fixed 🎯

**Comment by aleitner** [comment]
I just downloaded from the releases and I'm not receiving this. Can you confirm that you downloaded from the correct release?

**Comment by computeronix** [comment]
Looks good, re-downloaded it and deleted all my local preference files and everything and when installing the new one it is actually the 2.0.3 and looks great!
