### ISSUE TITLE
Mac GUI No Option to create save directory

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#357]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.3
- **Operating System:** Mac OS X 10.11

### Expected Behavior

Please describe the program's expected behavior.

```
Have an option to create a new folder for the save directory
```

### Actual Behavior

```
Must create the folder outside the app then select it within the app
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install APP / Run it
2. Save Directory -> you can only select no option to right click or even create a folder (not sure if this is OS X limitation or app)

**Comment by fletchertyler914** [comment]
I was going to create a pull request for this but it seems that there is an issue with Electron's showOpenDialog function. While adding the 'createDirectory' property to the showOpenDialog function works in adding a "New Folder" button, it overlays a "Hide Extensions" checkbox and the opacity of the "New Folder" button allows you to see the "Hide Extensions" checkbox underneath. 

I'm not experienced in Electron so I cant figure out how to modify the layout or CSS for the Electron Dialog as of yet.
