### ISSUE TITLE
Mac GUI Errors out Protocol version is incompatible and UPNP errors

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#358]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.3
- **Operating System:** Mac OS X 10.11

### Expected Behavior

Please describe the program's expected behavior.

```
Start sharing and it should work
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Start sharing an program errors with

{error} [Sat Aug 20 2016 16:17:26 GMT-0400 (EDT)] Protocol version is incompatible (left and right even though peers are up to date)

Also UPNP errors (even though open on Mac)

{warn} [Sat Aug 20 2016 16:17:25 GMT-0400 (EDT)] could not connect to NAT device via UPnP: 49493
{warn} [Sat Aug 20 2016 16:17:25 GMT-0400 (EDT)] failed to map port for tunserver: Request failed: 500
{warn} [Sat Aug 20 2016 16:17:25 GMT-0400 (EDT)] could not connect to NAT device via UPnP: 27048

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install on Mac
2. Run it

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by aleitner** [comment]
Is this still an issue with the most recently downloaded storjshare-gui?

**Comment by computeronix** [comment]
This looks good now too!!

Easy fixes!
