### ISSUE TITLE
Execution blocked by Windows 10 SmartScreen

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#36]
I tryed DriveShare_0.3.0.exe. Windows 10 SmartScreen blocked it. Publisher information is missing. Thats why SmartScreen blocks it.

**Comment by gamedevsam** [comment]
Can you provide some information on how I can add that metadata?

**Comment by littleskunk** [comment]
http://blogs.msdn.com/b/smondal/archive/2013/01/08/windows-smartscreen-prevented-an-unrecognized-app-from-running-running-this-app-might-put-your-pc-at-risk.aspx

**Comment by gordonwritescode** [comment]
Hey @littleskunk. I don't think this can be resolved through a code change (or the bundler scripts either). 

I'm almost certian that this is going to have to be done as part of the release scripts/process you are putting together.

Here is an article that seems to thoroughly outline the process: https://msdn.microsoft.com/en-us/library/windows/desktop/jj835835%28v=vs.85%29.aspx

**Comment by gordonwritescode** [comment]
Just saw this link, section 2 talk about how to correctly sign the build for Windows!
https://nulab-inc.com/blog/typetalk/3-necessary-things-to-correctly-release-a-product-based-on-the-electron-app/ @littleskunk

**Comment by littleskunk** [comment]
We need a code signing certificate. I found this
http://blog.aluxian.com/free-code-signing-certificate-for-open-source-software/

@super3 Can you sign up and get a certificate for farmer-gui?

**Comment by super3** [comment]
It's no longer free, but only about 14 euros. Once we are closer to a production release (and not shipping everyday), I can buy it for us. Just ping me again when you think it is time.

**Comment by super3** [comment]
@littleskunk Just bought the cert. Now we wait for verification and the keys. Will assign to myself for now as I get them together.

**Comment by bookchin** [comment]
@super3 any movement on this?

**Comment by bookchin** [comment]
We'll need to automate the release signing for this too, which may require some infrastructure setup. @phutchins

**Comment by littleskunk** [comment]
I can automate binary signing on my build server. At the moment we don't need additional infrastructure for it. I am waiting for the certificate.

**Comment by bookchin** [comment]
@littleskunk good news!

**Comment by super3** [comment]
Cert place wants me to send over my ID via plaintext. Its been in my queue, while I try to think of a work around. Might just do it to get it done.

**Comment by super3** [comment]
We now have a cert.

**Comment by littleskunk** [comment]
@super3 I need a .pfx certificate file. I can download the .cer file. It looks like I need the private key used to generate the certificate. I have to install the private key and the .cer file to get a .pfx certificate file.

**Comment by super3** [comment]
Ok working through it. I somehow don't have the .pfx, and I think I need to regenerate it, and in IE because it doesn't work in Firefox or Chrome....

**Comment by super3** [comment]
Sent them an email to fix.
1) Will wait until we get a response. 
2) @littleskunk You can generate a cert, and we will reimburse. 

Shawn

**Comment by super3** [comment]
Contacting the certificate authority, and waiting to hear back. @littleskunk You should still try to register your own certificate. I can also look for another less terrible provider.

**Comment by super3** [comment]
Certum was being annoying. Just ordered a cert at another authority: 

- https://mkaz.tech/code-signing-a-windows-application.html
- https://msdn.microsoft.com/en-us/library/windows/hardware/hh801887%28v=vs.85%29.aspx

Will provide an update when the order processes.

**Comment by super3** [comment]
@littleskunk I have a new cert that I have passed to you.

**Comment by littleskunk** [comment]
The new certificate looks good. I signed the first binary with it.

Now I have to include it into the build process.

**Comment by super3** [comment]
@littleskunk Awesome!

**Comment by littleskunk** [comment]
Binary signed but the signature is not valid. I don't understand what's wrong.

My command for signing the binary: `signtool.exe sign /fd sha256 /td sha256 /tr http://timestamp.digicert.com /f %Cert_File% /p %Cert_Password% *.exe`

On verify I get this error message:
```
C:\Users\Skunk\Downloads>signtool verify storjshare-gui.win32.exe
File: storjshare-gui.win32.exe
Index  Algorithm  Timestamp
========================================
SignTool Error: A certificate chain processed, but terminated in a root
        certificate which is not trusted by the trust provider.

Number of errors: 1
```

The signature looks correct.
![signature](https://cloud.githubusercontent.com/assets/6333390/17295592/27e965ce-57fd-11e6-8bc4-5e55e33ef76b.jpg)


Am I blind? It looks like the correct root certificate. Even the root certificate ID is correct and listed as trusted certificate. What is the problem? Why is smartscreen still blocking it?

**Comment by super3** [comment]
```Even after signing your app properly, there is an extra step of protection called the SmartScreen which can display during installation. It is my understanding that this is displayed based on the reputation of your certificate. So as more valid installs occur, it will go away and not display to users.

In an attempt to improve our reputation, I saw one recommendation to Microsoft's Hardware Dev Center which has a file signing section. I registered our company and walked through uploading a signed sample app. I'm not sure if this helps or not, but I figured it couldn't hurt and might improve our certificate's reputation.```

https://mkaz.tech/code-signing-a-windows-application.html

**Comment by super3** [comment]
But that doesn't seem to be the issue. Let me contact the certificate authority.

**Comment by littleskunk** [comment]
Looks like everything is ok and we only have to wait for a better smartscreen reputation.
```
C:\Users\Skunk\Downloads>signtool.exe verify /pa /v "storjshare-gui.win32(18).exe"

Verifying: storjshare-gui.win32(18).exe
Signature Index: 0 (Primary Signature)
Hash of file (sha256): 7304D63C29A544CF5D15E3A285DD96AAB73F7546E58A2B81F11A54E09B22153A

Signing Certificate Chain:
    Issued to: DigiCert Assured ID Root CA
    Issued by: DigiCert Assured ID Root CA
    Expires:   Mon Nov 10 02:00:00 2031
    SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43

        Issued to: DigiCert SHA2 Assured ID Code Signing CA
        Issued by: DigiCert Assured ID Root CA
        Expires:   Sun Oct 22 14:00:00 2028
        SHA1 hash: 92C1588E85AF2201CE7915E8538B492F605B80C6

            Issued to: Storj Labs Inc.
            Issued by: DigiCert SHA2 Assured ID Code Signing CA
            Expires:   Wed Jul 26 14:00:00 2017
            SHA1 hash: BF3D83E5F9B09C15BAB0061A2CF06CA781481456

The signature is timestamped: Fri Jul 29 14:24:13 2016
Timestamp Verified by:
    Issued to: DigiCert Assured ID Root CA
    Issued by: DigiCert Assured ID Root CA
    Expires:   Mon Nov 10 02:00:00 2031
    SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43

        Issued to: DigiCert SHA2 Assured ID Timestamping CA
        Issued by: DigiCert Assured ID Root CA
        Expires:   Tue Jan 07 14:00:00 2031
        SHA1 hash: 3BA63A6E4841355772DEBEF9CDCF4D5AF353A297

            Issued to: DigiCert SHA2 Timestamp Responder
            Issued by: DigiCert SHA2 Assured ID Timestamping CA
            Expires:   Tue Jan 07 02:00:00 2025
            SHA1 hash: C636F4DDA87CEE3D8263BF9A2514B4533468D75E


Successfully verified: storjshare-gui.win32(18).exe

Number of files successfully Verified: 1
Number of warnings: 0
Number of errors: 0
```

**Comment by computeronix** [comment]
Install the code signing certificate "xxx name of Storj Code Sign Cert" into your Keychain (Double click the pfx file, enter encrypted password, store it)
Open Terminal
sudo codesign --force --sign "name of Storj Code Sign Cert" "/path to app/Storj Share.app"

**Comment by computeronix** [comment]
FYI i should note while the above works; its not apple approved

Shawn's link follows the apple approved method: https://pracucci.com/atom-electron-signing-mac-app.html

Requires Apple Company Developer Account (https://developer.apple.com)
