### ISSUE TITLE
WSoD of GUI during initialisation

### ISSUE THREAD

**Issue by lfintor** [Storj/storjshare-gui#360]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.3
- **Operating System:** Windows 10 64bit

### Expected Behaviour

Upon starting a drive the amber rectangle changes to green, starts accepting contracts etc

### Actual Behaviour

For small drives (i.e. less than 10000 shards) client is going through an initialisation which drives the hard drive at 100%, the length of this is proportional to the size of the farmer.db folder.

NB, this is only o

For large (over 100K shards) directories the initialisation phase takes quite long (i.e. longer than 5 minutes on a fast, non-SSD HDD) and never completes, the client crashes. When reloading all the previous info read from the hard drive is already cached and the crash happens almost instantly after the reload.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. pick a large drive
2. start client
3. wait for it to crash

### Screenshots (Optional)

Here is a large-ish drive right after the start button was pressed.

![image](https://cloud.githubusercontent.com/assets/8819770/17871928/c8ec0f8a-68b5-11e6-85eb-706f64565dbf.png)

![image](https://cloud.githubusercontent.com/assets/8819770/17871911/b0d107b6-68b5-11e6-870c-5cf8dbed0294.png)

after about 3 minutes of churning the drive:

![image](https://cloud.githubusercontent.com/assets/8819770/17872084/5d64f9b0-68b6-11e6-865b-f24e1e72a413.png)

and 

![image](https://cloud.githubusercontent.com/assets/8819770/17872092/655c201c-68b6-11e6-9f04-9602e73bb5bd.png)

**Comment by matanbr** [comment]
I am getting also the white screen about 4 times a day in the last version 
No Logging
Windows 10 64bit

**Comment by littleskunk** [comment]
On windows we are using flatten-packages for the binaries. This can have side effects. Please try this workaround on windows:

```
git clone https://github.com/Storj/storjshare-gui -b v2.0.3
cd storjshare-gui
npm install
npm start
```

This will start storjshare-gui without flatten-packages. Leave me a comment if that works.

**Comment by littleskunk** [comment]
I removed flatten-packages. Please try again with the new gui release.

**Comment by lfintor** [comment]
Same behaviour.

**Comment by matanbr** [comment]
So far in 24 hours I had only 1 crash (2.0.5) , wich is much better than the last version , in 2.0.3 I had around 5 crashes per day

**Comment by matanbr** [comment]
OK little update , in the last 24 hours it did crash couple of time.
each time I need to restart it a couple of times in order to start getting shards again.
also started to get this error message sometimes when it crashing
![default](https://cloud.githubusercontent.com/assets/9035057/18200246/8caa361e-710c-11e6-9870-545468e43a76.png)

**Comment by MeijeSibbel** [comment]
I am getting the same error as matanbr when i press the 'start' button.

![2016-09-05_720](https://cloud.githubusercontent.com/assets/11735738/18249015/08c87eba-737c-11e6-8746-7bd7fa1ec4c2.png)

**Comment by lfintor** [comment]
Issue is the same (i.e. cannot start up large drives) on 2.0.6 as well. Also having intermittent crashes after 4-6 hours of operations.

**Comment by littleskunk** [comment]
I created 2 memory snapshots with visual studio and compared them. The memory is used for char[] somewhere in leveldown.

```
 	leveldown.node!operator new() - Zeile 19	C++
 	leveldown.node!leveldb::ReadBlock() - Zeile 77	C++
 	leveldown.node!leveldb::Table::ReadFilter() - Zeile 134	C++
 	leveldown.node!leveldb::Table::ReadMeta() - Zeile 116	C++
 	leveldown.node!leveldb::Table::Open() - Zeile 84	C++
 	leveldown.node!leveldb::TableCache::FindTable() - Zeile 64	C++
 	leveldown.node!leveldb::TableCache::NewIterator() - Zeile 97	C++
 	leveldown.node!leveldb::VersionSet::MakeInputIterator() - Zeile 1226	C++
 	leveldown.node!leveldb::DBImpl::DoCompactionWork() - Zeile 877	C++
```

The leveldb logfile shows the reason for this:
```
2016/09/10-13:44:46.812 29d8 Compacting 191616@0 + 0@1 files
```

I used the repair button once. Now my leveldb is uncompressed. It doesn't matter what I do on the GUI. As soon as leveldb starts compacting my memory will grow.

**Comment by littleskunk** [comment]
Test Result:
1.) Compacted leveldb is working fine. No OutOfMemory Exception.
2.) OutOfMemory Exception even with open file limit 100 (instead of 1000)

**Comment by littleskunk** [comment]
Workaround:
Use CLI to compact leveldb and than happy farming with GUI. This will only work for medium size (~300GB or less). Be carefull with the nodeID. The shard migration from GUI to CLI is not that easy.

@aleitner @bookchin  now its your turn.
Wait for https://github.com/Storj/core/issues/143? Find a way to avoid OutOfMemory exception and to many open files exception with leveldb?

**Comment by littleskunk** [comment]
As I can see the new storage adapter is comming next week. I think we can wait that long and try again.
