### ISSUE TITLE
Windows client cannot get shards if the farmer.db directory is open in Windows Explorer

### ISSUE THREAD

**Issue by Miskerest** [Storj/storjshare-gui#363]
### Versions

Replace the values below with your own:

- **GUI Version:** 2.0.3
- **Operating System:** Windows 10 Build 14366

### Expected Behavior

Running and receiving shards normally with `farmer.db` directory open

### Actual Behavior

Cannot get contracts/write shards to disk, gives error message in console that file `LOCK` is in use in another program.

### Steps to Reproduce

Open `farmer.db` in Windows Explorer, start Storj Share and no contracts will succeed.

**Comment by bookchin** [comment]
LevelDB implements a locking mechanism. Only one process can access it at a time.
