### ISSUE TITLE
IO error: /mnt/data/storj/farmer.db/047369.ldb: Too many open files

### ISSUE THREAD

**Issue by fredbeltrao** [Storj/storjshare-gui#368]
### Versions

Replace the values below with your own:

- **GUI Version:** 2.0.5
- **Operating System:** Ubuntu 16.04 LTS

I see several entries on log like this
`{error} [Wed Aug 31 2016 08:07:37 GMT-0300 (BRT)] IO error: /mnt/data/storj/farmer.db/047369.ldb: Muitos arquivos abertos` on both drives.

Muitos arquivos abertos can be translated as: Too many open files

Some information about my 2 drives:
- Drive 199bda: 64211 contracts and 223 log entries of error
- Drive 17990e: 22593 contracts and 1423 log entries of error

[2016-8-31-logs.zip](https://github.com/Storj/storjshare-gui/files/447077/2016-8-31-logs.zip)

**Comment by super3** [comment]
@fredbeltrao This is because Storj is too big and too cool for vanilla Level DB, which we use to store the files. We are working on a solution to this [here](https://github.com/bookchin/kfs).
