### ISSUE TITLE
Storj doesn't verify space offered <= space available

### ISSUE THREAD

**Issue by utdrmac** [Storj/storjshare-gui#372]
### Versions

Replace the values below with your own:

- **Storj Share:** 2.0.6
- **Core Lib:** 3.1.1
- **Protocol:** 0.8.1
- **Operating System:** Ubuntu 14.04

### Expected Behavior

When offering XXGB of space to share, one would expect Storj to verify/validate that much free space is available on the drive and present an error to the user if space is not available.

Additionally, when "No space left on device" type error is reached, Storj should stop offering out contracts until space has been made available.

### Actual Behavior

- Storj does not verify free space.
- Storj continues to offer contracts despite there being no free space.

### Steps to Reproduce

1. Create a 19GB partition
2. Mount it somewhere
3. Configure Storj-GUI to share this mount and specify 20GB available
4. Wait for contracts to fill it up
5. Observe 'No space left' errors in logs

### Screenshots (Optional)

```
root@drmac-ubuntu:~/.config/Storj Share# df /opt/storj20gb_a/
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sdb2       19091584 19075208         0 100% /opt/storj20gb_a

{error} [Wed Sep 07 2016 08:49:53 GMT-0500 (CDT)] IO error: /opt/storj20gb_a/farmer.db/107058.ldb: No space left on device
{error} [Wed Sep 07 2016 08:49:53 GMT-0500 (CDT)] IO error: /opt/storj20gb_a/farmer.db/107058.ldb: No space left on device
```

**Comment by utdrmac** [comment]
gparted reports the above partition as follows:

File system: ext4
Size: 18.63 GiB
Used: 18.58 GiB (100%)
Unused: 49.79 MiB (0%)

**Comment by utdrmac** [comment]
18.63 GiB = 20003810 Kilobytes = 20.00381 Gigabytes

The GUI says "Allocated Space: 19 GB" which to me means Gigabytes (2^10). Which should be 19922944 Kilobytes. 

Boy this is stupid...

```
root@drmac-ubuntu:~/.config/Storj Share# df -BG --si /opt/storj20gb_a/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb2        20G   20G     0 100% /opt/storj20gb_a

root@drmac-ubuntu:~/.config/Storj Share# df -BG /opt/storj20gb_a/
Filesystem     1G-blocks  Used Available Use% Mounted on
/dev/sdb2            19G   19G        0G 100% /opt/storj20gb_a
```

**Comment by aleitner** [comment]
https://github.com/aleitner/core/commit/762873116c0c0d1db30415e958013e239ed71e85 

It checks assuming you don't put a number greater than what you actually have...

That being said we will add some checks into place where it won't try to get contracts if there is no space available.

**Comment by utdrmac** [comment]
@aleitner I disagree with your first statement. I just tested this too with the latest GUI. I stopped Storj, upped the offer space to 30GB and started it back up. No errors anywhere. The "fill bar" even changed from 100% used to 65% used when I started it back up.

**Comment by bookchin** [comment]
You are certainly free to disagree, but @aleitner is 100% correct and even cited the line of code. As long as you do not over commit the drive, we *do* check that there is enough space available.

We do *not* check whether or not you have over committed the drive, which is where your problem is. You created an 19GB partition and told the program to fill up 20GB. It is doing exactly what you told it to do.

As @aleitner, at some point we can add checks to make sure that the user is not over committing the drive.

**Comment by utdrmac** [comment]
@bookchin Ok. I'll give ya that. 👍  There should be checks when clicking 'Start Storj' that: 1) verifies available space, 2) checks that offered space <= available space. Either of these should produce visible errors to the user and (most importantly) not start the Storj process.
