### ISSUE TITLE
install gui in silent mode - windows

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#374]
To skip all the installation questions, and to allow mass deployment of the GUI

Can you add a -s option to the GUI installer for windows (or something similar) to allow for seamless deployments?

So if I were a user whom would want to deploy this app automatically or seamlessly having the above options would take care of this for those scenarios.

**Comment by super3** [comment]
If you are doing a mass automated deployment do you really even need the GUI? Best done by the command line tool I would think under the hood. Don't think its the job of the GUI to do this at our current stage.
