### ISSUE TITLE
Windows - Hit the X notify user of app still running in background

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#375]
As a user I would expect hitting the red X would close the application altogether.  However, instead that just closes the command modal and the app is still running in the system tray (in the background).

Could you make it so when you hit the X a window would pop-up saying hey the app the is still running the background

Of course this window could have a checkbox on it saying don't show this me again; and in the advanced settings it would allow you to adjust as needed too.

**Comment by super3** [comment]
@computeronix This is the expected behavior when "Display in system tray" is selected. While I agree that this might be an extra bit of polish to the app, the default behavior of the app is to run in the background and it should do that unless the user deselects that option.
