### ISSUE TITLE
Storj Shares not starting

### ISSUE THREAD

**Issue by antogish** [Storj/storjshare-gui#377]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3

Storj Share 2.0.6

Core Library 3.1.1

Protocol 0.8.1

- **Operating System:** Ubuntu 14.04

Windows 10

### Expected Behavior

Please describe the program's expected behavior.

4 physical drives in desktop with 4 corresponding storj shares.
Only two shares start after rebott.
The other two shares have to to started manually
Am also unable to uninstall the Storj application.

tried a re-install over the top of the old application, with errors complaining that files existed. had to slect 'skip' a number of times.

After reinstall over the top, the issue remains.

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
For a clean reinstall you have to quit the GUI. If you close the window the GUI is still running in the background. That is the reason for the error messages.

Do you have more informations about the 2 drives not starting after reboot? Always the same 2 drives or is it random? Is there anything special?

**Comment by littleskunk** [comment]
Please add your config.json located in %AppData%. Remove the private keys for all 4 drives. Nobody else should see them.

**Comment by antogish** [comment]
I stopped the shares, then quit the gui, then ran the latest install which ran without error, uninstalling the old app and re-installing the latest app. The shares now start correctly after a reboot.
