### ISSUE TITLE
Windows Firewall

### ISSUE THREAD

**Issue by antogish** [Storj/storjshare-gui#380]
### Versions

Storj Share 2.0.6

Core Library 3.1.1

Protocol 0.8.1

Windows 10 Pro connected to network by WiFi

### Issue

Contracts and shards do not appear to be increasing. Appears to be a firewall issues as described inthe following article:

http://docs.storj.io/docs/windows-firewall-with-advanced-security-stealth-mode-applies-to-windows-vista-and-server-2008-and-higher

I have applied the "Disable Stealth Mode" registry update but it has not resolved the issue, with consistent 5152 errors in the Security Log.

When I look at the registry update file and also the manual registry update, it does not look like it corresponds to Windows 10 Pro registry. the following does not exist:

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsFirewall

The closest path match is as follows:

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender

The article specifies:

Applies to Windows Vista and Server 2008 and higher

Is an updated registry update required for Windows 10 (Pro)?

**Comment by antogish** [comment]
After further analysis of the windows Security Log I am uncertain whether the contracts are not increasing because of the firewall, or because demand for disk space if currently lower than supply. Copy of one of the 5152 events here:

The Windows Filtering Platform has blocked a packet.

Application Information:
	Process ID:		936
	Application Name:	\device\harddiskvolume4\windows\system32\svchost.exe

Network Information:
	Direction:		Inbound
	Source Address:		192.168.1.11
	Source Port:		5353
	Destination Address:	224.0.0.251
	Destination Port:		5353
	Protocol:		17

Filter Information:
	Filter Run-Time ID:	68088
	Layer Name:		Receive/Accept
	Layer Run-Time ID:	44

**Comment by super3** [comment]
@computeronix Have anything to add here?

**Comment by computeronix** [comment]
I am not sure how the below log sample would relate to storj as that is UDP and storj strictly talks over TCP, unless something has changed

Plus the destination is a broadcast address and not relevant to storj

Network Information:
Direction: Inbound
Source Address: 192.168.1.11
Source Port: 5353
Destination Address: 224.0.0.251
Destination Port: 5353
Protocol: 17

**Comment by antogish** [comment]
Have resolved this, have two firewall routers for security and moved server from internal network which had its own DNS server to outer network and specified Google DNS servers and contracts then started to increase.

**Comment by computeronix** [comment]
The manual registry entry will have to be created as by default the Policies folder is empty or very limited; the provided REG file should help with this

**Comment by computeronix** [comment]
ok perfect!  nice find!
