### ISSUE TITLE
Doesn't start on Ubuntu 16.04

### ISSUE THREAD

**Issue by ypadlyak** [Storj/storjshare-gui#381]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.6
- **Operating System:** Ubuntu 16.04

### Expected Behavior

The GUI does start up

### Actual Behavior

The GUI doesn't start 

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install storjshare-gui.amd64.deb
2. run it from console or Desktop
3. Check if it showed up

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
I installed ubtuntu 16.04.1 on virtualbox and storjshare-gui 2.0.6 is running fine.

Do you get any error message or something like that?

**Comment by ypadlyak** [comment]
No, no errors. Even when I run it in the console.

**Comment by aleitner** [comment]
Do you still have issues?

**Comment by ypadlyak** [comment]
Yes, I do

**Comment by lekanovic** [comment]
I have the same issue on Ubuntu14 and on OSX el capitan In both cases the Storj application does not start. Before the upgrade it worked fine, I don't see any logs or error messages.

**Comment by littleskunk** [comment]
I updated my linux and my osx build system. Please try again. If you still have problems please open storjshare from command line and copy the error message and stack trace.

**Comment by lekanovic** [comment]
Great, it works for me now on the OSX I have not tried it on the Ubuntu yes. But anyway thanks for the quick update

**Comment by aleitner** [comment]
I installed it using dpkg successfully, and also using gdebi successfully. I was able to run it just fine on Ubuntu 16.04 after installation
