### ISSUE TITLE
Malware detected inside storjshare-gui.win32

### ISSUE THREAD

**Issue by slrslr** [Storj/storjshare-gui#382]
### Versions

- **GUI Version:** v1.0.3
- **Operating System:** Windows 32bit

### Expected Behavior

Clean, no malware

### Actual Behavior

Malware detected:

- HEUR/QVM20.1.0000.Malware.Gen
- Malware.Heuristic!ET (rdm+)

https://www.virustotal.com/en/file/2cef7e9244ac090716613e1014f1b5ad754a1bc3fb024939e87d3308c71ce6c8/analysis/1474747290/

### Steps to Reproduce

Download storjshare-gui.win32 and scan it using virustotal.com

**Comment by littleskunk** [comment]
Both are false positives.
