### ISSUE TITLE
Windows client hangs on drive startup/initialization

### ISSUE THREAD

**Issue by Miskerest** [Storj/storjshare-gui#386]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.7
- **Operating System:** Windows 10, Server 2008 R2

### Expected Behavior

Prior to this version, the service would start correctly, connect to the network, and begin obtaining contracts.

### Actual Behavior

Upon clicking the "Start StorjShare" button, the button text changes to "Preparing..." and is grayed out. No output is printed to the console, and no contracts are executed. No apparent network or process activity appears in Resource Manager/Task Manager from the Storj Share process.

### Steps to Reproduce

Download, install, setup, and attempt to run the StorjShare GUI on any Windows machine. I have experienced this issue on Windows 7, 10, and Server 2008 R2 installations.

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 
![Screenshot from RDP session showing the error.](https://cloud.githubusercontent.com/assets/14872607/19100241/fad98710-8a8a-11e6-822b-1d14a719050b.png)

**Comment by littleskunk** [comment]
You missed the release notes: `Please be aware that upgrading before the latest bridge release is deployed will result in a failure to connect to the storj network. Join the #announcements channel in our community for updates.`

**Comment by uiharu-s** [comment]
The download link on https://storj.io/share.html currently points to v2.0.7 though.
This might not be friendly for new users.

**Comment by Miskerest** [comment]
@uiharu-s Yeah, I just assumed that whatever the most recently published version was should be the one I was using. Perhaps a disclaimer on the website would be helpful.
