### ISSUE TITLE
2.0.7 doesnt show  SJCX balance windows 10

### ISSUE THREAD

**Issue by misternils** [Storj/storjshare-gui#389]
### Versions

- **GUI Version:** v2.0.7
- **Operating System:** windows 10

### Expected Behavior

Balance: shows SJCX balance of payout address

### Actual Behavior

Balance shows "0" sjcx

### Steps to Reproduce

I installed the newest version, got connected using the manual URI with a storj.dk address. Everything is running, but it shows balance of 0 sjcx

**Comment by littleskunk** [comment]
tab.address is undefined even if a payout address is set

**Comment by misternils** [comment]
does this mean i am doing something wrong, or were you just better defining the bug skunk?

**Comment by br3nn** [comment]
I can confirm, I have same issue.. Windows 10 64bit, and Server 2012 :)

**Comment by cacalillos** [comment]
I have same issue. Windows 2008 R2 Datacenter

**Comment by trotskylenin** [comment]
Same issue in Ubuntu 14.04
