### ISSUE TITLE
Upgrade to 2.0.7 for Windows lost drive configs 

### ISSUE THREAD

**Issue by jburnett** [Storj/storjshare-gui#390]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.7
- **Operating System:** Windows 10, v 1607, bld 14393.222

### Expected Behavior
Upgrade from 2.0.6 to 2.0.7 should remember all drive configs

### Actual Behavior
Storj runs fine, but all 3 of my drive configs seem to have been lost.  It appears to be a clean slate.  I attempted to add the drives again with the same payout address, but didn't get past the first drive.  After starting the first drive, Storj appeared stuck in Pending.

### Steps to Reproduce
Unknown

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 

Settings file show the 2.0.6 settings and the 2.0.7 settings after config'ing one of the drives.
[Storj-settings.zip](https://github.com/Storj/storjshare-gui/files/518032/Storj-settings.zip)

**Comment by jburnett** [comment]
Log file after config'ing a previous location and starting.
[Drive-47f6d3_2016-10-8.txt](https://github.com/Storj/storjshare-gui/files/518033/Drive-47f6d3_2016-10-8.txt)

**Comment by littleskunk** [comment]
Everything works as expected. I don't see any issue here. The new GUI includes https://github.com/Storj/kfs/blob/master/README.md with a different shard folder and no shard migration. -> You will start farming from 0.

The new GUI requires a new bridge version. The storj bridge is not updated. Please read the release notes https://github.com/Storj/storjshare-gui/releases/tag/v2.0.7
