### ISSUE TITLE
2.0.7 doesnt show Used Space

### ISSUE THREAD

**Issue by br3nn** [Storj/storjshare-gui#391]
### Versions

- **GUI Version:** v2.0.7
- **Operating System:** Windows 10 Pro 64Bit / Windows Server 2012 R2

### Expected Behavior

Connected up using manual Seed information from http://server012.storj.dk/contacts?connected=true&page=1

Peers connected and contracts going up slowly, but it seems the space used is not returning to the figure it was before the update. 

Its been running 5 minutes, i will remove this post if it comes back

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
The new GUI includes https://github.com/Storj/kfs/blob/master/README.md with a different shard folder and no shard migration. -> You will start farming from 0.
