### ISSUE TITLE
Connection problems and used space went back to 0GB

### ISSUE THREAD

**Issue by trotskylenin** [Storj/storjshare-gui#393]
### Versions

- **GUI Version:** v2.0.7
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Maintain the amount of space used by clients before updating.
Connect to the network.

### Actual Behavior

"Used Space" returned to 0 GB after updating to 2.0.7. I tried repairing database but it was no help.
Now i have only 5.177 GB used.
Beyond that, it takes a lot of time or fails to connect - it stays in "Preparing..." a long long time... - and finally it throws a windows with an error saying it couldn't connect to the network.
I took a look at the logs... and a lot of time outs are happening. Here's a little example:

```
{warn} [Mon Oct 10 2016 00:00:03 GMT-0300 (ART)] rpc call c5d9ae69e07c2b24f524f33f96fad9ba9c46f31b timed out
{warn} [Mon Oct 10 2016 00:00:03 GMT-0300 (ART)] query failed, removing contact for shortlist, reason RPC with ID `c5d9ae69e07c2b24f524f33f96fad9ba9c46f31b` timed out
{warn} [Mon Oct 10 2016 00:00:03 GMT-0300 (ART)] failed to connect to seed storj://5.9.140.228:8000/4bf5cf262b548b2f424468e5dc3c7de2f4792e2a
{info} [Mon Oct 10 2016 00:00:03 GMT-0300 (ART)] attempting to join network via storj://104.196.117.1:8932/656ce89de61e745314f01ec4b8c90328154128bf
{info} [Mon Oct 10 2016 00:00:03 GMT-0300 (ART)] sending FIND_NODE message to {"userAgent":"4.0.0","protocol":"0.9.0","address":"104.196.117.1","port":8932,"nodeID":"656ce89de61e745314f01ec4b8c90328154128bf","lastSeen":1476068403212}
{warn} [Mon Oct 10 2016 00:00:07 GMT-0300 (ART)] missing or empty reply from contact
{warn} [Mon Oct 10 2016 00:00:33 GMT-0300 (ART)] rpc call 2d0b38cfa6930d4e4acf08e58a3a00b8faad58ee timed out
{warn} [Mon Oct 10 2016 00:00:33 GMT-0300 (ART)] query failed, removing contact for shortlist, reason RPC with ID `2d0b38cfa6930d4e4acf08e58a3a00b8faad58ee` timed out
{warn} [Mon Oct 10 2016 00:00:33 GMT-0300 (ART)] failed to connect to seed storj://104.196.117.1:8932/656ce89de61e745314f01ec4b8c90328154128bf
{info} [Mon Oct 10 2016 00:00:33 GMT-0300 (ART)] attempting to join network via storj://storj.aphint.com:6001/0f19d1b8765b5e189e941d8fc362bb222ee870b3
{info} [Mon Oct 10 2016 00:00:33 GMT-0300 (ART)] sending FIND_NODE message to {"userAgent":"4.0.0","protocol":"0.9.0","address":"storj.aphint.com","port":6001,"nodeID":"0f19d1b8765b5e189e941d8fc362bb222ee870b3","lastSeen":1476068433225}
{warn} [Mon Oct 10 2016 00:00:34 GMT-0300 (ART)] missing or empty reply from contact
{warn} [Mon Oct 10 2016 00:00:40 GMT-0300 (ART)] missing or empty reply from contact
{warn} [Mon Oct 10 2016 00:01:03 GMT-0300 (ART)] rpc call f3283b28be1dff3add7f7bdd10ffa4b34218a0db timed out
{warn} [Mon Oct 10 2016 00:01:03 GMT-0300 (ART)] query failed, removing contact for shortlist, reason RPC with ID `f3283b28be1dff3add7f7bdd10ffa4b34218a0db` timed out
```

### Steps to Reproduce

Open StorjShare and wait.

### Screenshots (Optional)

![storjsharefail](https://cloud.githubusercontent.com/assets/6507464/19241629/d5834212-8ee5-11e6-8be6-5cf8cc12d3f0.png)

**Comment by littleskunk** [comment]
The new GUI includes https://github.com/Storj/kfs/blob/master/README.md with a different shard folder and no shard migration. -> You will start farming from 0.

The new GUI requires a new bridge version. The storj bridge is not updated. Please read the release notes https://github.com/Storj/storjshare-gui/releases/tag/v2.0.7

**Comment by trotskylenin** [comment]
So what do you recomend me to do? Should I just wait for Bridge update? Or should I roll back?

**Comment by littleskunk** [comment]
I can't give you any advice. That is up to you. You can downgrade and run the old version while you wait for the bridge update or your use an already updated node as seed. Join us on https://community.storj.io/ if you need help.
