### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#395]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.8
- **Operating System:** windows 10

### Expected Behavior

Farming continues as usual.

### Actual Behavior
These errors follow each other if i click on 'ok' on the box:
After the box goes away i get a WSOD.

![2016-10-11 1](https://cloud.githubusercontent.com/assets/11735738/19289436/0f7b2b4e-900b-11e6-968a-10aa94b249ef.png)
![screenshot3](https://cloud.githubusercontent.com/assets/11735738/19292339/a62626c4-901b-11e6-8ed6-20776f9eedb5.png)
![screenshot](https://cloud.githubusercontent.com/assets/11735738/19292341/a680ebae-901b-11e6-9085-993d24ed0b16.png)
![screenshot2](https://cloud.githubusercontent.com/assets/11735738/19292340/a62c9c02-901b-11e6-8baa-59f4159d1f66.png)
![screenshot4](https://cloud.githubusercontent.com/assets/11735738/19292355/c7998a4e-901b-11e6-8a96-8af74913047f.png)

### Logs:

[logs.zip](https://github.com/Storj/storjshare-gui/files/523945/logs.zip)

### Steps to Reproduce

Run the latest storjShare-GUI for a hour or two.

**Comment by mo35** [comment]
same , setup 2.0.8 win10 , after couple of hours i had like 10 of thos messages stacked

**Comment by MeijeSibbel** [comment]
These errors follow the one above if i click on 'ok' on the box:
After the box goes away i get a WSOD.

![screenshot3](https://cloud.githubusercontent.com/assets/11735738/19292339/a62626c4-901b-11e6-8ed6-20776f9eedb5.png)
![screenshot](https://cloud.githubusercontent.com/assets/11735738/19292341/a680ebae-901b-11e6-9085-993d24ed0b16.png)
![screenshot2](https://cloud.githubusercontent.com/assets/11735738/19292340/a62c9c02-901b-11e6-8baa-59f4159d1f66.png)
![screenshot4](https://cloud.githubusercontent.com/assets/11735738/19292355/c7998a4e-901b-11e6-8a96-8af74913047f.png)

**Comment by kylegates** [comment]
I got the same type of error running on linux. I think it has something to do with the log file cleanup as all my errors were in /tmp where I had logs stored.

**Comment by matanbr** [comment]
Having same errors ... also 2.0.8 in Windows 10 , I have set it on "No Logging" so I dont know if that is the reason.
![error1](https://cloud.githubusercontent.com/assets/9035057/19298363/b2dc389c-9055-11e6-8897-e5b05b5f0882.png)
![error2](https://cloud.githubusercontent.com/assets/9035057/19298364/b2de57f8-9055-11e6-80f9-d4d7e68cb64a.png)

**Comment by Miskerest** [comment]
I get the same, in addition to #396.

**Comment by bookchin** [comment]
EPERM is in reference to a user permission problem. Has anyone, at any time, done anything to change the ownership of the Storj Share application data directory? Or run the application as root/admin?

**Comment by MeijeSibbel** [comment]
@bookchin, no, i have the same issue on 5 PC's , Storj was working before this release and nothing was changed on the machines for at least a few months. Antivirus also isn't the issue.

**Comment by MeijeSibbel** [comment]
@bookchin ,I think i found a possible cause, even after i deleted the old farmer.db the shard count was still taken up into the GUI(while the folder did not exits anymore). After all the crashes and the removal of the user settings i again inputted the user info, now the shard count is the actual shard count of kfs instead of the kfs + farmer.db shards. Maybe deleting the shard folder caused some sort of permission error as the old shard folder isn't there anymore, so it can't access it. Now it appears it is working without a issue. I will report back if the issue still pops-up.

**Comment by DaSpawn** [comment]
no permission changes, and I only upgraded from 2.0.6->2.0.8 yesterday and removed the farmer.db
I am on Ubuntu 16.04 and had same errors/problem:

EISDIR: illegal operation on a directory, unlink '/home/brianbee/.config/Storj Share/GPUCache

also same error on GPUCache.bad, Local Storage, looped 3 times for each error when clicking OK

**Comment by kylegates** [comment]
It seems to be trying to remove every file in the configured log directory that isn't a current log file.

**Comment by bookchin** [comment]
@kylegates alex just dropped the gamecube controller and said "oh my god it is" - expect a fix shortly
