### ISSUE TITLE
GUI forgets user config after error or GUI/computer reboot

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#396]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.8
- **Operating System:** Windows 10

### Expected Behavior

After a reboot or crash of the GUI due to this error: https://github.com/Storj/storjshare-gui/issues/395 , the GUI should remember the user data/config.

### Actual Behavior

After a reboot or after some hours of sitting on error: https://github.com/Storj/storjshare-gui/issues/395 the GUI forgets all entered/reconfigured user data such as wallet address, HDD directory... The settings.json file is now empty.

### Steps to Reproduce

Run the latest GUI until you get https://github.com/Storj/storjshare-gui/issues/395, then let it sit there for a few hours until the GUI forgets the entered user data> Alternatively a computer restart after the error also removes the user config.

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by mo35** [comment]
had one same occurance , from 8 instances , 2.0.8 win10 x64

**Comment by brad-pea** [comment]
Experienced the same also ....

11 Nodes - 2.0.8 Win10 x64

**Comment by Blackwolfen** [comment]
The problem seems to be that it had a preferences where it did hold the config. New it uses a settings but im not sure. I had the same issue and the same error as Miskerest. Might be the Key also changed?

**Comment by DaSpawn** [comment]
I also had this happen, 2 clients, Ubuntu 16.04 and both clients deleted my config and I did not have a backup of config/keys.  Client was still running when I came in but problem did not show until I restarted client

**Comment by jackyq2015** [comment]
Dup of #329 which was closed
