### ISSUE TITLE
WSOD is back

### ISSUE THREAD

**Issue by lfintor** [Storj/storjshare-gui#400]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.9
- **Operating System:** Windows 10 64bit

After around 8-9 hours continuous running (estimate) client WSoD-ed. It managed to farm around 10GB.

**Comment by billstanden** [comment]
Also present in v2.0.10 on OS X.

**Comment by littleskunk** [comment]
I created a few memory snapshots again.

Strings are growing. I see many PUBLISH messages. Based on the timestamps (TTL and store_begin) this message is a few minutes old. I will create a new memory dump later and search for this message. I should not be able to find it but I guess I will find it.
`"{"jsonrpc":"2.0","id":"f10d5dec05978032600172978f3e94c944704e0a","result":{"contact":{"userAgent":"4.0.5","protocol":"0.9.1","address":"server022.storj.dk","port":5002,"nodeID":"a69d4f2e3e97e4f26ece3d437b2825c5d7fed9e6","lastSeen":1476571487835},"contract":{"audit_count":3,"data_hash":"bc5f7febf7f18ca213d18f9780d97cea77381188","data_size":16777216,"farmer_id":"b408aeb67291e4d1994a95394e674c09eb683d3c","farmer_signature":"H8jrQGRiOLqt2nWt6aC4pt+s/pvgGN3LNL8QG12bhNzCZx138MtwY4xsco0ycrrpJl754l+Tv+P9eK0UCS78S/M=","payment_destination":"152z2MnvvpHz3XCNgC4GQUd9RCrupzger5","payment_download_price":0,"payment_storage_price":0,"renter_id":"a69d4f2e3e97e4f26ece3d437b2825c5d7fed9e6","renter_signature":"H/p3X8uawUZBgzzzV+iFEmWNNPQzIVm7TkAGK0lyeTBfMsC7EiUHJblQ8n3d319ATXU6YSZ7uUnrcT0vuwx4R8c=","store_begin":1476571941074,"store_end":1484347941074,"version":0},"nonce":1476571957167,"signature":"HzedL9LzUtIuZEnxrUtXtzBMHhI2OVKryqiYYiN7YfTlTfAyAhl+VZukwtaV2Mu7zx1M6qMJ4tewwYYJxnwKxsQ="}}"`

**Comment by littleskunk** [comment]
New test with loglevel debug. That way I was able to see the messages on my logfile. Some of them survive 30 minutes but at the end the garbage colletor will get them. There can't be the reason for the WSOD.

First test I used an empty folder as storage location and start farming. 50MB RAM usage. Everyting fine.
Second test I used my old storage location. 400GB farmer.db subfolder included. The new GUI 2.0.10 will run through these files. RAM usage goes up to 500MB.

Workaround for the moment: Make sure your storage location doesn't contain other files. No farmer.db subfolder or any other "useless" files. Only contracts.db and sharddata.kfs should stay there. @lfintor and @billstanden could you please try that?

**Comment by lfintor** [comment]
I removed the farmer.db folders back in 2.0.8 so that connot be it. I am on 2.0.10 and still experiencing WSOD.
NB I am running 20 drives currently.

**Comment by pvdl** [comment]
Also present in v2.0.10 on Linux.

**Comment by billstanden** [comment]
@littleskunk I did have a farmer.db subfolder still but deleting them made no difference on 2.0.10

Upgraded to 2.0.11 to see if it would help and it seems to have lost the entire dataset so I'm starting everything over from scratch.  Will report how it goes.

**Comment by lfintor** [comment]
Still an issue in 2.0.11

**Comment by amdstorm** [comment]
Ran with the Developer tools, it crashed with the error `too many files open` for mine. So i increased it on my ubuntu. Testing again

**Comment by aleitner** [comment]
@amdstorm can you post the full error message next time you see it?

**Comment by lfintor** [comment]
WSOD issue still present in 2.0.12 - NB it seems more stable, usually I manage to run the client for two hours/2GB before it breaks now it gets as far as 5GB and 5-6 hours.

**Comment by MeijeSibbel** [comment]
Today i got a WSOD on my laptop while i was watching it, right at the moment it went into the white screen i heard the 'windows permission sound' but nothing popped-up.

**Comment by MeijeSibbel** [comment]
After a few hours of running i get allot of the following warnings, their frequency tends to increase through time. 
![screenshot 2016-10-23 20 35 28](https://cloud.githubusercontent.com/assets/11735738/19628641/07eb02ee-9963-11e6-83f2-dc34505d6ee1.png)

**Comment by littleskunk** [comment]
I build a new test windows binary with a electron 1.4.4. Please try it out and let us know if it helps.
https://github.com/Storj/storjshare-gui/releases/download/v2.0.12/storjshare-gui.win32.test.exe

**Comment by aleitner** [comment]
I have a computer set up with it's screen being recorded. Hopefully we can catch it before my hard drive runs out of space

**Comment by lfintor** [comment]
This issue needs to be re-opened. Ran into issue after about 8 hours running on 2.0.13
