### ISSUE TITLE
v2.0.10 on windows 10 (EBUSY: resource busy or locked, lstat 'E:\pagefile.sys' on startup

### ISSUE THREAD

**Issue by aruikis** [Storj/storjshare-gui#402]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
A few more information would help. The issue template is complete empty. Please take a look at the developer console and copy any error stacktrace you see there.

**Comment by aruikis** [comment]
![image](https://cloud.githubusercontent.com/assets/22847621/19406235/07d951a6-9248-11e6-8b43-179820d4e81b.png)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/404
