### ISSUE TITLE
EPERM: operation not permitted, lstat 'D:\System Volume Information'

### ISSUE THREAD

**Issue by dlmac** [Storj/storjshare-gui#404]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.10
- **Operating System:** Windows 10 pro

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
See Screenshot

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start GUI

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 
![image](https://cloud.githubusercontent.com/assets/372043/19406150/c58eb4ec-924e-11e6-8c0e-2799472e9c0c.png)

**Comment by littleskunk** [comment]
Please don't use your complete D drive as target. Create a subfolder for storj and move contracts.db and sharddata.kfs.

**Comment by dlmac** [comment]
thank you. that worked

**Comment by littleskunk** [comment]
Reopen. We have to fix it. Worst case we should at least print out a readable error message.

**Comment by super3** [comment]
I am reproducing this.
