### ISSUE TITLE
wrong available storage calculation if target directory starts with capital letter

### ISSUE THREAD

**Issue by mo35** [Storj/storjshare-gui#405]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.10
- **Operating System:** Win10 x64
- Clean Storj GUI reinstall , no shard data , no user settings

### Expected Behavior

Please describe the program's expected behavior.

making 1TB instance in directory with 1,16tb available space ( example J:\storj1 
![error](https://cloud.githubusercontent.com/assets/16078512/19407794/1f545bce-92b5-11e6-9c70-85483c65f204.jpg)
)

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

error msg "invalid storage size"

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. if you target disks root it calculates correctly available storage
2. if you target directory starts with capital ( J:\Storj ) , available space calculation fails
3. no problems with other combos J:\storj ; j:\storJ ; j:\storj1 ; etc

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by RedRockMining** [comment]
Getting same here. I would only add that it's not just the first character. I tried changing just the first character in my mixed lower and capital folder names and get the same error. Changing the folder name to all lower case works.

**Comment by stricq** [comment]
Getting same error here.
