### ISSUE TITLE
Storj Share Stopping After Update 2.0.10

### ISSUE THREAD

**Issue by antogish** [Storj/storjshare-gui#409]
Storj Share 2.0.10

Core Library 4.0.4

Protocol 0.9.0

Windows 10 Pro

After updating to 2.0.10, Storj share starts normally, but then stops after a number of hours. This is happening on 4 different Windows 10 pro installations on four different PCs.

**Comment by aleitner** [comment]
In your settings is the checkbox for `Automatically restart farming if an error occurs` checked?

**Comment by antogish** [comment]
Yes

**Comment by MeijeSibbel** [comment]
I have also noticed this, it will just stop and the number of peers will drop down to 0. A complete restart of the app is the only thing that works.

**Comment by antogish** [comment]
Tried that and it is currently specifying "Preparing" as in the screen shot. That is also just a work around, can't monitor the app restarting it every 24hrs.

The version I installed about 6 week ago ran for about 4 weeks without fail. These recent releases of the last 1-2 weeks seem to be a bit buggy.

![image](https://cloud.githubusercontent.com/assets/22293756/19448729/f6d2db48-949a-11e6-90bc-d6f1d1f8ddd2.png)

**Comment by antogish** [comment]
Finally started after about 5 minutes. Suspect it will stop again though overnight.

![image](https://cloud.githubusercontent.com/assets/22293756/19449347/25eaf7a6-949d-11e6-9da6-ff4249e94ad3.png)

**Comment by aleitner** [comment]
Post your logs after it stops again. I don't have any relevant information here

**Comment by antogish** [comment]
Zipped logs attached:

[Log Zip.zip](https://github.com/Storj/storjshare-gui/files/534953/Log.Zip.zip)

**Comment by MeijeSibbel** [comment]
[logs.zip](https://github.com/Storj/storjshare-gui/files/537060/logs.zip)

**Comment by littleskunk** [comment]
@aleitner @antogish ports are closed. Tunnel connection but wrong order on reconnect. The tunnel is established to late. I will try to reproduce it. New issue will follow.

**Comment by littleskunk** [comment]
Yes that must be the reason. On each core + GUI restart I see this error message:
`{error} [Mon Oct 17 2016 19:23:42 GMT+0100 (GMT Summer Time)] Could not get usedSpace: IO error: LockFile F:\Storj\sharddata.kfs\000.s/LOCK: The process cannot access the file because it is being used by another process.`

**Comment by simernes** [comment]
I also have this problem running it on Linux Mint. Pretty much exactly as @antogish describes it

**Comment by littleskunk** [comment]
@simernes logfile please

**Comment by simernes** [comment]
[StorjDrive-06c719_2016-10-18.log.tar.gz](https://github.com/Storj/storjshare-gui/files/537521/StorjDrive-06c719_2016-10-18.log.tar.gz)

**Comment by aleitner** [comment]
In 2.0.10 the farmer would leave and join on restart without waiting for the leave to finish. in 2.0.11 I updated the restart script to wait for the leave to finish before rejoining. Is this a 2.0.10 only issue?

**Comment by aleitner** [comment]
Also this is a duplicate of #407

**Comment by antogish** [comment]
No, this is a 2.0.11 issue also. Upgraded to 2.0.11 24 hrs ago and multiple windows PCs shares had stopped when I checked this evening.

**Comment by antogish** [comment]
This issue no longer occurs after update 2.0.12. Closing this issue down.

**Comment by aleitner** [comment]
Some of the restartfarmer on error logic was fixed in 2.0.12 so I suspect that must have resolved this.
