### ISSUE TITLE
Invalid storage size with v2.0.11

### ISSUE THREAD

**Issue by kylegates** [Storj/storjshare-gui#411]
### Versions
- **GUI Version:** v2.0.11
- **Operating System:** Ubuntu 16.10

### Expected Behavior
```
Should start and run.
```

### Actual Behavior
```
Getting error "Invalid storage size"
```

### Steps to Reproduce
1. Installed 2.0.11
2. Press Start
3. Get error "Invalid storage size"

My storage location is on a different filesystem then the config directory.
/home is btrfs raid1 on ssd 43GB free
/data is btrfs raid10 on spinning rust 212GB free

I currently have around 2.5GB used out of 100GB allocated.
If I set Storage Size to less than 2.5GB Storj Share will start. Larger values will give the error "Invalid storage size"
If I empty the folder and try again it will start but then the same problem happens after stopping and trying to start again.
Found some lines like the following in the log:
Could not get usedSpace: IO error: /data/storjshare/storjshare-efa0c1/sharddata.kfs/250.s/MANIFEST-000126: Too many open files

**Comment by WilhelmGGW** [comment]
I have the same issue on Linux Mint 17. Main node on CPU and 5 on an external hdd. All worked fine on prior versions. Now they throw up the 'invalid storage size' message and will not start. Also, the 5 show 0 space available. When I tried to start each of these for the first time with the new version, it engaged well enough to set up the new data directory - as warned; but will not recognize that directory to show available space nor start the program.

**Comment by ShawnLeary** [comment]
Recently updated to 2.01.11 on Mac El Cap 10.11.6 and no getting 'Invalid storage size' on both drives when I try to Start.

**Comment by aleitner** [comment]
It would help if everyone includes the following:
Storage Location Path:
Size of bytes listed to the right of this:
Storage Size:
Actual size of disk that you are trying to use for shard storage:

**Comment by WilhelmGGW** [comment]
For one of my 5 locations on the external hard drive..
/media/gary/Seagate Expansion Drive/Storj1
0 B
900 GB
5 TB

**Comment by WilhelmGGW** [comment]
While you're working on the Linux GUI, here's another issue for you. I have it on my Linux install, but not on any of my Windows installations: The automatic restart when errors occur does not work. It attempts to restart. The Preparing bar and screen stays up for just a second. Then it goes to WSOD and stays dead. I've witnessed this several times while I was watching the screen. This happens when I've selected - and am watching - the screen of the well-running node when it crashes.

If I happen to be watching the screen of another node when the primary node crashes, of course I don't know it crashed till I select and see it. But when I do, it doesn't show it's running, or preparing, or the WSOD. It just shows the orange start button, waiting to be manually restarted.

**Comment by WilhelmGGW** [comment]
And then.. this just happened: The Linux node restarted itself just like it should. No WSOD. And with the window open and visible. Go Figure. Very erratic.

**Comment by aleitner** [comment]
Having a lot of trouble reproducing any of this. Everything is tested and working on Mac 10.12, Ubuntu 16.04, and Debian 8 so far. Trying other OSes. Still trying to reproduce

**Comment by aleitner** [comment]
GOt it working on Ubuntu 14.04 and Archlinux

**Comment by billstanden** [comment]
On macOS 10.12 I get this consistently for my secondary drive.

/Storj/ works fine on the primary disk
/Volumes/Storage HD/Storj/ on the secondary fails with Invalid Storage Size and reporting the disk size as 0B

**Comment by ruisilva93** [comment]
I'm on 10.12 and it does not work on any partition of my External HDD.
It is HFS+, GUID, the main one has 423GB. (other partitions are smaller) - all of them it say 0 B

**Comment by braydonf** [comment]
> Could not get usedSpace: IO error: /data/storjshare/storjshare-efa0c1/sharddata.kfs/250.s/MANIFEST-000126: Too many open files

I believe Mac OS has a lower limit for max open files, and leveldb can run into this issue more often there. The default of a LevelDB database is 1000, I wonder if this has anything to do with the issue.

**Comment by aleitner** [comment]
I have reproduced the issue. It's if the drive has spaces in it, it will fail. Working on a solution.

**Comment by littleskunk** [comment]
@aleitner fd-diskspace pull request open and my master branch updated. Should be fixed with the next GUI release.

**Comment by aleitner** [comment]
@littleskunk good to go!

**Comment by kylegates** [comment]
I'm still getting the error with v2.0.12.

**Comment by WilhelmGGW** [comment]
^^ ditto ^^ No fix with 2.0.12

**Comment by aleitner** [comment]
Are you on Windows?

**Comment by kylegates** [comment]
Linux

**Comment by WilhelmGGW** [comment]
Linux Mint 17

**Comment by creator276** [comment]
Os= win10
Storj version= 2.0.1
Storage path= Z:\           ( it is a network drive I have mapped to a letter)
Size on storj =0B
Real size= 2tb empty 


When I try to start it comes up with  invalid directory. It worked in older versions

**Comment by kylegates** [comment]
I have no spaces in the path to the data directory:
/data/storjshare/

**Comment by billstanden** [comment]
Can confirm it _is_ working for me under macOS with 2.0.12

**Comment by aleitner** [comment]
Looks like the spaces solved it for some people but there are still remaining issues for others. Will continue looking into other causes

**Comment by littleskunk** [comment]
I was able to reproduce it. It is very simple user error. I set my free space to 100TB and run into this: https://github.com/Storj/storjshare-gui/blob/9034beadc09ae05300bc36cd8a03ad2ef94d0632/app/lib/userdata.js#L193
If I set it to a valid value like 100GB everything is working fine. @billstanden @creator276 @WilhelmGGW @kylegates please reduce your free space and try again.

@aleitner Maybe change the error message? Print out the detected free space to give the user the chance to correct it? We should not remove it because the next issue would be "I set my free space to 1TB but after pressing the start button only 100GB is used and never increase".

I have no good idea. What would be the best solution for the user?

**Comment by WilhelmGGW** [comment]
This worked for me. Though I would argue I did not previously set my allocated space to very high (wrong) values. So I'm not sure this will solve the problem for everyone.

What I did - additionally - is this: I left v2.0.12 installed on my Linux Mint 17, but 
- Deleted all the nodes I'd previously created,
- Deleted all the data directories I'd previously created, and
- Set up all the devices again from scratch.

**Comment by stricq** [comment]
Still getting this error with 2.0.12 as well.  It doesn't matter what size I set the storage to, the error always pops up.  I've been offline for a week now.  Hope there is a fix soon.

**Comment by littleskunk** [comment]
@stricq Please map the networkshare as a drive and try again

**Comment by kylegates** [comment]
@littleskunk It turns out the free space was 0 because I was using a btrfs subvolume for the storage directory. When I switched to a folder it worked fine.
Here's a hint to the problem:
kyle@home:~$ df /data/storjshare
Filesystem      1K-blocks       Used Available Use% Mounted on
/dev/sdc2      1412456448 1192258288 218848064  85% /data
kyle@home:~$ df /data/storjshareOLD/
Filesystem      1K-blocks       Used Available Use% Mounted on
-              1412456448 1192258288 218848064  85% /data/storjshareOLD

storjshareOLD is the subvolume. Notice how the there is no path under the Filesystem column.

It looks like a btrfs bug.

**Comment by stricq** [comment]
Weird, I closed Storj and restarted it and it started working with the UNC path.  I did not have to map it.

**Comment by ShawnLeary** [comment]
just upgraded to .12 and getting the same message as soon as the app loads.

**Comment by globdesign** [comment]
Can we please make just make crap that works the first time people. The world doesn't have time for this.

**Comment by littleskunk** [comment]
@globdesign you are welcome to open a pull request with any improvement you have in mind.

**Comment by ElanHasson** [comment]
I had this issue on Windows, with GUI. I shut down Storj Share completely and then restarted it. It now works.

**Comment by renshuki** [comment]
I tried to upgrade to 6.4.0 and I get the same error here.  

![2017-08-15_142621](https://user-images.githubusercontent.com/7076736/29303418-b0b41936-81c7-11e7-900e-047db9c2d582.PNG)

Any workaround?

**Comment by littleskunk** [comment]
@renshuki reduce the allocated storage size.

**Comment by renshuki** [comment]
@littleskunk Thank you. HDD was getting full with the logs, my bad... 😞
