### ISSUE TITLE
Failed to handle offer

### ISSUE THREAD

**Issue by matanbr** [Storj/storjshare-gui#414]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.12
- **Operating System:** Windows 10

### Expected Behavior

```

```

### Actual Behavior

Getting  Failed to handle offer message on the Log
noticed that it is happening almost each time contract count is increasing

another problem that maybe this is relating to , the contracts count is increasing very good but the used space is increasing very slowly , maybe this error can indicate something about that.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by bookchin** [comment]
There is not enough information provided here to reproduce the issue. However, the contract count will fluctuate up and down as it is incremented when an offer is sent and decremented on an interval when stale contracts are reaped.

**Comment by matanbr** [comment]
Please tell me what info do you need to solve my issue , for couple of weeks now my farmer is not getting shards like it used to.
ports are open correctly , checked with http://www.yougetsignal.com/tools/open-ports/
and clocked is synced , checked with 2 different third party applications.
attached is the log from recent 2.0.16
[1.txt](https://github.com/Storj/storjshare-gui/files/558911/1.txt)
