### ISSUE TITLE
UI is all white after app running for a little while. Reload required to fix.

### ISSUE THREAD

**Issue by simernes** [Storj/storjshare-gui#415]
### Versions

Replace the values below with your own:

- **GUI Version:** storjshare 2.0.12
- **Operating System:** Linux Mint 17.3 

### Expected Behavior

Please describe the program's expected behavior.

Work as normal when returning to computer after a while

### Actual Behavior

When I've let the app run for a while and I come back to check it, the UI is all white. If I Reload (Ctrl+R) it starts up again, but it then also seems to restart. Or what I can say for sure is that there always seem to be 0 peers after I do a reload like that and it says Preparing for a while and then returns to normal.

### Steps to Reproduce

1. Start storjshare normally
2. Walk away from the computer for a while
3. Return and behold the white screen

### Screenshots (Optional)

![screenshot_2016-10-23_12-31-20](https://cloud.githubusercontent.com/assets/1278451/19625610/8406bc88-991d-11e6-8868-cca29c80d64a.png)

If the error is graphical in nature it is helpful to provide a screenshot. 

[StorjDrive-641632_2016-10-23.log.tar.gz](https://github.com/Storj/storjshare-gui/files/546278/StorjDrive-641632_2016-10-23.log.tar.gz)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/400
