### ISSUE TITLE
Too many open files error causes client to suspend

### ISSUE THREAD

**Issue by digidan** [Storj/storjshare-gui#416]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.12
- **Operating System:** OSX Sierra 10.12

### Expected Behavior

The program should run without issues continuing to get peers, collect shards, and take up disk space.

```

```

### Actual Behavior

After a short time of running the following error pops up EMFILE: too many open files, scandir '/then the path to my drive storjshare-f05727

When I hit ok sometimes the client starts running again other times it just hangs and doesn't come back without restarting it completely

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start storj share client on OS X
2. Leave running
3. Message pops up with error
4. hit ok
5. either restarts running again or most of the time just hangs on preparing forcing a restart of the app

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 
![screen shot 2016-10-20 at 3 23 39 pm](https://cloud.githubusercontent.com/assets/8356662/19631380/2735d1da-9961-11e6-9522-53ca4463f2d5.png)

**Comment by billstanden** [comment]
Beat me to it.  Was just about to write up the same.

Curious if this relates to #400 given people reporting too many open files in the developer tools.

I was getting WSODs with 2.0.10 and 2.0.11.  I'm notably not with 2.0.12, instead seeing this behaviour at about the same intervals.

**Comment by piadam** [comment]
I am seeing the same problem. It runs fine for hours then produces the 'Too many open files'-error and stalls.
Also, on macOS Sierra (10.12.1 Beta) I get some errors (in Terminal) when launching Storj Share:
![screen shot 2016-10-24 at 12 28 59 pm](https://cloud.githubusercontent.com/assets/2383586/19642556/2836c244-99e6-11e6-8e3e-f48e541a5860.png)

**Comment by digidan** [comment]
I also have the error that @piadam listed in his in my storjshare helper about the broken kqueue.
