### ISSUE TITLE
Screen stays in preparing / gets stuck at restarting farmer.

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#421]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.13
- **Operating System:** Windows 10 

### Expected Behavior

Farmer restarts quickly and gets back to farming.

### Actual Behavior

Farmer gets stuck in restarting.

![screenshot 2016-10-27 21 51 10](https://cloud.githubusercontent.com/assets/11735738/19783078/c364de98-9c90-11e6-96ab-96e019c152cd.png)

### Steps to Reproduce

Run latest storjshare GUI

### Logs

[log.zip](https://github.com/Storj/storjshare-gui/files/556881/log.zip)

**Comment by littleskunk** [comment]
Clock out of Sync. You are able to connect because the timeout is 15 sec but you will never receive any contracts because that timeout is only 5 seconds. -> Restart every 15 minutes.

```
{info} [Thu Oct 27 2016 12:29:46 GMT+0200 (W. Europe Daylight Time)] clock is synchronized with ntp, delta: 6991
[...]
{info} [Thu Oct 27 2016 19:07:46 GMT+0200 (W. Europe Daylight Time)] clock is synchronized with ntp, delta: 7561
```

I will use this issue for a tiny pull request. I would like to see the restart message on the logfile.

**Comment by MeijeSibbel** [comment]
It would be cool to add a feature where you get a warning when your clock is out of sync.

**Comment by littleskunk** [comment]
@MeijeSibbel https://github.com/Storj/core/issues/521
