### ISSUE TITLE
Check ntp delta only once

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#423]
### Versions

Replace the values below with your own:

Storj Share 2.0.14
Core Library 4.1.0
Protocol 0.9.1
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

CLI will check ntp delta on startup. Once synced the clock should be fine for the next few hours / days.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

We check ntp delta every 5 seconds. We even check the clock while the farmer has to deal with heavy load, 100% upload or download.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start GUI node and keep it running for an hour

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by artos60** [comment]
1 GUI instance 2 drives ->
just after sync
500 gb drive has ntp, delta: 29
8 tb drive has ntp, delta: 3340
screenshot: http://i.imgur.com/cyGDZ4d.jpg

**Comment by CJClaude** [comment]
Example:  http://puu.sh/rXSM6/81b6d31af2.png

**Comment by ruisilva93** [comment]
I'm having it on macOS Sierra 10.12.1 too
<img width="423" alt="screenshot 2016-10-28 00 05 17" src="https://cloud.githubusercontent.com/assets/22933729/19789708/e50b8cf4-9ca9-11e6-821c-05a4d694d55f.png">
