### ISSUE TITLE
Online port checker

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#425]
### Versions

Replace the values below with your own:

Storj Share 2.0.15
Core Library 4.1.0
Protocol 0.9.1
### Expected Behavior

Please describe the program's expected behavior.

I have a bad config. I set a puplic ip but missed the port forwarding. I would like to get an error message. Simple solution would be a online port checker. A better solution would be a probe message because even if the online port checker is working that doesn't mean my port forwarding rule hit the correct system. Maybe I am running it on 2 machines. The online port checker would only find the open port but can't find out which instance it is. The probe message could check the correct instance.
### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

I am able to connect to the network but I will never receive any messages. Endless restart loop. 
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. Start GUI and set a wrong external IP
### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Perfect solution would be https://github.com/Storj/core/issues/535

**Comment by bookchin** [comment]
Closes this in favor of  https://github.com/Storj/core/issues/535
