### ISSUE TITLE
Windows 64bit binary

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#428]
Some user are running Storjshare-gui with more than 20 drives. Each drive will require at least 50MB RAM and sometimes up to 500MB RAM. If they are unlucky they get activity on all 20 drives at the same time and hit the 32bit memory limit.

64bit binary would allow them to run so many drives at the same time without WSOD. I did a short test on my build system. I can build a 64bit binary very easy. The only problem is the wrong installation path and my build system would have to build 32 and 64bit binary. Possible but would require autobin modification.

http://stackoverflow.com/questions/13229212/how-to-detect-windows-32bit-or-64-bit-using-nsis-script

**Comment by super3** [comment]
64 bit binary would be nice if it was not too much work.

**Comment by super3** [comment]
@littleskunk Should this exist as an issue on autobin instead of storjshare-gui?

**Comment by littleskunk** [comment]
Both is needed. https://github.com/Storj/storjshare-gui/blob/master/resources/windows/installer.nsi#L47 C:\Program Files (x86)\ is the wrong directory for a 64bit binary.

I think that is the only change we need here.

Everything else should be autobin https://github.com/Storj/autobin/issues/17

**Comment by axiomfinity** [comment]
2.0.17 wsod after update this evening 

![screenshot from 2016-11-01 17-51-40](https://cloud.githubusercontent.com/assets/3162347/19913021/19ede722-a05c-11e6-9456-601971a2e65e.png)

**Comment by littleskunk** [comment]
@axiomfinity and how should a windows 64 bit binary help you on ubuntu?

**Comment by littleskunk** [comment]
Next GUI release will be available as 32bit and 64bit binary.

I have to reopen this issue to check the storj.io page.

**Comment by littleskunk** [comment]
storj.io will link to win32.exe: https://github.com/phutchins/smartypants/blob/5a1dfaeb548311847eeae85498f9dbc7d5960b33/app/routes/release.js#L36
