### ISSUE TITLE
2.0.16 gui becomes none responsive 

### ISSUE THREAD

**Issue by axiomfinity** [Storj/storjshare-gui#430]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.16
- **Operating System:** Ubuntu 16.04

### Expected Behavior

Please describe the program's expected behavior.
2.0.16 gui becomes none responsive requiring a restart/reload 

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by axiomfinity** [comment]
The menu bar is active, but cannot activate option on click

**Comment by simernes** [comment]
I have the same issue. When trying to reload after this the GUI stays white and an actual restart of the app is needed.

**Comment by littleskunk** [comment]
Logfile and screenshot please. Anything error messages on the developer console?

**Comment by littleskunk** [comment]
Please try again with GUI v2.0.17
