### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#431]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.16
- **Operating System:** windows 10

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

[log.zip](https://github.com/Storj/storjshare-gui/files/562978/log.zip)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

![screenshot4](https://cloud.githubusercontent.com/assets/11735738/19873590/2cf2bea2-9fc0-11e6-80f7-e8a6972eb779.png)

**Comment by littleskunk** [comment]
Must be a problem with core tunnel client. Please reopen the issue here: https://github.com/Storj/core/issues
The stacktrace will be very helpfull. Please plain text and not as screenshot.

**Comment by MeijeSibbel** [comment]
@littleskunk : https://github.com/Storj/core/issues/538
