### ISSUE TITLE
Peer count increases but nothing happens due to: No open ports + NAT traversal unsuccessful 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#432]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.16
- **Operating System:** windows 10
### Expected Behavior

Peer count increases only if the node is actually connected to the network and is able to download shards, this is not the case.

### Actual Behavior

Normally one would expect that with more peers comes more connections to the network and thus there is a higher chance a shard will find it's way to my machine. Unfortunately most of the times i start the GUI it starts at a few peers, something like 3-4, but it does not download any shards, then over the next few days running the GUI it can go up to 50 peers, without having downloaded a single shard in all this time!. Now my CLI on the same machine says that i have no open ports and that NAT traversal strategies failed, so the CLI just stops, i would expect the GUI  to do the same thing, yet it does not, as it still finds pees, but that's about it, it will never get any data. In my opinion the GUI should only start successfully if it can actually download or upload anything to or from the network. this is not the case. So a feature that checks if the node can actually reach the network would be handy, like: https://github.com/Storj/storjshare-gui/issues/425
Or just send a error message that it cannot to the network. With this you will create frustrated people that think their GUI is working as they see they have peers, but actually their GUI will not do anything at all except changing the peer count.

### Steps to Reproduce

1. Run the GUI
2. It fails to reach the node (no ports open) + NAT traversal failed
3. Peer count will continuously increase but nothing is downloaded or uploaded
4. It will reach 40-50 peers after a few days with 0 data used
5. Totally confusing to users, why is my GUI not working!!.

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Logfile please.

**Comment by MeijeSibbel** [comment]
@littleskunk : [log.zip](https://github.com/Storj/storjshare-gui/files/563850/log.zip)

**Comment by littleskunk** [comment]
Ports are open. I can see incoming PUBLISH messages.

```
{info} [Tue Nov 01 2016 11:03:59 GMT+0100 (W. Europe Standard Time)] received valid message from {"userAgent":"4.1.0","protocol":"0.9.1","address":"STORJ-CLUS-061.storj.space","port":4000,"nodeID":"3d1fb3d869aa2d36ab51b58ffbd90ff3ef27d766","lastSeen":1477994639563}
{info} [Tue Nov 01 2016 11:03:59 GMT+0100 (W. Europe Standard Time)] sending PUBLISH message to {"userAgent":"4.1.0","protocol":"0.9.1","address":"storj.uk","port":32603,"nodeID":"3ca1d57bafa4fcd6fbea09e1257627104075cd6e","lastSeen":1477994639625}
{info} [Tue Nov 01 2016 11:03:59 GMT+0100 (W. Europe Standard Time)] sending PUBLISH message to {"userAgent":"4.0.2","protocol":"0.9.0","address":"39.109.169.182","port":38583,"nodeID":"3b5128f116c8f7fe7d33447635ddac86b9349618","lastSeen":1477994639676}
{info} [Tue Nov 01 2016 11:03:59 GMT+0100 (W. Europe Standard Time)] received valid message from {"userAgent":"4.1.0","protocol":"0.9.1","address":"STORJ-CLUS-110.storj.space","port":4000,"nodeID":"381642e10b2db1f78afcffe29276ab0ef84cfb1b","lastSeen":1477994639744}
{info} [Tue Nov 01 2016 11:03:59 GMT+0100 (W. Europe Standard Time)] sending PUBLISH message to {"userAgent":"4.1.0","protocol":"0.9.1","address":"storj.uk","port":32603,"nodeID":"3ca1d57bafa4fcd6fbea09e1257627104075cd6e","lastSeen":1477994639800}
{info} [Tue Nov 01 2016 11:03:59 GMT+0100 (W. Europe Standard Time)] sending PUBLISH message to {"userAgent":"4.1.0","protocol":"0.9.1","address":"STORJ-CLUS-061.storj.space","port":4000,"nodeID":"3d1fb3d869aa2d36ab51b58ffbd90ff3ef27d766","lastSeen":1477994639848}
{info} [Tue Nov 01 2016 11:03:59 GMT+0100 (W. Europe Standard Time)] sending PUBLISH message to {"userAgent":"4.0.2","protocol":"0.9.0","address":"39.109.169.182","port":38583,"nodeID":"3b5128f116c8f7fe7d33447635ddac86b9349618","lastSeen":1477994639895}
```

**Comment by littleskunk** [comment]
I don't see any OFFER message on your log. Please switch to loglevel debug and restart the GUI. Keep it running for a few minutes. 15 Minutes should be enough. Upload the new logfile please. It should show us why you don't send any OFFER.

**Comment by MeijeSibbel** [comment]
@littleskunk ,Here is a logfile for the last few hours, i must admit that i haven't had the issue described in this topic for the last few hours so tomorrow i will upload a new log if it surfaces again, however, a few errors did occur that might me present in the logfile and could help you, so i will upload it anyway.  
[logs.zip](https://github.com/Storj/storjshare-gui/files/565164/logs.zip)

**Comment by littleskunk** [comment]
That logfile is looking fine. Still sending OFFER. Everything as expected. Lets give it more time.

**Comment by MeijeSibbel** [comment]
[log.zip](https://github.com/Storj/storjshare-gui/files/565224/log.zip)

**Comment by littleskunk** [comment]
Moved to https://github.com/Storj/core/issues/539

Workaround: Open a port to avoid tunnel connection.

**Comment by ruisilva93** [comment]
[Log.zip](https://github.com/Storj/storjshare-gui/files/567900/Log.zip)
