### ISSUE TITLE
Lots of peers, zero contracts

### ISSUE THREAD

**Issue by CJClaude** [Storj/storjshare-gui#433]
### Versions

Replace the values below with your own:

- **GUI Version:** v2,0.16
- **Operating System:** Windows 7 - 64 bit

### Expected Behavior

Contracts should be awarded.

```

```

### Actual Behavior

Started clean with a new disk definition on V16.  Noticed increasing peer counts but zero contract activity.  Have restarted several times over the past couple of days.  Currently at 38 peers, 0 contracts, and 367 BYTES of storage used.  Ports checked and open (pspoe.carpenter-farms.us port 4100).  0 tunnels specified.

http://puu.sh/s2frN/6320585aae.jpg

Logs below:

[StorjDrive-8f5c4b_2016-10-31.zip](https://github.com/Storj/storjshare-gui/files/563030/StorjDrive-8f5c4b_2016-10-31.zip)

FWIW, I've received hundreds of gigabytes of shards via my CLI instanances during this time.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
I don't see any PUBLISH messages on your logfile. There must be any other firewall still blocking the traffic. The port scanner is not able to detect that.

**Comment by CJClaude** [comment]
That would explain it, except everything looks setup correctly...

http://puu.sh/s2Ln4/519ea44929.png

http://puu.sh/s2Lrx/44898d3158.png

And I verified the Windows IP address of 10.184.155.202:

http://puu.sh/s2LuC/a99b3998a0.png

I was surprised that Storj has not listed in the Windows list of programs.  Also... this setup worked prior to version 14 (or 15, both of which had their own issues).

Hmmm, this is interesting... Its not listed, but if I try to add it, it claims its already on the list.

**Comment by littleskunk** [comment]
The wrong name is fixed with https://github.com/Storj/storjshare-gui/issues/353 but will not effect old firewall rules.

pspoe.carpenter-farms.us = 66.128.118.37
is that your external ip?

**Comment by CJClaude** [comment]
Yes, 66.128.118.37 is pspoe.carpenter-farms.us, the pfsense firewall whose screenshots I posted.

**Comment by CJClaude** [comment]
Stupid user error, transposed two letters in my public IP setting and didn't catch it.
