### ISSUE TITLE
Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#434]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.16
- **Operating System:** Windows 10

### Expected Behavior

clicking on 'Reload' successfully reloads the GUI.

### Actual Behavior

clicking on 'Reload' results in a WSOD.

[log.zip](https://github.com/Storj/storjshare-gui/files/563892/log.zip)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Unknown.

### Screenshots (Optional)

![screenshot](https://cloud.githubusercontent.com/assets/11735738/19888597/de056be4-a02f-11e6-99b5-7426c7bad9b1.png)

**Comment by littleskunk** [comment]
Looks like an Electron bug. Please try it again with the new binary I send you on slack. It is the same version but compiled with nodejs v6.9.1. The old binary is compiled with v4.6.0

**Comment by littleskunk** [comment]
Should be fixed with GUI v2.0.17
