### ISSUE TITLE
Failed to collect telemetry data

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#435]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.16
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
No errors.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Failed to collect telemetry data
```

Log: 
[logs.zip](https://github.com/Storj/storjshare-gui/files/564930/logs.zip)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run storjshare long periods of time.
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 

![2016-11-01 1](https://cloud.githubusercontent.com/assets/11735738/19905007/45b8720a-a075-11e6-9c60-4efce0552c5a.png)

**Comment by littleskunk** [comment]
More or less expected. You are connected via fallback tunnel connection and from time to time you lose your tunnel connection and start finding a new tunnel. This will effect the contact information the telemetry reporter would like to send.

Open a port should fix it.
