### ISSUE TITLE
No increase of shards on last 3 days

### ISSUE THREAD

**Issue by brizio1971** [Storj/storjshare-gui#436]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.16
- **Operating System:** Windows 10 64 bit

### Expected Behavior

Please describe the program's expected behavior.

Increasing of shards

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

No increase of shards on last 3 days, I have at least 7 peer connected, I attach the last log file
[StorjDrive-81aad0_2016-11-1.zip](https://github.com/Storj/storjshare-gui/files/565182/StorjDrive-81aad0_2016-11-1.zip)

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Node is running fine
`{info} [Tue Nov 01 2016 23:12:58 GMT+0100 (ora solare Europa occidentale)] sending OFFER message to {"userAgent":"4.1.0","protocol":"0.9.1","address":"104.196.152.206","port":8462,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1478038378662}`
