### ISSUE TITLE
javascript erro

### ISSUE THREAD

**Issue by allx1** [Storj/storjshare-gui#437]
### Versions

Replace the values below with your own:

- **GUI Version:** latest
- **Operating System:** Win 7 64bit

### Expected Behavior

Please describe the program's expected behavior.

n-a

### Actual Behavior

driveshare does not start due to the JavaScript error

### Steps to Reproduce

![java](https://cloud.githubusercontent.com/assets/17143942/19924857/046cb97c-a0ee-11e6-9b78-2daf0abc8040.jpg)

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Config file corrupted.
