### ISSUE TITLE
Not able to define UDP ports in Storj Share GUI

### ISSUE THREAD

**Issue by darkbluelight** [Storj/storjshare-gui#438]
### Versions

Storj Share 2.0.17
Core Library 4.1.0
Protocol 0.9.1

- **Operating System:** debian stretch, Kernel 4.6.0.1-amd64

### Expected Behavior

To be able to define what UDP ports Storj Share should use, so that I can open them in the firewall.
But the GUI allows only to define TCP ports.

### Actual Behavior
My Gufw Firewall 16.10.0 shows me that Storj tries to establish a connection on UDP 37243, UDP 41919, UDP6 39995, UDP6 42644, but those are all blocked by the firewall.

In the advanced settings-->Network Drive I defined TCP port 36901 and put NAT traversal strategies to "yes". With "no" Storj hangs forever in "preparing" state.
In Tunnels Drive I defined "Number of tunnel connections other farmers can open through you" to 3
TCP port number the tunnel should use to 42517
Start TCP port tunnel connections to 45984 and End to 45986.

If I restart Storj then other UDP ports will be used by Storj, so I would have to open those new ports again.

### Steps to Reproduce

Start Storj an watch the firewall logs.

**Comment by bookchin** [comment]
Storj Share itself does not use UDP, those ports are bound by the Electron framework for IPC, which we have no control over. They do not need to be exposed to the internet (and it's probably best they are not).

**Comment by darkbluelight** [comment]
Ok, thx for the answer. From a user perspective not a nice thing to have, but I can live with it.
