### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by digidan** [Storj/storjshare-gui#441]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.17
- **Operating System:** OS X 10.12.1

### Expected Behavior

Program will continue to get peers, shard, and use disk space, managing open file limits for relevant OS/File system

```

```

### Actual Behavior

After extended use the problem of too many files being open throws the error "contracts.db: Too many open files" in the logs (not in the UI any more).

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run stojshare app
2. acquire peers, contracts, shards, data
3. after several hours of operation the logs show the error drive path:
![screen shot 2016-11-05 at 10 21 13 am](https://cloud.githubusercontent.com/assets/8356662/20031199/a402e024-a341-11e6-8952-25b9dfb09d31.png)
contracts.db: Too many open files

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by digidan** [comment]
Unsure if its related but I’m also gettting this {error} [Sat Nov 05 2016 16:02:06 GMT-0500 (CDT)] Could not get usedSpace: IO error: lock /Volumes/MyBook/Storj/storjshare-f05727/sharddata.kfs/000.s/LOCK: already held by process

**Comment by bookchin** [comment]
Try increasing your system's maximum open files: http://ss64.com/bash/ulimit.html

**Comment by digidan** [comment]
I'm also getting this error.  While I appreciate the instructions for increasing the systems maximum open files, I shouldn't have to change OS native constraints and for most end users this could be risky if they don't know what they are doing.  There may be reasons for this limit in OS X and other platforms that need to be taken into consideration before removing limits just to get around an error.    It could have unforeseen performance or stability issues.  Is there no way for the app to negotiate this via a different method?

**Comment by digidan** [comment]
Here is the latest version of the error from the logs:
{error} [Mon Nov 14 2016 13:27:57 GMT-0600 (CST)] Could not get usedSpace: IO error: /Volumes/MyBook/Storj/storjshare-0933a1/sharddata.kfs/005.s/LOCK: Too many open files
{error} [Mon Nov 14 2016 13:29:37 GMT-0600 (CST)] Could not get usedSpace: IO error: /Volumes/MyBook/Storj/storjshare-0933a1/sharddata.kfs/008.s/MANIFEST-000055: Too many open files

**Comment by krilson** [comment]
The same as this error in storjshare-cli:

https://github.com/Storj/storjshare-cli/issues/206

**Comment by digidan** [comment]
still getting this in the latest version of Storj Share Gui as of 12/11/16

**Comment by lunokhod** [comment]
This is still happening on my system [osx]
```
StorjShare: 9.0.5
Core:       6.0.8
Protocol:   1.0.0
```

**Comment by arruah** [comment]
Same issue. 
Ubuntu 16.04
{error} [Tue Dec 13 2016 22:12:12 GMT+0600 ()] Could not get usedSpace: IO error: /media/kamrenov/other/storj/storjshare-20a170/sharddata.kfs/236.s/CURRENT: Too many open files
{error} [Tue Dec 13 2016 22:12:12 GMT+0600 ()] Could not get usedSpace: IO error: /media/kamrenov/other/storj/storjshare-20a170/sharddata.kfs/236.s/CURRENT: Too many open files
{error} [Tue Dec 13 2016 22:12:12 GMT+0600 ()] Could not get usedSpace: IO error: /media/kamrenov/other/storj/storjshare-20a170/sharddata.kfs/236.s/CURRENT: Too many open files
{error} [Tue Dec 13 2016 22:12:12 GMT+0600 ()] Could not get usedSpace: IO error: /media/kamrenov/other/storj/storjshare-20a170/sharddata.kfs/236.s/CURRENT: Too many open files
{error} [Tue Dec 13 2016 22:12:12 GMT+0600 ()] Could not get usedSpace: IO error: /media/kamrenov/other/storj/storjshare-20a170/sharddata.kfs/236.s/CURRENT: Too many open files
{error} [Tue Dec 13 2016 22:12:12 GMT+0600 ()] Could not get usedSpace: IO error: /media/kamrenov/other/storj/storjshare-20a170/sharddata.kfs/236.s/CURRENT: Too many open files
{error} [Tue Dec 13 2016 22:12:12 GMT+0600 ()] Could not get usedSpace: IO error: /media/kamrenov/other/storj/storjshare-20a170/sharddata.kfs/236.s/CURRENT: Too many open files

**Comment by scottbourne** [comment]
I'm running the 4.0.10 client and am having the same problem:

{error} [Sat Feb 18 2017 10:19:57 GMT-0800 (PST)] Could not get usedSpace: IO error: /home/anonymous/Documents/Storj1-10gb/storjshare-ce5fe1/sharddata.kfs/251.s: Too many open files
{debug} [Sat Feb 18 2017 10:19:57 GMT-0800 (PST)] not sending an offer for the contract
{error} [Sat Feb 18 2017 10:19:57 GMT-0800 (PST)] Could not get usedSpace: IO error: /home/anonymous/Documents/Storj1-10gb/storjshare-ce5fe1/sharddata.kfs/251.s: Too many open files
{debug} [Sat Feb 18 2017 10:19:57 GMT-0800 ()] not sending an offer for the contract
{error} [Sat Feb 18 2017 10:19:57 GMT-0800 ()] Could not get usedSpace: IO error: /home/anonymous/Documents/Storj1-10gb/storjshare-ce5fe1/sharddata.kfs/251.s: Too many open files
{debug} [Sat Feb 18 2017 10:19:57 GMT-0800 ()] not sending an offer for the contract
{error} [Sat Feb 18 2017 10:19:57 GMT-0800 ()] Could not get usedSpace: IO error: /home/anonymous/Documents/Storj1-10gb/storjshare-ce5fe1/sharddata.kfs/251.s: Too many open files
{debug} [Sat Feb 18 2017 10:19:57 GMT-0800 ()] not sending an offer for the contract
{error} [Sat Feb 18 2017 10:19:57 GMT-0800 ()] Could not get usedSpace: IO error: /home/anonymous/Documents/Storj1-10gb/storjshare-ce5fe1/sharddata.kfs/251.s: Too many open files
{debug} [Sat Feb 18 2017 10:19:57 GMT-0800 ()] not sending an offer for the contract
{error} [Sat Feb 18 2017 10:19:57 GMT-0800 ()] Could not get usedSpace: IO error: /home/anonymous/Documents/Storj1-10gb/storjshare-ce5fe1/sharddata.kfs/251.s: Too many open files
{debug} [Sat Feb 18 2017 10:19:57 GMT-0800 ()] not sending an offer for the contract

**Comment by littleskunk** [comment]
Should be solved in 4.1.0. We have one last issue that we will track in https://github.com/Storj/core/issues/666
