### ISSUE TITLE
No contracts/shards

### ISSUE THREAD

**Issue by digidan** [Storj/storjshare-gui#443]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.17
- **Operating System:** OSX 10.12.1

### Expected Behavior

Program will run and get contracts, shards, and use disk space

```

```

### Actual Behavior

Program continues to get peers, up to 50+ but never gets another contract or shard. Don't see any major errors in the logs or issues with connectivity. 

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...Start Storj
2. ...Storj starts to acquire peers
3. ...Numbers of Contracts or disk space used never changes

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Without any logfile we are not able to help you. -> Closed

Check your logfile for ntp delta and make sure ports are open. See https://storj.readme.io/docs/storjshare-troubleshooting-guide for more details.

**Comment by digidan** [comment]
Sorry I was having a problem with attachments.  Hopefully you can reopen.
[StorjDrive-f05727_2016-11-7.txt](https://github.com/Storj/storjshare-gui/files/576536/StorjDrive-f05727_2016-11-7.txt)


![screen shot 2016-11-07 at 2 07 31 pm](https://cloud.githubusercontent.com/assets/8356662/20073854/8d5774ee-a4f3-11e6-8d89-c0aafe4fab14.png)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/539
