### ISSUE TITLE
Shared folder path location displayed

### ISSUE THREAD

**Issue by busigkille** [Storj/storjshare-gui#446]
Could the shared folder path be displayed in the UI? Maybe under allocated space.

Me for instance have many HDD dedicated and would help if it the path would be displayed somewhere.

**Comment by digidan** [comment]
One thing I'm noticing is mapped drives do not show in the Windows 10 path browser in the gui.  This often causes the invalid location/path error.

**Comment by bookchin** [comment]
Done in `next`
