### ISSUE TITLE
`Invalid storage size` if disk space already shared

### ISSUE THREAD

**Issue by ComiR** [Storj/storjshare-gui#447]
### Versions
 ```
Storj Share 3.0.1
Core Library 5.0.1
Protocol 0.10.0
```
**Operating System:** Windows 10

### Expected Behavior

Normal startup

### Actual Behavior

`Invalid storage size` popup.

### Steps to Reproduce
1. Set up a partition with size 100GB
2. Share 75GB
3. Wait until >25GB are used by the share
4. Try to restart sharing the 75GB.

**Comment by busigkille** [comment]
Can confirm this. There is definetly something fishy here.

**Comment by digidan** [comment]
I'm having this on my OS X instance as well, its not a pop up but is in the logs, along with the too many files open error right after.

**Comment by bookchin** [comment]
You can only have one share per disk as there is a lock on the shard database and contracts

**Comment by ComiR** [comment]
@bookchin you got it wrong. I don't want to start another instance. I want to start the same share (quit and start, i.e. a reboot).
Perhaps there is a lock not properly removed (f.e. due to a system crash), but there is only one share and instance.

**Comment by littleskunk** [comment]
@ComiR Windows problem. See https://github.com/Storj/storjshare-gui/issues/427#issuecomment-262715621
