### ISSUE TITLE
Win7GUI: Starts older version

### ISSUE THREAD

**Issue by WilhelmGGW** [Storj/storjshare-gui#448]
StorjShare GUI v3.0.1

Windows 7

Expected Behavior
Once installed, program should launch from icon into the present version.

Actual Behavior
When launching duly installed program from icon, it somehow starts in v2.0.17 and presents the upgrade option window.  If I ignore the upgrade and launch the program, Help > About Storj Share says I'm using v2.0.17

The only way I can get the farmer to load into the present version 3.0.1 is to reinstall it. Then when I close the installation window, it starts and runs as it should in the current version.

However, if I exit the 3.0.1 that's running fine, and attempt to restart it normally from the icon, it will go right back to starting and running v2.0.17.

**Comment by littleskunk** [comment]
32 bit and 64 bit binaries have different Installation Folders. You have both Versions installed. Uninstall the old 32 bit Version (don't delete AppData content) and install the new 64 bit Version again. That should fix everything.
