### ISSUE TITLE
Severe *Memory Leak* Causing System Crash

### ISSUE THREAD

**Issue by WilhelmGGW** [Storj/storjshare-gui#450]
GUI v3.0.1
Windows 7

Expected Behavior
StorjShare should run for extended periods of time without problem.

Actual Behavior
     After starting my 22 nodes - total of core and on 2 external drives - I can watch the [Resource Monitor] Used Physical Memory gradually rise from about 35% to 70+% - during which time all nodes perform as expected.
     Within a few hours from starting, and after Used Physical Memory has maxed out, the registry of Hard Faults begins increasing quickly. If I'm not at hand to catch this situation and restart StorjShare and all the nodes, my core hard drive begins thrashing more and more extremely, till my hard drive stops and the system crashes.
     This process occurs each and every time, with every restart of StorjShare.

Of course I have no logs or screenshots to present, as all instances end in fatal crashes that abort logs and offer only the system Black Screen of Death.

Most recent occurrence, as reported on RocketChat: "I knew I was getting a flood of data yesterday. So last evening I did my memory purge and started only half my nodes, hoping the leakage wouldn't flood and kill my system overnight. To no avail. I woke up to find my computer (and all nodes) entirely crashed, dead and shut down! This is a _Serious Restriction_ of my contribution to the network."

This morning, on my first restart of all 22 nodes, I caught the Hard Faults beginning to jump and had to restart - Just Three Hours after starting!

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-cli/issues/204

BTW: You can always cause a OutOfMemory exception by adding more and more drives. If you can reproduce it with only one a few drives we can give this issue a higher priority.
