### ISSUE TITLE
Reducing allocated space when already using 100% of space

### ISSUE THREAD

**Issue by enzo2** [Storj/storjshare-gui#451]
### Versions

Replace the values below with your own:

- **GUI Version:** v3.0.1
- **Operating System:** Win7 64

### Expected Behavior
If one needs additional drive space, should be able to reduce the amount of space used within a reasonable time period. 

### Actual Behavior
Upon reducing the allocated space for a drive which is already at 100% space utilization, files are not deleted to free up space as requested. Have waited at least a few days but no change. 
In my case the used space was actually >100% (430GB/400GB). I then lowered to 300GB. 

### Steps to Reproduce
1. Fill to 100% used space
1. Reduce allocated space

**Comment by dlmac** [comment]
I also have this same issue
![image](https://cloud.githubusercontent.com/assets/372043/20332273/a3bb1728-ab78-11e6-930c-c66019e76527.png)

**Comment by littleskunk** [comment]
"If one needs additional drive space, should be able to reduce the amount of space used within a reasonable time period."

You have signed a 90 day contract for each shard. If you need more space now you shouldn't sign them in the first place. Now you would like to break 25% of the contracts? I don't think we will implement that. If you do it a few times no renter will trust you anymore. -> No more shards are comming in even if you have free space.

Solution: You did it correct. Reduce the free space and wait for expired contracts. On the first run this will take 90 days. Later the expired contracts will be replaced one by one. I would expect 400 GB / 90 days = ~ 4GB per day. It would take 25 days to reduce the used space but this time without breaking any signed contract.

Note: At the moment we have only 3 default opcodes implemented. All with 90 days duration. Later we would like to add more opcodes. If you need more dynamic used space you could go for low duration opcodes. This would allow you to reduce the used space faster.
