### ISSUE TITLE
Freeze (no response)

### ISSUE THREAD

**Issue by jurjendevries** [Storj/storjshare-gui#452]
### Versions

Replace the values below with your own:

- **GUI Version:** v3.0.1
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Responding to input (menu items / buttons, etc) and actual last activity date/time.

### Actual Behavior
After some time (sometimes a few seconds, another time hours) the GUI doesn't respond anymore. In version 2.x (last month) the whole GUI gets white, now it freezes and is not responding to any input, and no changes in peers/contract/last activity/used space fields.

Note. I have one drive configured.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start GUI with screen in foreground
2. Wait till there isn't activity for a long time. Then click menu items / buttons. No response.

### Screenshots (Optional)
![storj-white](https://cloud.githubusercontent.com/assets/355488/20323361/a22fcd82-ab7c-11e6-84d1-7f63e3a49005.png)
This screenshot was in latest 2.x versions. Since 3.0 it doesn't get white anymore.

**Comment by littleskunk** [comment]
Which linux desktop manager do you use?

**Comment by jurjendevries** [comment]
@littleskunk The default Ubuntu 14.04, I guess that is Unity?

**Comment by FreeBeer86** [comment]
Same issue on Ubuntu Mate 16.04. The Gui becomes unresponsive. I need to reboot to regain functionality.

**Comment by littleskunk** [comment]
New GUI release published. If you get the problem again please open a new issue.
