### ISSUE TITLE
StorjShare uses space beyond what is allocated

### ISSUE THREAD

**Issue by dlmac** [Storj/storjshare-gui#453]
### Versions

Replace the values below with your own:

- **GUI Version:** v3.0.1
- **Operating System:** Windows 10

### Expected Behavior

StorjShare should stop using space beyond allocated

### Actual Behavior

Continues to use space until completely gone

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 
![image](https://cloud.githubusercontent.com/assets/372043/20332340/0763f88a-ab79-11e6-93c6-555923aba907.png)

**Comment by littleskunk** [comment]
Windows reports the used space wrong. You set 900 GB * 1024^3 = 966367641600 Bytes. Windows calculates with 1000 and displays 967 GB.
