### ISSUE TITLE
Arch (Antergos) Install Failure on appdmg

### ISSUE THREAD

**Issue by arpee** [Storj/storjshare-gui#456]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** Antergos (Gnome)

### Expected Behavior

npm install should complete

### Actual Behavior

Install fails with error:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@^0.3.2 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.3.10: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

Attempting to install appdmg produces:

```
npm ERR! Linux 4.8.8-2-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "appdmg"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for appdmg@0.3.10: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/richardp/Downloads/software/storjshare/storjshare-gui/npm-debug.log

```

### Steps to Reproduce

1. npm install

Error.
[npm-debug.zip](https://github.com/Storj/storjshare-gui/files/608005/npm-debug.zip)

**Comment by bookchin** [comment]
That's okay, you just cannot build a OSX package.

**Comment by arpee** [comment]
Gordon hall - the answer is that you do not support any other OS?

Richard

**Comment by arpee** [comment]
Gordon - not sure if clear from my email - the whole install is failing for me on this bug.

I am stepping through the read me and running:

```
git clone https://github.com/Storj/storjshare-gui.git && cd storjshare-gui
npm install
```
is failing on the appdmg error. This will effect anyone attempting to install, as per the readme, on linux.

If that is not supported - it might be good to make it clear.

Richard

**Comment by littleskunk** [comment]
@arpee You cannont build a OSX binary on Linux. That is the reason appdmg is an optional dependency.

https://github.com/Storj/storjshare-gui/#prerequisites
You are using nodejs v7.1.0.

**Comment by bookchin** [comment]
@arpee gnu/linux is supported - i develop on Debian. If you can't get past the error during install, try:

```
npm install --no-optional
```

**Comment by arpee** [comment]
@littleskunk - thanks - i would have presumed that a listed prerequisite is a minimum version number.

@bookchin the  ``` --no-optiman ``` flag got the package installed. The application is now failing, but I have to put that down to me having a later version of node...
