### ISSUE TITLE
visual c++ issue

### ISSUE THREAD

**Issue by lyolyalya** [Storj/storjshare-gui#463]
- **GUI Version:** v4.0.5
- **Operating System:** Win 8.1x64

Starting today there is issue with visual c++ at startup guix64.
if i retry - then program shows white window.
if i ignore errors for a 10-15 times - then program starts as usual and nothing go wrong.i have contracts, peers and shards.no updates for windows, any programs not been installed during this time.

### Screenshots (Optional)
![clipboard](https://cloud.githubusercontent.com/assets/16507768/21146239/9cf0842c-c159-11e6-8db5-49b48a7d1bb2.png)

**Comment by littleskunk** [comment]
`R:\autobin...` is the path I am using on my build server. Maybe a Problem with 64bit openssl. It prints out a few warnings that could be the reason.

Please uninstall 64bit and try 32bit. Do you get the same error message?

**Comment by lyolyalya** [comment]
i'll try x32 little later but no problems for two weeks before with x64...

**Comment by lyolyalya** [comment]
nope.same error.same 10-15 ignores to start...

**Comment by littleskunk** [comment]
https://github.com/creationix/node-leveldb/blob/master/deps/leveldb/db/dbformat.h#L85-L97

It looks like a bad leveldb. What happens if you stop all drives (don't delete them) and start a new drive with a clean leveldb.

**Comment by lyolyalya** [comment]
yeah.new drive looks fine.no errors on start and have 4 contract already.what shoul i do with the old one?

**Comment by lyolyalya** [comment]
i migrated shards and contracts from old drive to new drive.but problem is still here.seems like there is corrupted shards or something.any thoughts?

**Comment by BernyMY** [comment]
I have the same problem. when i click ignore, the white screen keep pop ups, i have to click abort .

**Comment by littleskunk** [comment]
What I have to do to reproduce this? Kill the GUI? Hard reset? Power loss? How did you corrupt the leveldb?

We could try to repair it but that will take some time. For the moment add a new drive and and stop the corrupted one but don't delete it or the repair will be useless.

**Comment by BernyMY** [comment]
[storjshare-out-13whitescreen.txt](https://github.com/Storj/storjshare-gui/files/684284/storjshare-out-13whitescreen.txt)

**Comment by BernyMY** [comment]
i got this when i try to restart my pc. SOP, i shut down all nodes with pm2 stop, followed by pm2 delete all, and last pm2 flush. and Then i restart my comp. Then as usual, i restart all my nodes with pm2 resurrect.  And then this white screen popup.

**Comment by littleskunk** [comment]
@BernyMY 
```
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":15411401,\"address\":\"104.196.39.49\",\"port\":8466,\"nodeID\":\"ed97cb9fef2b72281c3b9d65440fae58a55a0295\",\"lastSeen\":1483522322290}","timestamp":"2017-01-04T09:32:02.290Z"}
{"level":"debug","message":"queuing callback for reponse to e3ce1ec927d4099450238209cba4ff95b316e4f9","timestamp":"2017-01-04T09:32:02.304Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":15411401,\"address\":\"104.196.39.49\",\"port\":8466,\"nodeID\":\"ed97cb9fef2b72281c3b9d65440fae58a55a0295\",\"lastSeen\":1483522322848}","timestamp":"2017-01-04T09:32:02.848Z"}
{"level":"debug","message":"updating contact {\"userAgent\":\"6.0.8\",\"protocol\":\"1.0.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":15411401,\"address\":\"104.196.39.49\",\"port\":8466,\"nodeID\":\"ed97cb9fef2b72281c3b9d65440fae58a55a0295\",\"lastSeen\":1483522322848}","timestamp":"2017-01-04T09:32:02.848Z"}
{"level":"debug","message":"checking pending rpc callback stack for e3ce1ec927d4099450238209cba4ff95b316e4f9","timestamp":"2017-01-04T09:32:02.850Z"}
```

You are sending an OFFER and the bridge send a resonse. I don't see the conten of the Response. I would expect a channel open or to late for offer message on the logfile. That is missing.

How about `storjshare-error-13`? pm2 should write the error and the stracktrace into that file. Please upload it as well.

**Comment by BernyMY** [comment]
@littleskunk pm2 error log is 0 file. i open it and it's empty

**Comment by super3** [comment]
@BernyMY Have you upgraded to storjshare-daemon?

**Comment by BernyMY** [comment]
i have figure out the real reason . Is my HDD problem. Bad HDD cause it

**Comment by BernyMY** [comment]
i'm still using CLI atm. I'll wait till daemon stable only installed it. As you know i'm not so good in this, so i prefer not to mess it up coz it'll cause me headache to fixed it when got problem. Since all running good atm, i'll just stick with CLI till Daemon is fully stable

**Comment by lyolyalya** [comment]
it was just bad node...i started new node on the same HDD in same folder and problem is gone...with my 330 gb of shards before christmas=)

**Comment by BernyMY** [comment]
your's maybe a bad node, but mine after scanning with hard disk sentinel, it shows my hdd health is bad. I guess is hardware issue. Even i start new nodes, the newly create nodes will soon have the same old white screen again after running for 2 days

**Comment by lyolyalya** [comment]
nope=)my new node rinning well 1 month already=)

**Comment by littleskunk** [comment]
Next time we can try to repair the leveldb. I found a way to do that. Complicated for GUI user but possible. No brainer for CLI user :)

**Comment by lyolyalya** [comment]
cli for me the same brainer=)
