### ISSUE TITLE
stop contract after upgrade 

### ISSUE THREAD

**Issue by tamchik** [Storj/storjshare-gui#464]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.0.5
- **Operating System: Windows 2008 R2 x64

### Expected Behavior

Please describe the program's expected behavior.

continuation of the rental space

### Actual Behavior

09.12 after the upgrade do not have new contracts, the counter is the number one contract and location is not changed on disk

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Logfile or it didn't happen :)

**Comment by tamchik** [comment]
big file

**Comment by littleskunk** [comment]
Zip it.

**Comment by tamchik** [comment]
ok

**Comment by tamchik** [comment]
when I add .ZIP file writes:
We don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

**Comment by tamchik** [comment]
File sharing: https://yadi.sk/d/vUX4wj9j33R7i8

**Comment by littleskunk** [comment]
Thank you. I will look into it at home.

**Comment by tamchik** [comment]
ok, thank you

**Comment by littleskunk** [comment]
```
{info} [Mon Dec 12 2016 12:24:03 GMT+0100 (W. Europe Standard Time)] clock is synchronized with ntp, delta: 4586
```

Please sync your clock with a good ntp time server.
