### ISSUE TITLE
no new contract after update

### ISSUE THREAD

**Issue by tamchik** [Storj/storjshare-gui#465]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.0.6
- **Operating System:** windows 2008 x64

### Expected Behavior

Please describe the program's expected behavior.

should be added to new contracts

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

after renovation 09.12.2016 no new contracts are added after the clock synchronization has not changed

log file in file share: https://yadi.sk/d/9QnDmIsD33Syhi

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
```
Line 869148: {error} [Wed Dec 14 2016 08:01:45 GMT+0100 (W. Europe Standard Time)] Could not get usedSpace: IO error: LockFile E:\StorjCOIN\storjshare-6a6a50\sharddata.kfs\001.s/LOCK: The process cannot access the file because it is being used by another process.
```

Duplicate https://github.com/Storj/kfs/issues/39
