### ISSUE TITLE
Not reporting telemetry data

### ISSUE THREAD

**Issue by WilhelmGGW** [Storj/storjshare-gui#467]
GUI Versions: v4.0.2-5
Operating System: Linux Mint 17 & Windows 7

Expected Behavior
Under Developer Tools > Console
There should be Success feedback on reports sent

Actual Behavior
Instead, line pairs like this are all that report
[telemetry] sending report Object client.js:504 
[telemetry] Error: Unknown error response(…) undefined

**Comment by WilhelmGGW** [comment]
Issue persists in GUI v4.0.6
Linux Mint 17 & Windows 7

**Comment by JHuppi** [comment]
Same but on macOS 10

**Comment by WilhelmGGW** [comment]
Here is a log in Debug mode that might show this behavior:
[StorjDrive-bac7a3_2016-12-16.txt](https://github.com/Storj/storjshare-gui/files/658895/StorjDrive-bac7a3_2016-12-16.txt)

**Comment by ayiphelmy** [comment]
![ntp](https://cloud.githubusercontent.com/assets/24635895/21294069/809c9a9c-c567-11e6-91b6-fcc2209e8fe5.jpg) ntp already sync but still an error on console
![storj1](https://cloud.githubusercontent.com/assets/24635895/21294072/9828c2a8-c567-11e6-96bb-9a85581f5a68.jpg)

**Comment by WilhelmGGW** [comment]
Issue persists in GUI v4.0.7&8
Linux Mint 17 & Windows 7

**Comment by super3** [comment]
The backend of storjshare-gui is going to be replaced with storjshare-daemon. I expect this issue to be fixed with #483

**Comment by bookchin** [comment]
This also looks like an issue with https://github.com/Storj/statusify - "unknown error response" indicates the telemetry server is not responding correctly, due to what is likely a bad payload being sent by the reporter.
