### ISSUE TITLE
Stays in state 'preparing'

### ISSUE THREAD

**Issue by jurjendevries** [Storj/storjshare-gui#468]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.0.5
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Having the Storj client active

### Actual Behavior

Screen shows 'preparing' for more then 24 hours, also after a restart of the computer, and update from version v4.0.4 to v4.0.5. So I have the problem since v4.0.4, where https://github.com/Storj/storjshare-gui/issues/452 was fixed.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start GUI with screen in foreground
2. You'll see preparing... and it stays in this state.
![storj-1](https://cloud.githubusercontent.com/assets/355488/21224244/7e983786-c2cb-11e6-8598-40648e3161ca.png)

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Logfile please

**Comment by jurjendevries** [comment]
@littleskunk I updated to v4.0.7 and now it's working. Can be closed.
