### ISSUE TITLE
Few contracts for the last 10 days

### ISSUE THREAD

**Issue by bebelu00** [Storj/storjshare-gui#475]
### Versions

Replace the values below with your own:

- **GUI Version:** 4.0.8
- **Operating System:** Win 7 x64 
 Protocol 1.0.0

### Expected Behavior

Please describe the program's expected behavior.
### Actual Behavior
For the last 10 or so days I'm getting very few contracts ... and the allocated space is stuck at 65% from 460gb . (peers 172 and contracts 78510)
Something wrong ? 

Also ... where should I ask about payments ? Haven't received even one storj coin so far . 

[StorjDrive-c8161f_2016-12-23.zip](https://github.com/Storj/storjshare-gui/files/671264/StorjDrive-c8161f_2016-12-23.zip)

**Comment by littleskunk** [comment]
http://community.storj.io/
