### ISSUE TITLE
warning before deleting drive?

### ISSUE THREAD

**Issue by lyolyalya** [Storj/storjshare-gui#477]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.0.8
- **Operating System:** Windows 8.1 х64

I deleted drive in gui by mistake without any knowing about private keys and other backup stuff.gui just asking me about deleting drive and that's all.
so would be nice to implement automatic backuping on drive deleting, or maybe some dialogbox with this option or whatever you can find useful and helpful to prevent those mistakes.cause i as a user don't know anything about all importance of this file on restoring shards and contracts.thanks.

**Comment by littleskunk** [comment]
New GUI 5.0.0 will keep the config.json file even if the drive was deleted.
Configs are stored in `%userprofile%\.config\storjshare\configs` / `~/.config/storjshare/configs`

I think we still need a warning but at least the private key is not lost.

**Comment by bookchin** [comment]
eeabd3c
