### ISSUE TITLE
StorJ with ARM cpu

### ISSUE THREAD

**Issue by matteoraggi** [Storj/storjshare-gui#479]
Hi, I would like to use Storj on raspberry pi 3 model B (arm 64 bit cpu), os raspbian 8 pixel.
Is that possible?

**Comment by littleskunk** [comment]
Yes that is possible.

**Comment by matteoraggi** [comment]
how?

**Comment by bookchin** [comment]
You'll need to use the CLI, electron doesn't support ARM to my knowledge.

**Comment by littleskunk** [comment]
GUI should support ARM as well. As far as I know there are already users running the GUI on a raspberry pi. The only problem is the binary we release. You have to install and build from source. Join us on https://community.storj.io/ and we will try to help you.

https://github.com/electron/electron/pull/2094
