### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by antogish** [Storj/storjshare-gui#480]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.08
- **Operating System:** Windows 10 Pro

### Expected Behavior

Please describe the program's expected behavior.

After install Storj starts.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

After install a popup windows states:

Error - A javascript error occured in the main process.
Uncaught Exception
SyntaxError: Unexpected token

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Uninstall old verison of Storj
Reboot
Install latest Storj version
Install completes and then error occurs as Storj tries to start
Have uninstalled and re-installed several times and error occurs every time.

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/476

(settings.json is located in %appdata%/Storj Share)
