### ISSUE TITLE
[telemetry] Speed test ended early

### ISSUE THREAD

**Issue by WorldOfGZ** [Storj/storjshare-gui#485]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.0.8
- **Operating System:** Windows 10

### Expected Behavior
Success feedback on reports sent

### Actual Behavior

On developper tools > Console, error reports
[telemetry] Error: connect ETIMEDOUT 104.196.133.93:80 client.js:524
[telemetry] Error: Speed test ended early at WebSocket.cleanup (C:\Program Files\Storj Share\resources\app\node_modules\myspeed\lib\client.js:39:16)

### Steps to Reproduce

Appear when click on "start" or when I click on Reload.

**Comment by littleskunk** [comment]
Belongs to https://github.com/Storj/storjshare-gui/issues/467
