### ISSUE TITLE
GUI causes GPU clock set to default.

### ISSUE THREAD

**Issue by lyolyalya** [Storj/storjshare-gui#486]
- **GUI Version:** v4.0.9
- **Operating System:** Win10x64

Have mining rig with 3x Nvidia GTX 1070 with OC.
starting storjshare gui causes my first GPU to set default GPU clocks.

**Comment by littleskunk** [comment]
Try to start the GUI with `--disable-gpu`

**Comment by lyolyalya** [comment]
how can i do that exactly? where i need to add this option?

**Comment by littleskunk** [comment]
`"C:\Program Files\Storj Share\Storj Share.exe" --disable-gpu`
