### ISSUE TITLE
GUI Screen Flicker

### ISSUE THREAD

**Issue by super3** [Storj/storjshare-gui#487]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

Program stays on preparing or goes to ready. 

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Stuck on Preparing and just flashing back and forth. 

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upgrade from previous Storjshare
2. Launch Storjshare

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 

![demo](https://cloud.githubusercontent.com/assets/60975/22743616/ad327bc2-ede8-11e6-9c76-ec3f98f4c3e1.gif)

**Comment by bookchin** [comment]
https://github.com/Storj/storjshare-gui/issues/484
