### ISSUE TITLE
GUI reported Used Space keep getting stuck

### ISSUE THREAD

**Issue by bathrobehero** [Storj/storjshare-gui#488]
### Versions
- **GUI Version:** v4.0.10
- **Operating System:** Windows 7 x64

### Expected Behavior
GUI reported Used Space to match actual space used on the drive.

### Actual Behavior
GUI reported Used Space is stuck (e.g. showing 300 MB instead of actual 2 GB). Restart fixes it (and shows 2GB).
Didn't notcie it with one drive but now with 18 drives I noticed it. Could be irrelevant.
Assuming Peers and Contracts were stuck as well, didn't check before restart.

### Steps to Reproduce
Run the GUI for longer periods of time.

**Comment by MandarKarhade** [comment]
I confirm. Data is getting added on the nodes but especially the nodes in the background do not update "used space" .. after restarting GUI the higher space usage is visible.
