### ISSUE TITLE
UNKNOWN: unknown error on Start

### ISSUE THREAD

**Issue by ckippen** [Storj/storjshare-gui#490]
### Versions

- **GUI Version:** v4.0.10
- **Operating System:** Windows 10

### Expected Behavior

GUI loads and automatically starts farming.

### Actual Behavior

GUI loads and the START button is visible with no error. Clicking Start displays an error message.
```
UNKNOWN: unknown error, lstat 'E:\Storj Share\storjshare-f4ac94\sharddata.kfs\115.s\000375.ldb'
```
Closed Storj Share completely and attempted:
```
kfs compact -d "E:\Storj Share\storjshare-f7ac94\sharddata.kfs"
```
115.s (done!), error persists.

### Screenshots (Optional)
 Log
[StorjDrive-f7ac94_2017-2-16.txt](https://github.com/Storj/storjshare-gui/files/782043/StorjDrive-f7ac94_2017-2-16.txt)

Error Message
![storj share_2017-02-16_19-25-23](https://cloud.githubusercontent.com/assets/24601549/23049307/dfd6281e-f480-11e6-9022-b84eb26f8100.png)

Rename/Copy Error
![explorer_2017-02-16_19-53-39](https://cloud.githubusercontent.com/assets/24601549/23049971/22bc5f5a-f485-11e6-96b7-85be62a4bb4e.png)

**Comment by littleskunk** [comment]
Please rename the folder and remove the space. That should fix it for now.

I found some informations about a nodejs bug. Nothing we can fix in a short time.

**Comment by littleskunk** [comment]
and how about Drive E. Is it a loca HDD or any remote network share?

**Comment by ckippen** [comment]
Local Disk
![dllhost_2017-02-17_17-54-15](https://cloud.githubusercontent.com/assets/24601549/23087453/29baaba8-f53a-11e6-8813-923c42a047f1.png)

**Comment by littleskunk** [comment]
Windows Error code `0x80070570` means that you somehow manage to destroy the file system or permission.

Please check your hard disk for errors and repair them.
