### ISSUE TITLE
GUI White Screen

### ISSUE THREAD

**Issue by bdg0296** [Storj/storjshare-gui#493]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.0.11
- **Operating System:** Windows 2012 R2

### Expected Behavior

The program should run and display the GUI

```

```

### Actual Behavior

I get a white screen randomly in the GUI the only way to fix is to go to view and reload

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... Can't reproduce it happens randomly 
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Are you using the 32 or 64 bit binary?

**Comment by littleskunk** [comment]
Was the old GUI version 4.0.10 or 4.0.9 running fine?

**Comment by bdg0296** [comment]
I am running the 64bit client. And the old version did the same. I've had the problem for the last few versions actually. I asked about it in the forum and was told to list it here

**Comment by littleskunk** [comment]
It looks like a electron issue and only windows is effected. I build 2 new binaries for windows 32 and 64 bit and uploaded them: https://github.com/Storj/storjshare-gui/releases/tag/v4.0.11

One binary for the latest stable electron version 1.4.15 and one for the latest beta version 1.6.1.

About Storj Share will now print out the electron and chrome version but only for the beta binary. The 1.4.15 binary has the old version output.
```
About Storj Share

Storj Share 4.0.11
Core Library 6.2.0
Protocol 1.1.0
Electron 1.6.1
Chrome 56.0.2924.87
```

Please try both binaries and let me know which version has a WSOD.

**Comment by bdg0296** [comment]
Thanks I will give them a try and report back

**Comment by littleskunk** [comment]
Because of a memory problem the 24 hour cleanup job can produce a WSOD. All 3 binaries should run into this problem.

I am more interested in any random WSOD. Rocket chat user meije still has some WSOD with all 3 electron versions. I will wait for your feedback just in case but it looks like the solution is not that simple.

**Comment by bdg0296** [comment]
Sounds good. Mine don't seem to be on any kind of pattern I can identify. I started running the 1.4.15 64bit version but have yet to get one. I have gone days and weeks with none then other times a couple times a day or week. I will keep monitoring and report back

**Comment by littleskunk** [comment]
New GUI release is published. The memory problem should be fixed now.

I updated to electron 1.4.15. That looks very stable. I included the electron version output just in case we have to repeat the test.

Please let me know if you get these random WSOD again.

**Comment by bdg0296** [comment]
Just upgraded and will let you know.

Thanks

**Comment by bdg0296** [comment]
Seems like the GUI white screen has returned in 4.1.1. I hadn't had a problem with the previous version

**Comment by tross2015** [comment]
Mine does the same thing. I am on window 10 64bit. It didnt happen before and now 3 times a day. Would switching over to cli make it better?
