### ISSUE TITLE
Create official Synology package

### ISSUE THREAD

**Issue by d-zalewski** [Storj/storjshare-gui#494]
I will be nice if there was an easy to install official package that could be installed on Synology (arm or x86)

**Comment by littleskunk** [comment]
https://www.synology.com/en-global/support/developer
You can create the easy to install package yourself. I don't have a Synology box to play with and linux 32bit  binary would have a higher priority. 

@super3 your decision

**Comment by razorfish-sl** [comment]
actually synology would be better, we are sitting on hundreds of TB in a 24/7/365 data centre

**Comment by littleskunk** [comment]
The priority is clear. Synology package has a very low priority. A few hundred TB will not change the priority. We already have a few PB free space available.

You can create the package yourself or install storjshare-daemon. Don't expect a Synology package any time soon.
