### ISSUE TITLE
GUI constantly asking to update

### ISSUE THREAD

**Issue by ericninjinha** [Storj/storjshare-gui#501]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.1.0
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.
```
GUI should run and only ask to update when a new version is released

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Every time i start the GUI it asks for me to update it, even thought i have the latest version, and because of that, its constantly preparing and never actually running the programs properly.(I've been having this problem for a few months now but since i always got paid normally i thought everything was fine.
 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...All i really did was just install just the GUI and start running it, i had no idea about all the other steps and softwares i had to install 
2. ...I also tried install everything properly a few days ago with all the correct ports and forwarding but nothing changed.
3. ...

### Screenshots (Optional)
![sem titulo3](https://cloud.githubusercontent.com/assets/26369056/23875498/69a867dc-0818-11e7-9fb4-0e9f4ebb0e8f.png)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
You are running an old version and the message is correct. This is a common problem on Windows. We support 32bit and 64bit binaries. You can install both at the same time. If you update only one version the other version will still show you this message.

**Comment by ericninjinha** [comment]
so whats the latest version?
