### ISSUE TITLE
The GUI doesn't respect storage size in settings

### ISSUE THREAD

**Issue by michaldlouhy** [Storj/storjshare-gui#503]
### Versions

- **GUI Version:** v4.1.0 x64
- **Operating System:** Windows 10 v. 1607 x64 (with all hotfixes and updates installed); CPU Intel Core i5 M480@2,67GHz, 8GB RAM, 256 GB SSD

### Expected Behavior

The program (GUI) should respect the settings regarding storage size which user set.

### Actual Behavior

The program (GUI) dosn't respect the limit which I set in setting (I set 5 GB (it means 5000 MB) for storage size). Yesterday was used space 4.994 GB (it means 4994 MB), now it is more than 5.55 GB (means 5550 MB) and growing up. It is not a problem about GB/GiB calculation, it is about it that the size of shared data folder going up "to the moon".

### Steps to Reproduce

I'am not able to describe how this can be reproduced. It happend only on one concrete disk, never in past wasn't problem with this.

### Screenshots (Optional)

![image](https://cloud.githubusercontent.com/assets/25122172/23991897/3be458f4-0a3b-11e7-9d44-d6ebaa6e8116.png)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Logfile please

**Comment by michaldlouhy** [comment]
[Logs.zip](https://github.com/Storj/storjshare-gui/files/848544/Logs.zip)

**Comment by michaldlouhy** [comment]
Now, I found the same problem on another disk on another PC with Windows Server 2008 R2...

![image](https://cloud.githubusercontent.com/assets/25122172/24014196/4a997264-0a84-11e7-9a74-50d80c6515ad.png)

**Comment by littleskunk** [comment]
Moved to core: https://github.com/Storj/core/issues/675
