### ISSUE TITLE
Microsoft c++ runtime library

### ISSUE THREAD

**Issue by tross2015** [Storj/storjshare-gui#505]
### Versions

Replace the values below with your own:

- **Storj Share** 4.1.1
- **Operating System:** Win 10 64bit

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.
Error popped up while running!

```
![storerror](https://cloud.githubusercontent.com/assets/20988413/24042696/6e471eca-0b13-11e7-8407-3106b82c661e.PNG)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/463

Workaround: https://github.com/Storj/storjshare-daemon/issues/76
