### ISSUE TITLE
GUI Reporting wrong drive size

### ISSUE THREAD

**Issue by ne0ark** [Storj/storjshare-gui#506]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.1.1
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
Drive showing correct drive space.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Drive shows random drive space.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

N/A

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 

![capture](https://cloud.githubusercontent.com/assets/660607/24276519/bfa7b2f8-100d-11e7-8442-a1759a2c7b6e.JPG)
![capture2](https://cloud.githubusercontent.com/assets/660607/24276526/c695e3aa-100d-11e7-9839-4db6e3313ad2.JPG)
![capture3](https://cloud.githubusercontent.com/assets/660607/24276561/f8f54f48-100d-11e7-802a-1f85d95eec59.JPG)

**Comment by littleskunk** [comment]
Looks like a problem with your Windows system. Please check the output of `wmic logicaldisk get size,freespace,caption`

**Comment by ne0ark** [comment]
It was using netdrive. Oh well I switch to stablebits.
