### ISSUE TITLE
Frequent mouse stutter

### ISSUE THREAD

**Issue by bathrobehero** [Storj/storjshare-gui#507]
### Versions

- **GUI Version:** v4.1.1

- **Operating System:** win7x64

### Expected Behavior

No mouse lag

### Actual Behavior

If you have a bunch of drives (~100) running under one instance, Storjshare will cause frequent, system-wide, mini mouse stuttering. It's like for a second someone else were moving your mouse back from where you try to move it (no, my PC is not being controlled remotely). Happens every few minutes. After a process of elimination I'm 100% positive it's caused by Storj. If I had to guess Storj is checking all drives at the same time and waiting for all the IO causes the lag. I mean if I start Storj I get a frozen mouse for like 3-4 seconds. No other software does that for me.

### Steps to Reproduce

Have a lot of drives active
wait until you have a few GB of data in most of them
keep moving your mouse, experience frequent mouse stutter/lag

**Comment by bookchin** [comment]
I know this may not be the answer you were looking for, but running 100 nodes within the v4 GUI - especially on a PC you use for other work - is not something we recommend or can reasonably support.

**Comment by bathrobehero** [comment]
Afraid so, but worth a try. Guess I'll be migrating Storj to a mining rig pointed to the (locally shared) drive. No UPS on that one though and plenty of power outages. Staggered drive access instead of doing all of them at once should be developed eventually though - even if it's not priority at the moment.
