### ISSUE TITLE
GUI 5.0.0 error message overlapped

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#508]
### Versions

Replace the values below with your own:

Windows 32bit
GUI 5.0.0
Daemon 2.5.1
Core 6.3.2
Protocol 1.1.0

### Expected Behavior

Please describe the program's expected behavior.

Error message should not overlapp buttons, text or logo.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

![error](https://cloud.githubusercontent.com/assets/6333390/24372545/9df32786-132e-11e7-861c-adc924bc8f39.jpg)

**Comment by littleskunk** [comment]
Error message can not be closed. The X is not working. No error message on the developer console. Now the setup wizard is open and I have no chance to click on back...

**Comment by MrFancyMonocle** [comment]
Was this fixed with: https://github.com/Storj/storjshare-gui/commit/545db7f753c71af42e05abc5aff5b1dad744714d? Or, is this still an issue in Windows? Can't reproduce on current Ubuntu.

**Comment by littleskunk** [comment]
No it is still reproduceable.

The setup wizard is working. I can press the X on any error I will get there. So lets be more clear and add the steps to reproduce it:
Open GUI.
Press Import Config
Select Settings.json from old GUI
This will tigger the error message on the screenshot.

**Comment by littleskunk** [comment]
Now I don't get the error message anymore: https://github.com/Storj/storjshare-gui/pull/483/commits/34e6c7b9cff49b42a81372b99d6ccbd19f7194d5

**Comment by littleskunk** [comment]
I can now close the error message.
