### ISSUE TITLE
GUI 5.0.0 reload not working

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#509]
### Versions

Replace the values below with your own:

Windows 32bit
GUI 5.0.0
Daemon 2.5.1
Core 6.3.2
Protocol 1.1.0

### Expected Behavior

Please describe the program's expected behavior.

GUI Menu -> View -> Reload
Reload should work like a GUI restart. Usefull for any kind of problem. Memory leaks for example.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

![error](https://cloud.githubusercontent.com/assets/6333390/24374145/0ca27d80-1334-11e7-890d-abc84d8df2d1.jpg)

**Comment by littleskunk** [comment]
Menu -> File -> Quit is not working as well. I don't get any error message but the GUI is still running in system tray.

**Comment by MeijeSibbel** [comment]
I have the same issue.

**Comment by bookchin** [comment]
766001a

**Comment by littleskunk** [comment]
Reload is working fine now but I have a new problem now:
![reload exception](https://cloud.githubusercontent.com/assets/6333390/25046539/3dd57b62-2132-11e7-90e5-11ea936445ee.jpg)

**Comment by littleskunk** [comment]
Windows GUI 32Bit
```
C:\Users\Skunk>storjshare daemon --foreground

  * starting daemon in foreground

{"level":"info","message":"got status query","timestamp":"2017-04-14T15:39:54.285Z"}
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:572:26)
```
