### ISSUE TITLE
GUI 5.0.0 migration of old settings.json

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#511]
### Versions

Replace the values below with your own:

Windows 32bit
GUI 5.0.0
Daemon 2.5.1
Core 6.3.2
Protocol 1.1.0

### Expected Behavior

Please describe the program's expected behavior.

I have a few GB used space from the old GUI and would like to migrate them. I need to migrate my private key or all shards will be lost. I would expect an import button that will read my old settings.json file.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

The migration is not possible and to difficult at the moment. Normal GUI user doesn't even know they have a private key and should not lose it. They will setup the same drive on the new GUI. That way they start farming from 0. The bridge will not pay for the shards connected to the old private key. We will get a lot of funn on the next payout day.

**Comment by bookchin** [comment]
12682a6

**Comment by littleskunk** [comment]
I was able to import my old GUI config with 2 drives on it. Nice and easy migration. Well done :)
