### ISSUE TITLE
error: LockFile E:\storjshare-381c6e\sharddata.kfs\169.s/LOCK: El proceso no tiene acceso al archivo porque esta siendo utilizado por otro proceso.

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#512]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.1.1
- **Operating System:** win 10 64 bits

### Expected Behavior

Please describe the program's expected behavior.

```
No Lock error, continue sending offer messages as usual 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
GMT+0200 (Hora de verano romance)] sending PUBLISH message to {"userAgent":"6.3.0","protocol":"1.1.0","address":"176.194.209.157","port":37479,"nodeID":"b73fa076ba4d8e8c01d13fd300149c7e5ef95f09","lastSeen":1490743457416}
{info} [Wed Mar 29 2017 01:25:55 GMT+0200 (Hora de verano romance)] received valid message from {"userAgent":"6.0.11","protocol":"1.0.0","address":"83.156.255.33","port":20206,"nodeID":"b73a22bdccfbffc288a16a6d91c8259ef829d1f0","lastSeen":1490302140579}
{info} [Wed Mar 29 2017 01:25:55 GMT+0200 (Hora de verano romance)] replying to message to 7e33dcc205696dca130c071177432c6f812d52e5
{error} [Wed Mar 29 2017 01:25:55 GMT+0200 (Hora de verano romance)] Could not get usedSpace: IO error: LockFile E:\storjshare-381c6e\sharddata.kfs\169.s/LOCK: El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso.

{info} [Wed Mar 29 2017 01:25:56 GMT+0200 (Hora de verano romance)] received valid message from {"userAgent":"6.3.2","protocol":"1.1.0","address":"91.144.168.250","port":4018,"nodeID":"b70e558a938c2dd0162cfdff019aa352ac136d4f","lastSeen":1490681741400}
{info} [Wed Mar 29 2017 01:25:56 GMT+0200 (Hora de verano romance)] received valid message from {"userAgent":"6.3.2","protocol":"1.1.0","address":"server2dk.ddns.net","port":4020,"nodeID":"b76f74bf6d1a6e47f76702638b608feef51adf34","lastSeen":1490721496341}
```
[StorjDrive-381c6e_2017-3-29 (2).txt](https://github.com/Storj/storjshare-gui/files/877354/StorjDrive-381c6e_2017-3-29.2.txt)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Complete logfile please. I don't see any sign that this node was sending any OFFER. At the moment it looks like 2 nodes with the same private key are pointing to the same storage location. One will get these errors all the time.

**Comment by MeijeSibbel** [comment]
Issue was resolved with a restart, closing
