### ISSUE TITLE
GUI 5.0.0 - Storage size unit not displayed at setup step 3 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#514]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
When i set the storage size unit in Step 3 of the setup the unit should remain on the screen. 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
After i select the correct size unit the box remains empty. This is confusing for the users, it should display the correct size unit after selecting it. 
```
### Screenshots (Optional)

![step_3](https://cloud.githubusercontent.com/assets/11735738/24636086/a7fb6ca6-18cf-11e7-8efa-99603d528be1.png)

**Comment by MrFancyMonocle** [comment]
This issue should be resolved in current next. The step-3 page is still being updated.
