### ISSUE TITLE
GUI 5.0.0 finish wizard with invalid storage location

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#519]
### Expected Behavior

I didn't select a storage location (see screenshot). I would expect an error message and no way to get to the next step.

![step2](https://cloud.githubusercontent.com/assets/6333390/24818613/8c161922-1be1-11e7-9392-0a73970cd022.jpg)

### Actual Behavior

I get the error message but on the next step. I can finish the wizard with an invalid storage location.

![step2error](https://cloud.githubusercontent.com/assets/6333390/24818706/d960b3d6-1be1-11e7-81bf-cab3d051d5f6.jpg)

**Comment by JukeboxRhino** [comment]
I know it probably doesn't strictly fall under this issue but the same error happens if you leave the address blank. When you complete the wizard you will get an assertion error at the top of the screen but dismissing it does nothing and you are stuck on a twirling loading icon.

**Comment by computeronix** [comment]
using the above information; With GUI 5.0 if I go all the way through it hangs at the very end with a spinning storj cloud

**Comment by jfnz** [comment]
Same issue here

**Comment by therampagerado** [comment]
any fix?

**Comment by littleskunk** [comment]
There is no fix but selecting a valid storage location solved it for me.

**Comment by therampagerado** [comment]
And what is 'valid' storage location? Because I wanted to add numerous folders and all of them were rejected.

And now the software is working.

**Comment by JukeboxRhino** [comment]
Fixed with #632, can be closed
