### ISSUE TITLE
Disallow input of the SJCX owner address

### ISSUE THREAD

**Issue by frdwrd** [Storj/storjshare-gui#522]
Counterwallet displays the address that issued SJCX as part of the asset info. Several users have incorrectly entered this address into the payout address field. Should disable entry of it.

`17VLRV4y7g15KNhCepYvgigHHvREzbEmRn`

Of course, this is kinda a moot point, as we're going to be switching away from Counterparty soon.

¯\\\_(ツ)\_/¯

**Comment by JukeboxRhino** [comment]
Fixed with [daemon PR #175](https://github.com/Storj/storjshare-daemon/pull/175)
