### ISSUE TITLE
Error: cannot find module `./hash/sha` after windows update

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#524]
### Versions

Replace the values below with your own:

- **GUI Version:** v4.1.1
- **Operating System:** Windows 10

### Expected Behavior

Windows defender does not block storjshare

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
After a windows defender update it blocks storjshare and prevents it from running.

Reference issue:
https://github.com/indutny/hash.js/issues/7

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Windows update
2. Run storjshare
3. windows defender blocks storjshare

### Screenshots (Optional)

![trojan](https://cloud.githubusercontent.com/assets/11735738/24961928/3b27f29c-1f92-11e7-8bab-6a84cb8408a4.png)
![sha](https://cloud.githubusercontent.com/assets/11735738/24961929/3b4b8338-1f92-11e7-8aff-d42cad0b45b7.png)

**Comment by frdwrd** [comment]
@MeijeSibbel this is more of a "can't fix" than a "won't fix." There's basically nothing we can do about Windows Defender definitions. 

I'm trying to figure out the best way to communicate this to the community. If you restore the files, does it solve the problem?
