### ISSUE TITLE
GUI 5.0.0 wrong UPnP migration

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#525]
old GUI setting:
```
      "network": {
        "hostname": "127.0.0.1",
        "port": 5000,
        "seed": "",
        "nat": "true"
      },
```

new GUI setting:
```
  "rpcAddress": "127.0.0.1",
  "rpcPort": 5000,
  "doNotTraverseNat": true,
```

The migration disabled UPnP. I am unable to get a connection.

**Comment by littleskunk** [comment]
A second test this time nat was set to false:
```
  "rpcAddress": "127.0.0.1",
  "rpcPort": 5000,
  "doNotTraverseNat": false,
```

The migration is reading the old value. I will try to fix it myself.

**Comment by littleskunk** [comment]
79938e5413b6de2cc34ba761637410f965a98274

**Comment by onsightit** [comment]
The negative naming convention is confusing.  I assume doNotTraverseNat:false is the same as traverseNat:true?

My daemon instances do not seem to want to use UPnP, so I have tried both true and false to no avail.

Note: I have 5 storjshare-daemon instances running on 5 Pi3s that are on the 192.168.1.X subnet. My router, which is configured for UPnP (and works with similar port-forwaring for IPFS) is forwarding ports 4000-4004 to one Pi on the internal network. That Pi is a seed node for the others. The only time I can get them to connect to each other is if I set doNotTraverseNat:true.

Note2: I am running on a private network protocol with no bridge. Just the daemons.

**Comment by littleskunk** [comment]
You are mixing a few things here. You can use port forwarding or UPnP. Using both at the same time is not possible.

If you would like to use port forwarding please don't forget to configurate your external IP or DDNS. I am not able to send you a message to 192.168.1.X:4000. I need your external IP or DDNS. doNotTraverseNat=true

If you would like to use UPnP please use a free port that is not forwarded.

**Comment by onsightit** [comment]
Update: I have two clusters of Pi3s on two different networks. I was able to port forward to one Pi (a seed node) on each network, and the others all connected via UPnP. So a combination is possible.  I have 15 storjshare-daemons all connected now.  :)

The key was to set the rpcaddress to the public IP, and set doNotTraverseNat=false.
