### ISSUE TITLE
...\hash.js\lib\hash\sha.js is classified as Trojan Win32/Vigorf.A 

### ISSUE THREAD

**Issue by BerChill** [Storj/storjshare-gui#528]
### Versions

- **GUI Version:** v4.1.1
- **Operating System:** Microsoft Windows 10 Pro Version 10.0.14393 Build 14393

### Expected Behavior

None of the files installed and used by Storj Share are identified as being harmful (virus, trojan, etc.)

### Actual Behavior
Windows Defender reports `file:C:\Program Files\Storj Share\resources\app\node_modules\bitcore-lib\node_modules\elliptic\node_modules\hash.js\lib\hash\sha.js` as a trojan rating it as severe since it allegedly runs code from an attacker. Thus, the file is being quarantined by Windows Defender and Storj Share will not work upon a reboot of the system.

### Steps to Reproduce
I cannot be certain here since the issue started to appear recently after a system check by Windows Defender

1. have Windows Defender installed and running
2. run Storj Share on startup
3. run a full system check by Windows Defender
4. aforementioned file will be recognized and quarantined by Windows Defender

### Screenshots (Optional)

![storj-trojan](https://cloud.githubusercontent.com/assets/18327444/25071012/c73aa91a-22ac-11e7-886d-8ba2e110018e.JPG)

**Comment by littleskunk** [comment]
That is a false positive. Update your windows defender to get the latest fix. More details you can read here: https://github.com/indutny/hash.js/issues/7

**Comment by eventwifi** [comment]
Same issue in Avast.
