### ISSUE TITLE
GUI v5.0.0 cross-platform config file migration check

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#529]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** ALL

### Expected Behavior

Please describe the program's expected behavior.

```
1. Storj share checks if the path nomenclature matches that of the current system, if it does not match it warns the user that the config file originates from another operating system, it then asks the user to browser to the directory of each node.
2. Alternatively Storj Share could check if the data directory specified in the config file used for the migration exists or not, if it does not exist it ask the user to browse to the correct path which contains the node data directory.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
currently if one imports say a Storjshare-GUI `settings.json` file from a Windows system into say a Linux v5.0 Storjshare GUI, the GUI will import the config file, however, it will still use the windows path which is incompatible in Linux. Storjshare does not inform use the path is incorrect. It will create a new database and start the nodes from scratch. Users will have no idea if the migration was successful or not. Adding something like a cross-platform path checker that asks the user to browser to the correct data directory for each node when one migrates to another OS would also work.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Import a config file from another operating system. 
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by tross2015** [comment]
I tried using a conf setting from win 10 with storj v5 on linux. Import error but nodes created in storj-gui folder and conf sent to folder containing imported setting json. When I changed the path of first setting in the win conf setting json you see in this image where the conf went. 
![testeditdesk](https://cloud.githubusercontent.com/assets/20988413/25091134/c76619d4-2387-11e7-8987-c356d0f7135d.PNG)
