### ISSUE TITLE
GUI v5.0.0 Config file saved to wrong directory after migration. 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#530]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** ALL

### Expected Behavior

Please describe the program's expected behavior.

```
After the migration the new config file is saved to  `~/.config/storjshare/configs/`
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
When one migrates from Storjshare v4.x to v5.0.0, the config file is saved in the same directory as the original `settings.json` file. The file should be saved to the `~/.config/storjshare/configs/`
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Import a config file from Storjshare v4.x
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by tross2015** [comment]
I had the same thing happen with linux during migration! I tried linux mint and Ubuntu same problem with both.

**Comment by bookchin** [comment]
The config file is intentionally saved in the same directory as the imported one.
