### ISSUE TITLE
GUI v5.0.0 “I’m experienced user, skip setup” -> “I’m an experienced user, skip setup”

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#531]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
d1c105122d0c0f19a07d285f9e2c15abd005d0e6
