### ISSUE TITLE
GUI v5 linux storj node doesnt load after computer shutdown and restart

### ISSUE THREAD

**Issue by tross2015** [Storj/storjshare-gui#532]
### Versions

Replace the values below with your own:

- **GUI Version:** v5
- **Operating System:** Ubuntu 14.04, linux mint 16

### Expected Behavior

Please describe the program's expected behavior.
linux storj node doesnt load after computer shutdown and restart. It would start the test node I made. It also didnt restart an imported node. I could refresh the program and all is ok. 
```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. create or import node.
2. run node till it works
3. close storj reboot computer

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Same problem on Windows. The old configuration dialog doesn't exists anymore. No more "start GUI on user login" option that would add the needed registry keys.

I could modify the installer to add the key. That would solve the problem for windows but not for Linux or OSX.

**Comment by bookchin** [comment]
Please use the operating system's method for configuring an application to start on boot/login.
