### ISSUE TITLE
Storj GUI in Programs and Features does not display Publisher or GUI Version

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#533]
Storj GUI in Programs and Features when installed on Windows (tested with Windows 10 Enterprise) does not display publisher or the storj GUI version.

This would be important to add to give reference to who owns the app and then also a quick view at what version the GUI is before attempting to repair or uninstall from this screen.

Screenshot:
![storjgui](https://cloud.githubusercontent.com/assets/19168174/25093067/8972e09a-235e-11e7-9134-2acd447d5aa3.PNG)

**Comment by computeronix** [comment]
Size could be added too, but given it's dynamic scaling it is not necessary.

**Comment by littleskunk** [comment]
At the moment the uninstaller has these additional informations.
```
    WriteRegStr HKLM "${uninstkey}" "DisplayName" "${productName}"
    WriteRegStr HKLM "${uninstkey}" "DisplayIcon" '"$INSTDIR\icon.ico"'
    WriteRegStr HKLM "${uninstkey}" "UninstallString" '"$INSTDIR\${uninstaller}"'
```

I should be able to add the size but lets keep it simple for the beginning. I will start with the publisher.

**Comment by computeronix** [comment]
nice thank you!
