### ISSUE TITLE
uninstaller remove personal data language

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#539]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0 (beta)
- **Operating System:** Windows 10

When you uninstall the application it asks to remove personal data.

The language shows "Remove also my Storj Share personal data"

The word also seems redundant and could be taken out?

Also in the top text "If you really want to remove Storj Share press uninstall button"

add the word "the" so it sounds

"If you really want to remove Storj Share press the uninstall button"

![uninstall](https://cloud.githubusercontent.com/assets/19168174/25110760/75de02d4-23b4-11e7-9b28-ab9d06aeb6af.PNG)

**Comment by littleskunk** [comment]
![grafik](https://cloud.githubusercontent.com/assets/6333390/25204106/45212e7e-255c-11e7-9fa2-299251494383.png)
