### ISSUE TITLE
Gui Version Won't Import Daemon Config

### ISSUE THREAD

**Issue by bigjme93** [Storj/storjshare-gui#545]
Ok so i've installed the latest v5 gui, and am trying to import my .json config files into the app. on selecting the config nothing happens at all and the file doesn't import

Operating System: Windows Server 2016
Old Cli Version: * daemon: 2.5.1, core: 6.4.0, protocol: 1.1.0

**Comment by littleskunk** [comment]
The import may take some time. Please try again. Import the old config and wait 10 minutes.
