### ISSUE TITLE
GUI v5.0.0 "Invalid payout address" while the address is valid

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#549]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
payout address is valid and config file import works
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
`invalid payout address` error appears at config file import while the address is valid. 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by MeijeSibbel** [comment]
![clipboard - may 2 2017 8-11 pm](https://cloud.githubusercontent.com/assets/11735738/25646273/bd7314b2-2fae-11e7-8966-41629bbde2c7.png)

**Comment by MeijeSibbel** [comment]
e.g. https://counterpartychain.io/address/12i2i6qeX52qMGzGjQPMhTvAXbxpviKFod

**Comment by littleskunk** [comment]
Old config file please (without the private key)

**Comment by MeijeSibbel** [comment]
I don't have the config file anymore
