### ISSUE TITLE
NAS System an Storj.io V5

### ISSUE THREAD

**Issue by kikiiuuh** [Storj/storjshare-gui#551]
### Versions

Replace the values below with your own:

- **GUI Version:** V5.0.0.0.
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

Storj.io - Now i have updated to V5 and the NAS System for mei STORJ are not available.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 
![image](https://cloud.githubusercontent.com/assets/28345516/25657218/135b2a60-2ffd-11e7-99c0-498aaf72b5e4.png)

**Comment by MrFancyMonocle** [comment]
Please open an issue for this in the https://github.com/Storj/storjshare-daemon project. The GUI is simply bubbling an error up from the daemon for this. If you're only seeing this in the GUI and not in the CLI, we'll re-open here as well.
