### ISSUE TITLE
Api does not show any status after having GUI 5 run for 8 hours

### ISSUE THREAD

**Issue by nerdatwork** [Storj/storjshare-gui#552]
### Versions

Replace the values below with your own:

- **GUI Version:** v5
- **Operating System:** Windows 7

### Expected Behavior

Please describe the program's expected behavior.

```
It should show status of my nodes as given in tutorial for nodeid
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"error":"Contact not found"} is shown on the api URL.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Installed version 5
2. Imported config thereby converting it to version 5 specs.
3. All drives were successfully imported and active ON sate. Uptime showed 8 hours but API url shown below kept showing contact error.

### Screenshots (Optional)

![storj 5 api](https://cloud.githubusercontent.com/assets/15882196/25657998/44aecd26-301e-11e7-8ebd-cc0f64673676.jpg)

**Comment by MrFancyMonocle** [comment]
This is a contact error. Need additional info on the error, please fill out the "Steps to Reproduce" section.

**Comment by nerdatwork** [comment]
Steps to reproduce section updated.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/692
