### ISSUE TITLE
GUI_V5 will only show 7 nodes

### ISSUE THREAD

**Issue by guelz** [Storj/storjshare-gui#553]
### Versions

Replace the values below with your own:

- **GUI Version:** V5
- **Operating System:** Windows 10

### Expected Behavior

after importing the daemon config's of 9 nodes, GUI_V5 will only run the first 7 (0-6) of them! 
no error message!

### Actual Behavior
after importing them thru the gui last two will not show up in  ../gui.snapshot
also adding them manually to ../gui.snapshot will not start them.

https://api.storj.io/contacts/691bb91b1a8bea64b775cb835b3768ce3714151d
https://api.storj.io/contacts/29c67612d3a4cb9c24ae028ee544db4175148634
https://api.storj.io/contacts/6da315cc293bcaa6a2795f3ee72d334d126ea568
https://api.storj.io/contacts/4fbffc482c8d72e56b801684390df0f21863f434
https://api.storj.io/contacts/78810ce5c533d44886a625d44931a22ae92b49e8
https://api.storj.io/contacts/90b473f2e18939e173a7585e13a5e05229569a75
https://api.storj.io/contacts/e69906d8d6825b084491799eec25b1c01c2ad77a

https://api.storj.io/contacts/4862207a2f65edb60e8e8359dfa86507eddbb914   
https://api.storj.io/contacts/6ef4e759ac7e336939ddba748f6d0a8896906b47    

p.s. had to edit this report because i'm stupid!-/

**Comment by guelz** [comment]
turns out this is also the "insufficient resource error" just without an error message in the gui.
daemon will run the same 9 nodes and config's just fine.
so i'm on daemon for now.

**Comment by MrFancyMonocle** [comment]
Closing, please continue discussion of any "Insufficient system Resources" issues in the https://github.com/Storj/storjshare-daemon project (there are probably several issue threads open now surrounding it). Any change to this behavior will take place there.
