### ISSUE TITLE
Memory leak or use

### ISSUE THREAD

**Issue by tross2015** [Storj/storjshare-gui#554]
### Versions

Replace the values below with your own:

- **GUI Version:** v5
- **Windows 10 pr VM

### Expected Behavior

Please describe the program's expected behavior.
Should work fine
```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

The wm has 2 cores 4gb ram but as time goes by the ram usage goes up and up! Storj is the sole running program on VM except anti virus time program and ram monitor.

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Dulicate: https://github.com/Storj/storjshare-daemon/issues/114
