### ISSUE TITLE
New GUI don't show drive/node shared amount

### ISSUE THREAD

**Issue by BogdanGoim** [Storj/storjshare-gui#555]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** Windows 10

### Expected Behavior

After update, new doesn't recognize one of my drives/nodes with message: share 3c9af..... invalid storage size. After this I reduced the allocated space in the config file, but no much gain. Now the drive is visible, but the GUI doesn't show the amount of disk space allocated or ocuppied
![after edit config file](https://cloud.githubusercontent.com/assets/16228706/25660950/23e56b74-3017-11e7-8ea9-f9c4801cac4f.JPG)
![before edit config file](https://cloud.githubusercontent.com/assets/16228706/25660951/248c7068-3017-11e7-852e-d85aecbdbc62.png)

[settings_json.txt](https://github.com/Storj/storjshare-gui/files/973300/settings_json.txt)

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Patience please. The startup of the farmer may need a few minutes.

**Comment by BogdanGoim** [comment]
After 48 minutes is the same. Tough I have 137 peers

**Comment by littleskunk** [comment]
Upload your logfile on rocket chat please. Channel storjshare

**Comment by BogdanGoim** [comment]
OK. Thank you

**Comment by BogdanGoim** [comment]
Is already there
