### ISSUE TITLE
Second drive will not show used-space after migration from GUI v4.x 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#556]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
All drives show the correct used-space after migration.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Only the first node shows the correct used-space 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

bogdan.apostoaia on rocketchat:

![storj 5](https://cloud.githubusercontent.com/assets/11735738/25662617/11a9482c-300d-11e7-8464-142a1c5b7579.JPG)

@mazzydan on rocketchat:

![screen shot 2017-05-03 at 8 23 09 am](https://cloud.githubusercontent.com/assets/11735738/25662661/37b0d562-300d-11e7-9fc2-00937d597e13.png)

**Comment by MeijeSibbel** [comment]
@epic.designs on rocketchat

![w](https://cloud.githubusercontent.com/assets/11735738/25665376/4bce7196-3015-11e7-8053-09ca4fee0953.PNG)

**Comment by littleskunk** [comment]
Lets use https://github.com/Storj/storjshare-gui/issues/567 to track this
