### ISSUE TITLE
Advanced Option to specify threads to use

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#558]
In the GUI allow an advanced option to specify the number of threads to utilize on the system.

This way you can specify the min threads of 1 or max (max number system can handle) or any number in between to utilize.

**Comment by braydonf** [comment]
The environment variable `UV_THREADPOOL_SIZE` may be able to be used. Otherwise Node.js is single threaded for JS related processing.

**Comment by MrFancyMonocle** [comment]
Currently (after 5.3.2 storjshare-daemon is merged, was max-1), the default max is the max recommended, which is 1 thread per share. If we do add any config for this in the GUI, it will be added in tandem with daemon optimizations. Closing this for now, but if there is a use case, where more shares are required, the storjshare-daemon start command can be run with a -u (--unsafe) flag to bypass this restriction.
