### ISSUE TITLE
Can add Drive pointing to same location as earlier drive

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#562]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** Windows 10 - 64-bit

### Expected Behavior

Please describe the program's expected behavior.

```
Do not allow adding a drive to the same location as an existing drive
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Right now it allows adding multiple drives pointing to the same storage location
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Add drive and point it to C:\storj
2. Add second drive pointing to same location as first drive
3. Repeat

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by MrFancyMonocle** [comment]
Hmm, well, it will allow you to do this, but one share will shut-down if you try. I do think a warning would be helpful at the step of entry, though.
