### ISSUE TITLE
Track and display bandwidth utilized in GUI. 

### ISSUE THREAD

**Issue by ryanshay** [Storj/storjshare-gui#568]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

I would like to request an additional value be displayed on the GUI that indicates the amount of bandwidth utilized for the current billing period. Bonus points for splitting into upload/download. Numbers are fun.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

New feature request. Does not exist. 

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

N/A

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 

N/A

**Comment by littleskunk** [comment]
Please add your ideas to https://github.com/Storj/storjshare-gui/issues/513
