### ISSUE TITLE
Cannot add SMB mapped storage location

### ISSUE THREAD

**Issue by jfnz** [Storj/storjshare-gui#569]
### Versions

GUI 5.0.1
Daemon 2.5.3
Core 6.4.2
Protocol 1.1.0

- **Operating System:** Windows 10 x64 v1607

### Expected Behavior

Please describe the program's expected behavior.

Previous versions allowed me to add a drive located on my NAS.

The latest version prevents me from adding it via a mapped drive (e.g. L:\ -> <nas-ip>\share) -- it just plain doesn't show up in the explorer windows when selecting a location.

It will allow you to go via <\\<nas-ip>\share> but it creates the error listed below.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Error produced = "Error: Invalid directory selected"

You can click next anyway, at which point it asks you for storage size but this is blank (obviously as there is no drive selected).

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Add the drive
2. Select the SMB location
3. Receive error

### Screenshots (Optional)

1. Seen via Storj (no mapped drives shown)
![image](https://cloud.githubusercontent.com/assets/12504630/25777205/4d81c69c-332a-11e7-92b4-e2cf93acc652.png)

2. Seen via Explorer (mapped drives shown)
![image](https://cloud.githubusercontent.com/assets/12504630/25777204/425cde14-332a-11e7-86e0-ec63b701e8a7.png)

**Comment by jfnz** [comment]
Have managed to solve my own issue here:

**Symptoms**
Mapped network drives are not visible in application

**Cause**
This problem occurs because UAC treats members of the Administrators group as standard users. Therefore, network shares that are mapped by logon scripts are shared with the standard user access token instead of with the full administrator access token.

**Solution**
Configure the EnableLinkedConnections registry value, which allows Windows to share network connections between the filtered access token and the full administrator access token for a member of the Administrators group.

_Caution: Incorrect use of the Windows registry editor may prevent the operating system from functioning properly. Great care should be taken when making changes to a Windows registry. Registry modifications should only be carried-out by persons experienced in the use of the registry editor application. It is recommended that a complete backup of the registry and workstation be made prior to making any registry changes._

To configure the EnableLinkedConnections registry value, follow these steps:

1. Click Start, type regedit in the Start Search box, and then press ENTER.
2. Locate and then right-click the following registry subkey:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
3. Point to New, and then click DWORD Value.
4. Type EnableLinkedConnections, and then press ENTER.
5. Right-click EnableLinkedConnections, and then click Modify.
6. In the Value data box, type 1, and then click OK.
7. Exit Registry Editor, and then restart the computer.

**Comment by meaverick** [comment]
@jfnz 
  I follow this document setup map disk but can't forward port. the port is black, even restart the computer

**Comment by jfnz** [comment]
Doesn't sound like an issue related to this one. Maybe make a new post?
