### ISSUE TITLE
Link to upgrade guide is missing in release notes of 5.0.1

### ISSUE THREAD

**Issue by maxp1256** [Storj/storjshare-gui#570]
I've upgraded from 4.x.x to 5.0.1 and thought that I've lost my config. 
After reading the release notes of v5.0.0 I've found the migration guide. It would be great if there is a hint to the migration guide for <v5 users in the next couple of v5 versions.

**Comment by littleskunk** [comment]
I am sorry but release information are incremental. You have to read all release informations even if you skip a version.
