### ISSUE TITLE
"Currently Running Storj on Test Network"

### ISSUE THREAD

**Issue by adwit3** [Storj/storjshare-gui#571]
- Version:5.0.1
- Operating System: Xubuntu 16.04

I updated to gui 5.0.1 and imported my config. After start, gui is running on "testnet", and have 0 peers.
I tried to download and compile 5.0.1 and 5.0 but both have this problem.
If I run (npm start) older (v4) gui from command line, I see this:

> @ start /home/user/storjshare-gui_old
>node ./tasks/start

and if I run 5.0.1 node i see this:

> @ start /home/user/storjshare-gui
>node ./tasks/start --env=development

Maybe "--env=development" is a problem of this?

![clipboard - 7 maja 2017 15-06](https://cloud.githubusercontent.com/assets/16165493/25783260/790e6ca0-3359-11e7-8121-41e09eb5cf4a.png)

**Comment by nico3070** [comment]
I have same Problem with the GUI.
![test networkk](https://cloud.githubusercontent.com/assets/28511508/25783512/7c424d34-335d-11e7-9671-a17903f16670.PNG)

**Comment by littleskunk** [comment]
The old GUI did the same but doesn't print out any hint. The problem is that you start storjshare in developer mode. At the moment it will work. Long term I would prefer to release binaries for you. You are both running a raspberry pi right?

**Comment by nico3070** [comment]
Im running Raspberry PI 3 i dont know that arch he is running

**Comment by adwit3** [comment]
I'm running on intel atom N450 (x86)

**Comment by boukeversteegh** [comment]
i've asked about it on the chat, and there is no way to run storjshare-gui in production mode. I've tried building a release, but it compiles a amd64 version, so i gave up.

What did work, was installing storjshare-daemon

```
npm install -g storjshare-daemon
storjshare daemon
storjshare start -c "~/.config/Storj Share/<share name>.json"
```
where I used my previous GUI-created share

then use ``storjshare status`` to see what is going on

**Comment by adwit3** [comment]
I deleted "--env=development" from package.json (scripts/start) and now i got peers, but message about testnet is still displaying

**Comment by MrFancyMonocle** [comment]
Well, the good news is that this feature has a bug currently, so it isn't actually running on a test network, though it displays the message. When I fix this, I'll add a button to disable the test net, but it's probably simpler to modify the package.json.

**Comment by littleskunk** [comment]
i386 binary is ready but not published. I will work on arm now and as soon as everything is working I will release a new version.

**Comment by paulmadore** [comment]
"I deleted "--env=development" from package.json (scripts/start) and now i got peers, but message about testnet is still displaying, but my "last seen" in api json (api.storj.io/contacts) is current time"

This needs to happen programmatically after npm install is run. This is the actual bug fix.

**Comment by littleskunk** [comment]
I am not sure about fedora. Based on the documentation (https://electron.atom.io/docs/tutorial/supported-platforms/#linux) I would expect that the .deb binaries should work on fedora 21. If that is not the case I could setup a build server for fedora. Just let me know.

@nico3070 My arm system was to slow to build binaries. I am sorry . I can't offer binaries at the moment but I will try it again as soon as I have time for it. Meanwhile I keep this issue open and will debug why this testnet message is still there even if not running in development mode.

I think we can remove the development flag. I will work on a pull request later. Still low-medium priority so it will take some time.

**Comment by paulmadore** [comment]
> I am not sure about fedora. Based on the documentation (https://electron.atom.io/docs/tutorial/supported-platforms/#linux) I would expect that the .deb binaries should work on fedora 21. If that is not the case I could setup a build server for fedora. Just let me know.

dnf install dpkg-deb patches the problem that Fedora users might have had, but then you also need alien to convert it to a proper rpm that will actually install in the system, because simply trying to install the deb also failed for me. After I converted it from deb to rpm, and I think I had to tell it to ignore a postinstall script, [it installed and worked](https://steemit.com/storj/@phmadore/howto-making-storjshare-gui-run-on-fedora).
