### ISSUE TITLE
Stop Drive Then you cannot start

### ISSUE THREAD

**Issue by osok** [Storj/storjshare-gui#573]
### Versions

Replace the values below with your own:

- **GUI Version:** Linux GUI v5.0.1
- **Operating System:** Ubuntu 14.04 LTS

### Expected Behavior

Please describe the program's expected behavior.

```I have four drives configured.  After stopping a drive I should be able to start it again.  

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```when I hit start I'm told I have insufficient resources.

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...Run Linux GUI with 4 drives
2. ...select Stop Drive
3. ...select start drive (You get an insufficient resources error)

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/119
