### ISSUE TITLE
Shared showing ... (...%) after Updating to v5

### ISSUE THREAD

**Issue by ne0ark** [Storj/storjshare-gui#574]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
Show correct Shared value
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
#0
ON
G:\STORJ02.0\storjshare-5d9eac	5h 20m 15s	0	184	... (...%)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upgrade to v5. @Alexey  checked the logs and everything looks good.

### Screenshots (Optional)

![75abe85681ae545619c8e3cfa773ae45](https://cloud.githubusercontent.com/assets/660607/25784362/7e96a6a8-3339-11e7-9e06-e188674de52f.png)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/567
