### ISSUE TITLE
Step 4 Port Increment

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#577]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** Windows Server 2016 Datacenter

### Expected Behavior

Please describe the program's expected behavior.

```
As you add multiple drives the Port number should detect if the default is already in use and auto increment one

It also should detect if the port is in use and not let you select the port
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
On step 4 as you add multiple drives the port 4000 stays the same and allows you to select the same port for multiple drives leading to nodes not starting due to port conflict
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Add one drive
2. Attempt to add a second drive
3. ...

**Comment by JukeboxRhino** [comment]
This should be closed now, was fixed with #628
