### ISSUE TITLE
Cannot restart nodes in UI

### ISSUE THREAD

**Issue by ssa3512** [Storj/storjshare-gui#578]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** Windows 10 x64
- **CPU Cores:** 4 - Intel i5 2500k
### Expected Behavior

Having created four nodes/shares, I should be able to stop one to edit the configuration and then restart it successfully.

### Actual Behavior

After stopping the node/share, it will not restart. UI presents "Insufficient System Resources Available" at top. Going to File > Quit, and then relaunching StorjShare from the start menu successfully starts all nodes.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Create same number of nodes as CPU cores
2. Stop one node
3. Attempt to restart node

### Screenshots (Optional)
![image](https://cloud.githubusercontent.com/assets/1991399/25822037/565d9e4a-3405-11e7-81a6-4a591c20fa65.png)
![image](https://cloud.githubusercontent.com/assets/1991399/25822060/6a90a7ae-3405-11e7-9491-a7dae5fc3d45.png)
![image](https://cloud.githubusercontent.com/assets/1991399/25822068/70fc8536-3405-11e7-8a24-6334e3911ddc.png)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by computeronix** [comment]
I experience this too

only quitting and restarting still prevents my 4th node from starting

![image](https://cloud.githubusercontent.com/assets/19168174/25883907/4db01bfc-351c-11e7-8910-d28078c9dc20.png)

**Comment by bookchin** [comment]
This is a bug in the daemon, where we are checking the number of managed shares against number of CPU cored instead of checking the number of *running* shares.
