### ISSUE TITLE
Logging stops if you delete log while node running

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#579]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** Windows Server 2016 Datacenter

### Expected Behavior

Please describe the program's expected behavior.

```
When you delete a log file in %USERPROFILE%\.config\storjshare\logs while the node is running then the log file should be created again and new events begin recording

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
If you delete a log file while the node is running, no more logs ever write until the node is restarted
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start node
2. Go to %USERPROFILE%\.config\storjshare\logs
3. Delete log file
4. No more logs...
5. Restart node, logging once again

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/123
