### ISSUE TITLE
Over use allocated Storage 

### ISSUE THREAD

**Issue by ruisilva93** [Storj/storjshare-gui#580]
### Versions
GUI 5.0.1
Daemon 2.5.3
Core 6.4.2
Protocol 1.1.0
OSX 10.12.4

### Expected Behavior

Use storage up to 100%

### Actual Behavior

it's using 137%, and making my system to crash due to 0mb storage available.

### Steps to Reproduce

I don't know - just created the drive, and it over used

### Screenshots (Optional)

https://www.dropbox.com/s/2sw373rh0jn2wou/Captura%20de%20ecr%C3%A3%202017-05-09%2C%20%C3%A0s%2020.12.41.png?dl=0

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/675
