### ISSUE TITLE
Server 2016 does not get firewall rules

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#581]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** Server 2016 Datacenter

### Expected Behavior

Please describe the program's expected behavior.

```
When you install the app and run it, it should add the firewall rules to Windows Firewall (like the Client OS)
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
When you run the app, no firewall rules are prompted to be accepted, nor are any added automatically to Windows Firewall
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. On Server 2016 install and attempt to run your first node

**Comment by MrFancyMonocle** [comment]
Since this is the 2nd request for this feature, I'll look into trying to add this, but OS/Version-specific non-critical nice-to-haves are a lower priority in the issue backlog. Will accept powershell scripts (assuming that's what we'd use here, need to research) as pull requests for this.

**Comment by littleskunk** [comment]
@MrFancyMonocle The NSIS installer is able to add and remove firewall rules. I would like to have an option to add the firewall rule. Default false. That is what I would expect as user. Don't add any firewall rule without my acknowledge.

Based on the priority I will ignore this issue for a while.

**Comment by JukeboxRhino** [comment]
I pushed a commit to one of my branches adding a firewall plugin for NSIS, but I don't actually know enough to add the checkbox and run the firewall plugin. I would assume it would be trivial for anybody that knows how to use NSIS. Documentation for the plugin is [here](http://nsis.sourceforge.net/NSIS_Simple_Firewall_Plugin)

[Check out the commit here](https://github.com/JukeboxRhino/storjshare-gui/commit/ff0b8c79c84ae24ebcb67bff6e476f77576f5231)

**Comment by azrin619** [comment]
Try this one

netsh advfirewall firewall add rule name="Open Port 4000" dir=in action=allow protocol=TCP localport=4000

Port 4000 is usually used by STORJ and I used it on my 2016servers.

**Comment by MysticRyuujin** [comment]
@azrin619 If we're talking Windows it should be PowerShell, like:

`New-NetFirewallRule -DisplayName “Storj Share” -Direction Inbound -Program "C:\Program Files\Storj Share\Storj Share.exe" -Action allow`

This would allow for dynamic/multiple port use.

Although the Program path should be dynamic and it's currently not #609

**Comment by azrin619** [comment]
I am not sure but definitely does not work on server or cloud enviroment.

**Comment by MysticRyuujin** [comment]
> I am not sure but definitely does not work on server

Not sure what that means? That command absolutely works on Windows Server including Core and Nano. Obviously in a cloud environment more work is required and there's almost no way to account for that.

**Comment by littleskunk** [comment]
One pull request and we can try it.

**Comment by azrin619** [comment]
I can create an instance on google compute n azure if you guys wanna test.
Ports all open

**Comment by MysticRyuujin** [comment]
I created pull request #659 and I think it'll work however I'm a GitHub noob and I know nothing about NSIS apart from what I gleaned from a few minutes of Google and reading the current code's syntax :)

**Comment by littleskunk** [comment]
I can't upload the binary here. How about rocket chat?

**Comment by MysticRyuujin** [comment]
I think this should be closed now that my pull request was merged.

**Comment by littleskunk** [comment]
> I would like to have an option on the installer interface to add the firewall rule. Default false. That is what I would expect as user. Don't add any firewall rule without my acknowledgement.

That part is missing. Please keep the issue open.

**Comment by MysticRyuujin** [comment]
#690 May or may not resolve that part :)

**Comment by littleskunk** [comment]
Perfect. Thank you.
