### ISSUE TITLE
failed to start share, reason: failed to parse config

### ISSUE THREAD

**Issue by jfnz** [Storj/storjshare-gui#585]
### Versions

Replace the values below with your own:

- **daemon**: 2.5.4, **core**: 6.4.2, **protocol**: 1.1.0
**npm** --version = 3.10.10
**nodejs** --version = v6.10.3
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Please describe the program's expected behavior.

Able to start applicatoin

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

xxxxx@xxxx:~$ storjshare create --sjcx <sjcx>--storage /mount/storj --size 1TB --rpcport 31337 --rpcaddress 127.0.0.1 --maxtunnels 10 --tunnelportm    in 4000 --tunnelportmax 4010

  * configuration written to /home/xxxxx/.config/storjshare/configs/3cad7730155ce0cde38c5f73f989b61eb30e0a9a.json
  * opening in your favorite editor to tweak before running
  ...
  * use new config: storjshare start --config /home/xxxxxx/.config/storjshare/configs/3cad7730155ce0cde38c5f73f989b61eb30e0a9a.json
xxxxx@xxxxxx:~$ storjshare start --config /home/xxxxx/.config/storjshare/configs/3cad7730155ce0cde38c5f73f989b61eb30e0a9a.json

  failed to start share, reason: failed to parse config at /home/xxxxx/.config/storjshare/configs/3cad7730155ce0cde38c5f73f989b61eb30e0a9a.json

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Have followed guide and installed using npm, etc.

Tried on a fresh install of Ubuntu 17.04 and it worked fine -- something related to existing install or Ubuntu 14.04

Any advice on how to resolve please?

**Comment by bookchin** [comment]
I see a couple issues with your create command. There is no sjcx address provided after `--sjcx`, there is a space in the `--tunnelportmin` option. This likely led to writing a bad config file. Open the configuration in a text editor and see if you can fix it. A JSON validator might help.

**Comment by jfnz** [comment]
Nah, it's just github that's mangled it. I removed the SJCX address for privacy reasons, I should have replaced it with a placeholder.

Why are you so quick to close these bugs when you haven't verified anything?

**Comment by jfnz** [comment]
Pasting the config file your app generates in to a json validation tool presents a plethora of errors. I'm not sure this is accurate, are you?

![image](https://cloud.githubusercontent.com/assets/12504630/25962620/87bac9c0-36d2-11e7-9d80-b9889ab5460b.png)

**Comment by bookchin** [comment]
That's due to the inline comments, which are stripped before parsing. 

Paste your configuration file here, redacting your private key.

**Comment by bookchin** [comment]
Your are hitting this: https://github.com/Storj/storjshare-daemon/blob/master/lib/api.js#L59-L65

Which mean that either the file cannot be read, the comments cannot be stripped, or the json is invalid.

**Comment by jfnz** [comment]
json attached. This was generated using

`storjshare create --sjcx xxxxxxxxxxx--storage /mount/storj --size 1TB --rpcport 31337 --rpcaddress 127.0.0.1 --maxtunnels 10 --tunnelportmin 4000 --tunnelportmax 4010`

[storj.txt](https://github.com/Storj/storjshare-gui/files/994476/storj.txt)

**Comment by TheRoliYogi** [comment]
I have the same Problem on Ubuntu Server 16.04.2 LTS:

- JUst checked if the JASON is valid, and it is. 
- Copied the JSON File from a running installation and modified just the IP and Private KEY to make sure the file will work - same error.
- Tried both SNAP and "normal" installation on UBUNTU Server, both installations the same error.
- Storj Daemon is running
- I installed a new Server, same issue.
- I use the newest Version of Storj

ERROR:

Does anyone has any advice?

storjshare-start --config /home/roland/storj/node1/config/config.json

  failed to start share, reason: failed to parse config at /home/roland/storj/node1/config/config.json

**Comment by jytou** [comment]
I have the same problem here. Actually storj was working fine, I stopped it by simply closing the window and it hanged indefinitely. I had to [Ctrl]-C for it to stop. And now when I restart storj it acts as if it was the first time I was running it. And when I try to import the config, it says "failed to parse config at <file name>". Is there any way to fix this? My node has been running for a while.
