### ISSUE TITLE
Import Config fails with "invalid storage size" after Update to 5.0.1

### ISSUE THREAD

**Issue by BerChill** [Storj/storjshare-gui#586]
### Versions

- **GUI Version:** GUI 5.0.1
- **Operating System:** Microsoft Windows 10 Pro Version	10.0.14393 Build 14393

### Expected Behavior

After selecting the `settings.json` for importing a previous config the legacy configuration should be imported without errors.

### Actual Behavior

Storj Share does not import the legacy configuration throwing an "invalid storage size" exception - see screenshot. The documentation says to 
> Reduce the allocated space in the config/settings file and try the import again.
Unfortunately, there is no variable in `settings.json` called `allocated space` or similar. Which one shoud be changed? I guess it refers to the `size` variable but the one below `storage`, `usedspace` or `remainingspace`?

### Steps to Reproduce

1. have an older Version installed. Unfortunately I can't say when I installed Stroj but probably around the beginning of March.
2. Start Storj Share .... it will ask if I want to update and redirects to github releases upon confirming.
3. Download new version and execute confirming to close older version of Storj upon being asked.
4. Installer runs and finishes without problems.
5. Start Storj ... it will ask to run setup ... skip setup.
6. click "import config" and select `settings.json` from Storj Share Directory in AppData
7. confirm that you want to import legacy config
8. see screenshot

### Screenshots (Optional)

![storj-fail](https://cloud.githubusercontent.com/assets/18327444/25940924/f53d7ede-3637-11e7-91fe-522895dc77a3.JPG)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/546
