### ISSUE TITLE
Cannot add network drive 

### ISSUE THREAD

**Issue by eventwifi** [Storj/storjshare-gui#587]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
Add network drive as normal, with folder on network drive. Detects network drive folder available size. 
```

### Actual Behavior

Issues error " invalid directory "

yet every other application on the PC can access the network drive folder. 

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Attempt to add network drive based folder to Storjshare GUI as a drive for sharing.

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/569
