### ISSUE TITLE
libgtk-x11-2.0.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by cemsbr** [Storj/storjshare-gui#588]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1-3 (snap)
- **Operating System:** Archlinux

### Expected Behavior

Please describe the program's expected behavior.

GUI should be shown.

### Actual Behavior

```
~$ storjshare-gui  
/var/lib/snapd/snap/storjshare-gui/3/opt/storjshare/storjshare: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open s
hared object file: No such file or directory
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. snap install storjshare-gui --edge
2. storjshare-gui

### Notes
I tried installing gtk2 and reinstalling storjshare-gui, but the behavior didn't change:

```
$ locate libgtk-x11-2.0.so.0
/usr/lib/libgtk-x11-2.0.so.0
/usr/lib/libgtk-x11-2.0.so.0.2400.31
```

**Comment by MrFancyMonocle** [comment]
Have you tried installing the full GTK2 package; I believe libgtk-x11-2.0.so.0 is an individual dependency for it. May be a similar issue to: http://www.linuxquestions.org/questions/linux-software-2/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0-a-921435/

**Comment by cemsbr** [comment]
gtk2 was already installed.

**Comment by subins2000** [comment]
I got this exact same problem on Ubuntu 16.04. But `locate` shows that the file exists :
```
$ locate libgtk-x11-2.0.so.0
/home/simsu/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
/home/simsu/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.10
/home/simsu/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
/home/simsu/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0.2400.10
/snap/storjshare-gui/11/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
/snap/storjshare-gui/11/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30
/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0.2400.30
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30
```
