### ISSUE TITLE
Feature Request: Reaper scheduling

### ISSUE THREAD

**Issue by gbaker3** [Storj/storjshare-gui#591]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** Windows 10 Pro 64-bit v1607

### Expected Behavior

Please describe the program's expected behavior.

Using Storjshare as a farmer should not _significantly_ impact the user's PC performance. It should run in the background and the user should barely know it is running.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

I find when the reaper is clearing shards, it uses significant disk I/O resources. So much so that it makes my computer noticeably slower when running.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run storjshare-GUI
2. Monitor disk I/O when the reaper is running

My suggested solution would be to create an option where the user can set specific hours where the reaper is allowed to run. Being able to restrict the reaper routine to run overnight, for example, would limit the performance impact the end user sees. Or only have it run when the screen is off or screen saver is running would be another (more complicated) option. I would be happy with a schedule.

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/115
