### ISSUE TITLE
Text editors cause Failed to parse config file. 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#592]
### Versions

Replace the values below with your own:

- **GUI Version:** 5.0.1
- **Operating System:** Mac, windows, even Linux

### Expected Behavior

Please describe the program's expected behavior.

```
I edit the config file, then when i save and close the text editor all is good and i can start the node. 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
It appears that some text editors (e.g.  textedit in Mac) are either changing the file encoding when one saves the file after a change or are adding some rubbish invisible data  which leads to the `failed to parse config` error. This error is very hard to get rid of. Adding a GUI edit menu like in the old GUI will solve this issue (and is also much more user friendly). 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Edit a config file with say textedit in Mac (e.g. change allocation size) 
2. save the file
3. try to start the node

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by MeijeSibbel** [comment]
e.g. 
[9a94bf5c74d7fb6af92cb4e400a66f14016f97d9.json.txt](https://github.com/Storj/storjshare-gui/files/1006204/9a94bf5c74d7fb6af92cb4e400a66f14016f97d9.json.txt)

**Comment by tempestb** [comment]
To add to this.  It appears to be in this piece of code...

```
try {
config = JSON.parse(stripJsonComments(
readFileSync(configPath).toString()
));
} catch (err) {
throw new Error(`failed to parse config at ${configPath}`);
}
```

I think maybe this happens because the stripJsonComments method fails for some reason.  Or, possibly, there is a rights issue with readFileSync, although it appears that it already read the config in earlier parts of the code that would have failed if that was a problem.  So if it's not the ctrl codes, then there is probably an issue in stripJsonComments.

**Comment by bookchin** [comment]
It looks like you inserted an invalid first quotation mark in the `storageAllocation` value. Paste your config into a JSON validator and you'll see what I'm talking about. 

I'm going to close this, but if you'd like to open a feature proposal regarding an in-app config editor, that'd be great.
