### ISSUE TITLE
Upgrading Storj Share 4.1.1 to Storj Share 5.0.1 cannot import settings.json

### ISSUE THREAD

**Issue by sschutte** [Storj/storjshare-gui#594]
### Versions

Replace the values below with your own:

- **GUI Version:** 
```
Storj Share 4.1.1
Core Library 6.3.2
Protocol 1.1.0
Electron 1.4.15
Chrome 53.0.2785.143
```

- **Operating System:** Windows 

Edition ------> Windows 10 Pro 64 bit
Version -----> 1511
OS Build ---> 10586.873

![1491760261142 remmina-2017-5-17-0 13 55 824999](https://cloud.githubusercontent.com/assets/1301384/26148968/b8e56454-3af8-11e7-8f3a-0de2404b774b.png)

### Expected Behavior

```
I start the client, it prompts me to install the update/upgrade
I stop storj share.
I install the update.
I import the current settings.json file. 
My nodes are back online.
```

### Actual Behavior

```
Currently Storjshare 4.1.1 is running. 
I get the update prompt, click File -> Quit
Install the new client (5.0.1)
I am not a new user, I just want to import my settings...
I select the option to import my config:
```

![1491760261142 remmina-2017-5-17-9 49 36 750057](https://cloud.githubusercontent.com/assets/1301384/26149000/d8cad5f6-3af8-11e7-990e-6475915454ef.png)

```

I then get prompted to convert my file from the legacy format:

```

![1491760261142 remmina-2017-5-17-9 49 59 277014](https://cloud.githubusercontent.com/assets/1301384/26149025/f3e3ed32-3af8-11e7-8116-da015e3ca439.png)

```

Afterwards, two files are generated, each representing a node, however when trying to import them, both fail with the following error message:


```
![1491760261142 remmina-2017-5-17-9 50 22 440480](https://cloud.githubusercontent.com/assets/1301384/26149040/12403aec-3af9-11e7-92ba-849c97d80945.png)

```
As suggested in the storj community chat I have opened the settings.json file with Notepadd++ and set the encoding to UTF-8 without BOM, however importing still fails.

```

### Steps to Reproduce

1. As described above, when having version 4.1.1 installed and then installing version 5.0.1, import fails.

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/546
