### ISSUE TITLE
Node Oversharing by 3%

### ISSUE THREAD

**Issue by gep88** [Storj/storjshare-gui#595]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Please describe the program's expected behavior.

Expect the node to fill to 100% and stop incoming shards.

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Node surpasses 100% capacity and continues to collect shards, and has now passed 103%

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Open node and allow it to fill past capacity.
2. ...
3. ...

### Screenshots (Optional)

![image](https://cloud.githubusercontent.com/assets/21994139/26163322/ef89e084-3aee-11e7-9b46-066de5485d71.png)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/675
