### ISSUE TITLE
Windows NTP Suggestions

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#598]
Because Storj Network is considered a time sensitive application (similar to an ATM/Bank/Airport/etc) the following suggestions are recommended to be applied as part of the installation and/or configuration process of Storj Share GUI

The idea is to hopefully not have to rely on a third party client for the user to farm.  This will make things easier and "lighter" and less prone to mistakes.

Enable Windows Time Service
W32TM (or Windows Time)
Make sure the service is set to Automatic and started   (some user's configurations has this disabled)

w32tm command to perform
This adjusts the windows client to utilize pool.ntp.org peers
```
w32tm /config /manualpeerlist:"0.pool.ntp.org,0x8 1.pool.ntp.org,0x8 2.pool.ntp.org,0x8 3.pool.ntp.org,0x8" /syncfromflags:manual
```

Registry entries to adjust
MaxAllowedPhaseOffset 1 second -> (default is 300 or 5 minutes)
Max Poll 9 -> (this equates to 8.5 Minutes - default is 10 which is 17 minutes)
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Config]
"MaxAllowedPhaseOffset"=dword:00000001
"MaxPollInterval"=dword:00000009
```

Restart Windows Time Service

**Comment by bookchin** [comment]
FWIW, the upcoming core7/protocol2 work eliminates the need for NTP synchronized nodes.

**Comment by littleskunk** [comment]
https://github.com/Storj/core/issues/521
