### ISSUE TITLE
UPNP Concerns

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#599]
I am going to lump a few UPNP concerns here and feel free to break them apart as needed

1. UPNP Stomping (made that term up)
To define what I mean by UPNP stomping let me define my thoughts on UPNP, provide an example, and then provide the suggestion.

First, UPNP works to basically allow seamless and automatic port opening on your network. With this as a user I do not care what port is used I just want the application to open the port(s) it needs and then use them and then close them when done.

For example, lets say you have two Xbox Ones on your network.  With UPNP enabled the Xbox's will open individual dynamic ports so that you can connect to other users on xbox live for multiplayer games and then close them when done.  The ports that are dynamically opened are configured broad enough to allow for a multitude of Xbox's on the same network.

Looking at the storj clients, they require you set a static port (regardless of using port forwarding, upnp, tunneling).  While this is ok with one node on your network and UPNP enabled.  You run into a "stomping issue" when you have two different computers with two different nodes configured both for UPNP using default settings.   While the RPC port default (4000) is configured on both which is allowed (as long as the nodes are not on the same computer), when using UPNP on the same network, the router gets confused on who to assign the UPNP TCP port 4000 to.

Suggestion: When you are using UPNP, set a random port, and check to make sure it is not in use on the network and then utilize that for communication.  This will help the user as having one less item to set.  You will no longer have to ask the user for which port to use because first of all the user wont care (when using UPNP) and second you wont have to worry about conflicts (whether the nodes are on the same machine or different machines within the same network).

/////

UPNP - Hostname / Public IP

When utilizing UPNP, the default hostname is 127.0.0.1 (which is fine)
However in the logs of the client, it mentions it cannot get your public ip address / hostname (which is not fine) as when the client attempts to register with the bridge the client IP and port this will not work properly and will cause the client to not connect properly.

Suggestion: Fix identifying the public ip of the network the machine is on when using UPNP

/////

UPNP Select as Option

In order to utilize UPNP you must turn off Nat Traversal (by default it is).
However, what if a user wants to utilize tunneling but not UPNP?  Right now the user would have to leave the default setting and then turn UPNP off on their network and then when the client attempts to connect it will check UPNP, fail, then tunnel.

Suggestion: Provide one additional option to traverse via UPNP and allow the user to turn that on or off.
This will give the flexibility of selecting tunnel or UPNP.  (of course you could turn them all on to have failover/redundancy in case one fails).

**Comment by computeronix** [comment]
One more bug with UPNP

If you start the GUI (or the daemon) and then the router recognizes the UPNP request and opens up the request and everything is working.    Now if you restart the router, it clears all UPNP states.   Unless you also restart storj client, the client just attempts to connect and fails and it keeps doing this and never attempts to re-establish the UPNP connection...(so on the router you never see the port open up again either - until the client is restarted)

**Comment by AlexeyALeonov** [comment]
Better to add timer of renewal of the UPnP leasing.

**Comment by bookchin** [comment]
The latest release of kad-traverse periodically checks for this and will automatically adjust if it detects that the lease expired or the port in so linger reachable. 

https://github.com/kadtools/kad-traverse

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/600
