### ISSUE TITLE
Log files exceed 1Gb - no daily log recording.

### ISSUE THREAD

**Issue by ugofoscolo19** [Storj/storjshare-gui#603]
### Versions
SO: W10
GUI 5.0.1
Daemon 2.5.3
Core 6.4.2
Protocol 1.1.0

### Expected Behavior
Daily write a new .log;  delete older logs. 

### Actual Behavior
Log files exceed 1GB
17 Days log recording in a single file.

### Steps to Reproduce
Imported datas from prev. Storj version.
Running a node for 13/17days.

### Screenshots (Optional)
![image](https://cloud.githubusercontent.com/assets/29001063/26521878/ab8bf392-42c1-11e7-9cea-98c81ff7ea8f.png)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/120
