### ISSUE TITLE
Clicking on `Logs` to view logs does nothing. 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#607]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** Windows (32 and 64bit)

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by MeijeSibbel** [comment]
@bookchin ^

**Comment by bookchin** [comment]
@MeijeSibbel you know i get notified already for literally everything, right?
