### ISSUE TITLE
V5.1.0 is not working

### ISSUE THREAD

**Issue by mauroinagoki** [Storj/storjshare-gui#608]
### Versions

- **GUI Version:** v5.1.0
- **Operating System:** Windows 7

### Expected Behavior

Please describe the program's expected behavior.

```
After update this program to 5.1.0, i start drive but it turns off or stop. I try restarting but it is stopping too.
```

### Actual Behavior

```
Click in log but not appers log
```

**Comment by bookchin** [comment]
https://github.com/Storj/storjshare-gui/issues/607
