### ISSUE TITLE
I'm getting error on loading Storj-Share

### ISSUE THREAD

**Issue by trashMeNow** [Storj/storjshare-gui#611]
Storj Share 4.1.1
Core Library 6.3.2
Protocol 1.1.0
Electron 1.4.15
Chrome 53.0.2785.143- 
**Operating System:** Windows 10 Pro 64bit

### Expected Behavior

i'm unable to load storj-Share correctly.

here last part of log:
{info} [Thu Jun 01 2017 23:03:15 GMT+0200 (ora legale Europa occidentale)] clock is synchronized with ntp, delta: 301 ms
{info} [Thu Jun 01 2017 23:03:15 GMT+0200 (ora legale Europa occidentale)] resolving seeds from https://api.storj.io
{warn} [Thu Jun 01 2017 23:03:16 GMT+0200 (ora legale Europa occidentale)] Request failed, reason: not authorized on bridge to execute command { find: "contacts", filter: {}, sort: { lastSeen: -1 }, projection: {}, limit: 30 } - retrying(false)...
{error} [Thu Jun 01 2017 23:03:16 GMT+0200 (ora legale Europa occidentale)] Failed to discover seeds from bridge: not authorized on bridge to execute command { find: "contacts", filter: {}, sort: { lastSeen: -1 }, projection: {}, limit: 30 }
{warn} [Thu Jun 01 2017 23:03:16 GMT+0200 (ora legale Europa occidentale)] An error occurred. Restarting farmer [1bdbf9]...
{warn} [Thu Jun 01 2017 23:03:17 GMT+0200 (ora legale Europa occidentale)] you are not publicly reachable, trying traversal strategies...
{info} [Thu Jun 01 2017 23:03:17 GMT+0200 (ora legale Europa occidentale)] successfully traversed NAT via UPnP: 79.12.203.113:40616
{info} [Thu Jun 01 2017 23:03:17 GMT+0200 (ora legale Europa occidentale)] node created with nodeID df6091c55a4cdc5a4c9da9d83c9f798544f40496
{info} [Thu Jun 01 2017 23:03:17 GMT+0200 (ora legale Europa occidentale)] node bound and port mapped: 40616
{info} [Thu Jun 01 2017 23:03:17 GMT+0200 (ora legale Europa occidentale)] clock is synchronized with ntp, delta: 301 ms
{info} [Thu Jun 01 2017 23:03:17 GMT+0200 (ora legale Europa occidentale)] resolving seeds from https://api.storj.io
{warn} [Thu Jun 01 2017 23:03:18 GMT+0200 (ora legale Europa occidentale)] Request failed, reason: not authorized on bridge to execute command { find: "contacts", filter: {}, sort: { lastSeen: -1 }, projection: {}, limit: 30 } - retrying(false)...
{error} [Thu Jun 01 2017 23:03:18 GMT+0200 (ora legale Europa occidentale)] Failed to discover seeds from bridge: not authorized on bridge to execute command { find: "contacts", filter: {}, sort: { lastSeen: -1 }, projection: {}, limit: 30 }
{warn} [Thu Jun 01 2017 23:03:18 GMT+0200 (ora legale Europa occidentale)] An error occurred. Restarting farmer [1bdbf9]...
{warn} [Thu Jun 01 2017 23:03:19 GMT+0200 (ora legale Europa occidentale)] you are not publicly reachable, trying traversal strategies...
{info} [Thu Jun 01 2017 23:03:19 GMT+0200 (ora legale Europa occidentale)] successfully traversed NAT via UPnP: 79.12.203.113:24706
{info} [Thu Jun 01 2017 23:03:19 GMT+0200 (ora legale Europa occidentale)] node created with nodeID df6091c55a4cdc5a4c9da9d83c9f798544f40496
{info} [Thu Jun 01 2017 23:03:19 GMT+0200 (ora legale Europa occidentale)] node bound and port mapped: 24706
{info} [Thu Jun 01 2017 23:03:19 GMT+0200 (ora legale Europa occidentale)] clock is synchronized with ntp, delta: 302 ms
{info} [Thu Jun 01 2017 23:03:19 GMT+0200 (ora legale Europa occidentale)] resolving seeds from https://api.storj.io
{warn} [Thu Jun 01 2017 23:03:39 GMT+0200 (ora legale Europa occidentale)] Request failed, reason: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set metadisk1 - retrying(false)...
{error} [Thu Jun 01 2017 23:03:39 GMT+0200 (ora legale Europa occidentale)] Failed to discover seeds from bridge: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set metadisk1
{warn} [Thu Jun 01 2017 23:03:39 GMT+0200 (ora legale Europa occidentale)] An error occurred. Restarting farmer [1bdbf9]...
{warn} [Thu Jun 01 2017 23:03:41 GMT+0200 (ora legale Europa occidentale)] you are not publicly reachable, trying traversal strategies...
{info} [Thu Jun 01 2017 23:03:41 GMT+0200 (ora legale Europa occidentale)] successfully traversed NAT via UPnP: 79.12.203.113:36733
{info} [Thu Jun 01 2017 23:03:41 GMT+0200 (ora legale Europa occidentale)] node created with nodeID df6091c55a4cdc5a4c9da9d83c9f798544f40496
{info} [Thu Jun 01 2017 23:03:41 GMT+0200 (ora legale Europa occidentale)] node bound and port mapped: 36733
{info} [Thu Jun 01 2017 23:03:41 GMT+0200 (ora legale Europa occidentale)] clock is synchronized with ntp, delta: 303 ms
{info} [Thu Jun 01 2017 23:03:41 GMT+0200 (ora legale Europa occidentale)] resolving seeds from https://api.storj.io
{warn} [Thu Jun 01 2017 23:04:12 GMT+0200 (ora legale Europa occidentale)] Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...

**Comment by littleskunk** [comment]
Please update: https://github.com/Storj/storjshare-gui/releases/latest
