### ISSUE TITLE
Log file - too many open files

### ISSUE THREAD

**Issue by artos60** [Storj/storjshare-gui#612]
### Versions
GUI 5.1.0
Daemon 3.1.0
Core 6.5.0
Protocol 1.1.0
GUI 32 bit
Operating System: windows 10

### Expected Behavior

To be able to write log file 

### Actual Behavior
after 3-5 hours of normal working:
at GUI 5.1.0 i have information Error: EMFILE: too many open files, open LINK TO LOG FILE
screenshots:
![image](https://cloud.githubusercontent.com/assets/23109763/26702150/fecb07da-4723-11e7-98c0-c8b9d04dae08.png)

![image](https://cloud.githubusercontent.com/assets/23109763/26701116/256a0228-4720-11e7-8d7b-e25a1cd6eb69.png)

![image](https://cloud.githubusercontent.com/assets/23109763/26701125/2e73db96-4720-11e7-9a3b-86719559f465.png)

![image](https://cloud.githubusercontent.com/assets/23109763/26701134/330c9274-4720-11e7-9e9e-525f083000a4.png)

### PREVIOUS GUI:
![image](https://cloud.githubusercontent.com/assets/23109763/26701146/406dad68-4720-11e7-919c-37c97e39a041.png)

![image](https://cloud.githubusercontent.com/assets/23109763/26701149/43ab76a4-4720-11e7-8d80-6b87c3145046.png)

### Steps to Reproduce
wait few hours

### LOG FILE
[LOG_FILE.zip](https://github.com/Storj/storjshare-gui/files/1046066/LOG_FILE.zip)

**Comment by artos60** [comment]
at version 6.0.1 i didnt had this problem 
but at version 6.1.0 this appeard again,
so for now im trying to do loggerVerbosity: 1 instead of loggerVerbosity: 3

**Comment by Poilaucul** [comment]
Same here on:

GUI 6.1.0
Daemon 3.4.0
Core 6.6.0
Protocol 1.1.0

After almost 3 days of normal activity I got this error.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/666
