### ISSUE TITLE
Update GUI for new payout address format during transition

### ISSUE THREAD

**Issue by phutchins** [Storj/storjshare-gui#614]
We are currently in the process of migrating from SJCX which is based on Counterparty to STORJ which is based on Ethereum. We need to make the following updates in the GUI to make this possible.

- [x] Add a popup or some sort of notification telling users that they need to update their payout address (if its the old format) and give dates or a link to details (link coming soon)
- [x] Update Documentation here: https://github.com/Storj/storjshare-gui/blob/0e70ae89ecfd0cf2a4d910e3ac1d593233b46f34/app/views/share-wizard/wizard1.js#L44

**Comment by JukeboxRhino** [comment]
I just finished #615, it doesn't directly fix any of those issues but it does update the wizard to support Ethereum addresses. I'm thinking about trying to add a popup next.

**Comment by littleskunk** [comment]
Popup included in storjshare-gui v6.0.0. The Documentation is not updated.

**Comment by JukeboxRhino** [comment]
Documentation on the website has been updated, this can be closed now

**Comment by MeijeSibbel** [comment]
I think we can close this as it is already implemented

**Comment by littleskunk** [comment]
Still not 100 completed:

![image](https://user-images.githubusercontent.com/6333390/28438907-0f20168c-6da0-11e7-9146-7f5af9dc49ff.png)

**Comment by braydonf** [comment]
The link to "How to create a wallet" doesn't go to the section on how to create a wallet in the docs, but in otherwise up-to-date.

**Comment by braydonf** [comment]
The link is working okay mostly. However in Firefox it will go to the section and then jump back up (not sure what's up with that). I think we can consider this complete though.
