### ISSUE TITLE
OSX not accepting ETH address - only works with SJCX address

### ISSUE THREAD

**Issue by digidan** [Storj/storjshare-gui#625]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.0
- **Operating System:** OSX 10.12.5

### Expected Behavior

App should accept new ETH address and work once node restarts.
```

```

### Actual Behavior

After entering the ETH address, the nodes stop, upon trying to restart the UI says invalid payout address.  I tried restarting the app, doing it again no change.  When I change it back to the SJCX address it works just fine.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. start app after upgrading
2. enter new eth address
3. app stops node
4. when node restarts displays invalid payout address message
5. works when changed to SJCX address (should not, only eth should work)

### Screenshots (Optional)

[](https://dl.dropboxusercontent.com/u/1047613/Screen%20Shot%202017-06-20%20at%201.09.46%20PM.png)

**Comment by digidan** [comment]
Screenshot can be found here:  https://dl.dropboxusercontent.com/u/1047613/Screen%20Shot%202017-06-20%20at%201.09.46%20PM.png

**Comment by digidan** [comment]
Also here is config with private key redacted.  https://u1047613.dl.dropboxusercontent.com/u/1047613/f0572775c0e16f9a2d61111192ff7786528c2e6a%20copy.json

**Comment by littleskunk** [comment]
It is possible to have a running daemon process. Maybe from the old GUI. The new GUI will notice the already running daemon and not start a new one. That combination would throw the invalid payout address error.

It is very unlikely but at the moment the only explanation I have. I installed the latest GUI on my OSX VM and I was able to add and run a new farmer with your ETH address.

**Comment by digidan** [comment]
Restart solves the issue in this case, thank you!
