### ISSUE TITLE
Won't run Ubuntu 16

### ISSUE THREAD

**Issue by edimusrex** [Storj/storjshare-gui#626]
### Versions

Replace the values below with your own:

- **GUI Version:** v6
- **Operating System:** Ubuntu 16.06

### Actual Behavior

When running the storjshare-gui I get the following error 

> mkdir: cannot create directory '/run/user/0': Permission denied

I am running as root so this should not be an issue

**Comment by littleskunk** [comment]
Duplicate: #624
