### ISSUE TITLE
Storj isn't allocating my space

### ISSUE THREAD

**Issue by Borduni** [Storj/storjshare-gui#629]
### Versions

- **GUI Version:** v6.0.0
- **Operating System:** Windows 10 Pro

Storj isn't working correct since 3 days. I have run the client for 2 days and it only allocated 27.4MB on my HDD and 5.79MB on my USB stick. The ports are open (i checked them on yougetsignal.com).

Check out these scrennshots:
![screenshot_8](https://user-images.githubusercontent.com/24731809/27499997-a768f76e-5866-11e7-97e0-c61609665f93.png)
![screenshot_9](https://user-images.githubusercontent.com/24731809/27500013-b7e5a11e-5866-11e7-95ce-335c1466f268.png)

**Comment by Borduni** [comment]
Sorry that i haven't wrote this issue in the original basic scheme

**Comment by littleskunk** [comment]
I don't see any error message or logfile. -> Closed

If you need help please join us: https://storj.io/community.html
