### ISSUE TITLE
Comments should be posted at top of node-id.json file for each node

### ISSUE THREAD

**Issue by nerdatwork** [Storj/storjshare-gui#631]
### Versions

- **GUI Version:** v6
- **Operating System:** Windows 7

### Expected Behavior
The comments like
```  
// Determines how much detail is shown in the log:
  // 4 - DEBUG | 3 - INFO | 2 - WARN | 1 - ERROR | 0 - SILENT
  "loggerVerbosity": 3,

```
should be at the top of the node-id.json file which will help farmers choose log levels. Also could add more comments detailing what each entries mean. This would be ideal for farmers who are clueless and have to visit different channels to search for answers.
### Actual Behavior

There are no comments which makes the farmer search for answers on the community channels. If more definitions and  helpful comments are posted at top. This will save a lot of time for moderators. There could be more comments that stay permanently at the top of each node-id.json file explaining things inside the .json file like what each of the entries mean.
```

```

### Steps to Reproduce

1. ... Install version 6
2. ...Add a node and let it run for few mins
3. ... Click "Edit" option for the node and check top of the node-id.json file. There are no comments

### Screenshots (Optional)

NA

**Comment by littleskunk** [comment]
As far as I can see it should include the components here: https://github.com/Storj/storjshare-gui/blob/ae271f8e4774bf364e3cbb3003dfcbc40b09cf92/app/stores/share.js#L100

Somewhere later they get lost.
