### ISSUE TITLE
GUI generating weak/duplicate IDs?

### ISSUE THREAD

**Issue by florianfink** [Storj/storjshare-gui#633]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.0.0
- **Operating System:** Ubuntu 16.10

### Expected Behavior

Please describe the program's expected behavior.

```
When using storjshare-gui to add a new drive, storjshare should generate a unique ID/private key.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
storjshare-gui seems to generate IDs that are already in use.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install storjshare-gui using .deb on Ubuntu 16.10
2. Start the GUI and add a new drive
3. Request node id from storj API (https://api.storj.io/contacts/ID)
4. Returned data shows different IP address and port

IDs that were generated for me: 
- c2a83c881b2b1e694551e687787aa66fe1193be6
- aae4d2c4f816052eb90a9e4d584e7f0358a607eb

**Comment by littleskunk** [comment]
I don't see an issue here. Both nodeIDs are new. Not a single timeout and no responseTime. An old nodeID would have at least a responseTime.

**Comment by florianfink** [comment]
But why does the API return IP addresses that don't belong to me for both nodeIDs? Do I have a fallacy here?

**Comment by littleskunk** [comment]
A tunnel connection would have this effect. If your farmer was not able to open any port he would ask any other farmer to give him one of his open ports. Your nodeID will be listed with his ip and port.

You can see that here: https://api.storj.io/contacts?address=94.11.50.135&port=60125
That looks like a tunnel server and over time different farmer will use his ip and port to connect to the network.
