### ISSUE TITLE
GUI Upgrade 6.0.1 not working in Linux Mint

### ISSUE THREAD

**Issue by WilhelmGGW** [Storj/storjshare-gui#634]
- **GUI Version:** v6.0.1
- **Operating System:** Linux Mint 17.1

Program should load and run as normal

Program does not start after upgrade. Sometimes it throws up an empty window, but never goes farther. Sometimes, not even that.
![image](https://user-images.githubusercontent.com/5957623/27565900-e79130c6-5aa6-11e7-9894-a4d33efd164c.png)
Performs just like first release of 6.0.0 did, until littleskunk reworked the installer.

**Comment by alexeft** [comment]
Same in debian 8. Also, there was the same issue in version 6. Littleskunk solved it by recompiling after a library that was missing.

**Comment by littleskunk** [comment]
Please try again.

**Comment by alexeft** [comment]
There are no .deb packages in the release at https://github.com/Storj/storjshare-gui/releases/tag/v6.0.1

**Comment by littleskunk** [comment]
Now there are ;)

**Comment by alexeft** [comment]
Selecting previously unselected package storjshare.
(Reading database ... 132436 files and directories currently installed.)
Preparing to unpack storjshare-gui.amd64.deb ...
Unpacking storjshare (6.0.1) ...
dpkg-deb: error: unexpected end of file in archive member header in storjshare-gui.amd64.deb
dpkg: error processing archive storjshare-gui.amd64.deb (--install):
 subprocess dpkg-deb --fsys-tarfile returned error exit status 2
Errors were encountered while processing:
 storjshare-gui.amd64.deb

**Comment by littleskunk** [comment]
Stupid me. My build server is running out of drive space :(

**Comment by littleskunk** [comment]
Please try again.

**Comment by alexeft** [comment]
This time it installed, but it still has the same problem. I have to start it twice for the gui to appear, and then, it's blank.

**Comment by littleskunk** [comment]
I am sorry but now it must be a problem on your system. I setup ubuntu 16.04 and installed nothing else. Storjshare was working fine.

Please call it from command line `/opt/storjshare/storjshare` and show me the error message you get.

**Comment by alexeft** [comment]
I get the same 'GLIBCXX_3.4.21' not found error that existed in the initial compilation of version 6.

**Comment by WilhelmGGW** [comment]
Newest installer still not working for me, either.  Linux Mint 17.1

**Comment by trotskylenin** [comment]
Same here in Ubuntu 14.04.1. Fixed the GLIBCXX_3.4.21 following these steps:
https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
But still showing the blank page when opening the GUI from desktop or terminal.

**Comment by trotskylenin** [comment]
Well, I could open the GUI and see something but when i try to start my drive it fails.
This is what the logs say:

> /opt/storjshare/storjshare: relocation error: /tmp/.org.chromium.Chromium.gyhHtM: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

Evidently the issue is not fixed completely.

**Comment by trotskylenin** [comment]
I managed to make it work by doing some nasty shit.
I replaced manually the libstdc++.so.6 library with another installed with a snap.
This is by no means a good way to fix this anyway.

**Comment by littleskunk** [comment]
Ok I will try it with Ubuntu 14.04 and lets see what happens. Meanwhile please use GUI v6.0.0. If nothing works I can still use my backup build server but the difference between v6.0.0 and v6.0.1 are not critical and I have time to understand whats going on here.

**Comment by littleskunk** [comment]
Found out whats wrong. Electron binaries are build against the current libraries. If I use debian 9 as my build server it will not run on old linux system.

Now I am forced to use the oldest possible linux distribution to support them all.
