### ISSUE TITLE
White screen after update from 6 to 6.1

### ISSUE THREAD

**Issue by therampagerado** [Storj/storjshare-gui#637]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.1
- **Operating System:** Win 7 64

### Expected Behavior

Show the full interface
```

```

### Actual Behavior

Program is starting. I'm getting 4 processes live and the screen is white. Only the menu tabs are visible
```

```

### Steps to Reproduce

Can't say. On one of my computers everything is OK, on the other I have this issue.

**Comment by littleskunk** [comment]
Please open Storjshare from command line.

Open cmd and call `"C:\Program Files\Storj Share\Storj Share.exe"`

Do you get any usefull error message?

**Comment by therampagerado** [comment]
Unfortunately not.

Only when I remove the configs the app starts. But otherwise it hangs on this white screen.

**Comment by littleskunk** [comment]
Please upload your config (without private key!)

**Comment by therampagerado** [comment]
It is OK now. I didn't do anything. Probably it was loading HDD contents of shares or something like that.
