### ISSUE TITLE
Very high RAM usage

### ISSUE THREAD

**Issue by ajthemacboy** [Storj/storjshare-gui#642]
### Versions

Replace the values below with your own:

- GUI Version: 6.1.0, Daemon 3.4.0, Core 6.6.0, Protocol 1.1.0
- Operating System: Windows 10

### Expected Behavior

```
Normal RAM usage, lower than 2GBs
```

### Actual Behavior

```
RAM usage increased for several hours, reaching a maximum of 10.5 GBs. I tried to take a dump in Task Manager so you could have it, and that caused it to crash, so I restarted the app and RAM usage is slowly increasing again. I will comment here if it gets high again.
```

### Screenshots

https://drive.google.com/a/eyestra.in/file/d/0B6AmcbVDdoMsNmNBTGxWQmxzYzQ/view?usp=drivesdk

**Comment by ajthemacboy** [comment]
RAM usage is increasing again: https://drive.google.com/a/eyestra.in/file/d/0B6AmcbVDdoMsRjFMMG9MeHRaRDA/view?usp=drivesdk

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/114
