### ISSUE TITLE
Storj GUI breaks GPU overclock

### ISSUE THREAD

**Issue by tsourick** [Storj/storjshare-gui#647]
### Versions

- **GUI Version:** v6.2.0
- **Operating System:** Windows 7

### Expected Behavior

No interfere with overclocking software while mining.

### Actual Behavior

Overclocked GPU connected to display switches to default core clock upon Storj GUI launch. It is due to underlying Chrome using acceleration, well-known problem, i believe. Can be fixed temporarily if open NVIDIA control panel whith rotating logo (which obviously forces full throttle again). Could not find an option in the GUI to disable accel.

### Steps to Reproduce

1. Run mining software
2. Run afterburner
3. Overclock GPU connected to display - core clock goes up
4. Run Storj GUI - core clock goes back to defaults (while memory clock still overclocked)

**Comment by littleskunk** [comment]
duplicate: https://github.com/Storj/storjshare-gui/issues/486
