### ISSUE TITLE
Incorectly closing the GUI causes "invisible" corruption 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#649]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.2.0
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
When shutting down windows OS without properly stopping Storj Share, a "invisible" corruption occurs. The node will not send anymore OFFER messages and will stick at 0 contracts. However there are no visible corruption errors in the log like one would expect. 

The only way to solve it is delete the entire database, then when Storj Share starts it will automatically collect more "contracts".

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Log level debug?

**Comment by MeijeSibbel** [comment]
[1d218942cf3fe97a3e5b540e5ff4ed3286a114bc_2017-7-20.txt](https://github.com/Storj/storjshare-gui/files/1163601/1d218942cf3fe97a3e5b540e5ff4ed3286a114bc_2017-7-20.txt)

You can enter th VPS if you wish:

500 413 580
951kbf

**Comment by littleskunk** [comment]
The drive is simply full
```
{"level":"debug","message":"received contract offer...","timestamp":"2017-07-20T20:24:10.258Z"}
{"level":"debug","message":"renter is whitelisted: true","timestamp":"2017-07-20T20:24:10.258Z"}
{"level":"debug","message":"active transfers 0 is less than offerBackoffLimit 4: true","timestamp":"2017-07-20T20:24:10.258Z"}
{"level":"info","message":"replying to message to bca85bbb8c28bededf2988149f83277b94bd97b2","timestamp":"2017-07-20T20:24:10.258Z"}
{"level":"debug","message":"not waiting on callback for message bca85bbb8c28bededf2988149f83277b94bd97b2","timestamp":"2017-07-20T20:24:10.267Z"}
{"level":"debug","message":"no storage item available for this shard","timestamp":"2017-07-20T20:24:10.269Z"}
{"level":"debug","message":"negotiator returned: true","timestamp":"2017-07-20T20:24:10.269Z"}
{"level":"debug","message":"we have enough free space: false","timestamp":"2017-07-20T20:24:10.280Z"}
{"level":"debug","message":"not sending an offer for the contract","timestamp":"2017-07-20T20:24:10.280Z"}
```

**Comment by MeijeSibbel** [comment]
![image](https://user-images.githubusercontent.com/11735738/28437509-cbfca3a0-6d92-11e7-872a-1efc0c58396f.png)

**Comment by MeijeSibbel** [comment]
its not full. not even close

**Comment by littleskunk** [comment]
`"storageAllocation": 20737418240,` The drive is more than full. You set a limit of 207MB. If I increase the limit the farmer is sending OFFER again.

**Comment by littleskunk** [comment]
Something is wrong with `"storageAllocation": 20737418240,`

If I change it to 20GB the farmer is sending OFFER again. Looks like a problem in core.

**Comment by MeijeSibbel** [comment]
I didn't change anything in the config, maybe core is messing up the storage allocation?

**Comment by MeijeSibbel** [comment]
Please open issue in core

**Comment by littleskunk** [comment]
Sorry it is getting late for me. I am not sure if that is deamon or core. All I know is that `"20737418240B"` is not sending OFFER. `"20737418KB"` is sending OFFER.

For the moment I better reopen the issue and go on tomorrow.

**Comment by Losiara** [comment]
Have the same issue in daemon-mode too.

[a97eca23d8f079d7dfe43567ac957f8d91356af0_2017-7-21.txt](https://github.com/Storj/storjshare-gui/files/1165829/a97eca23d8f079d7dfe43567ac957f8d91356af0_2017-7-21.txt)

```{"level":"debug","message":"we have enough free space: false","timestamp":"2017-07-21T12:49:18.139Z"}```

**Comment by littleskunk** [comment]
Lets track this in https://github.com/Storj/storjshare-daemon/issues/207
