### ISSUE TITLE
Deceptive site ahead on the download page

### ISSUE THREAD

**Issue by Vacilando** [Storj/storjshare-gui#655]
When trying to download the win64 exe from https://github.com/Storj/storjshare-gui/releases/tag/v6.4.0 I get the following message:

> Deceptive site ahead
> Attackers on github-production-release-asset-2e65be.s3.amazonaws.com may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards).

![image](https://user-images.githubusercontent.com/147258/28562577-1b6981a4-7123-11e7-8a83-136575319590.png)

**Comment by littleskunk** [comment]
False positive. We have to wait for Google to fix it.

**Comment by littleskunk** [comment]
Looks like they solved it.
