### ISSUE TITLE
Distribution node

### ISSUE THREAD

**Issue by HyperCriSiS** [Storj/storjshare-gui#656]
Hi,

I'm running STORJ on a server in a datacenter.
On this server I cannot spare much space, only several hundred GBs.
But this server has a 1Gbit connection.

So I thought if it could be more useful for the STORJ network to use such configurations for nodes that currently went offline to distribute the data **very** **fast** to **many** nodes.

Would that make any sense?

Regards,
Hyper

**Comment by littleskunk** [comment]
I don't see any issue here. -> Closed

Better ask your question on https://community.storj.io/

**Comment by HyperCriSiS** [comment]
Of course, this is not an issue. It is a feature suggestion and I did not know where to report else.
