### ISSUE TITLE
ERROR: ... failed to start share, reason: failed to parse config at ...

### ISSUE THREAD

**Issue by TheRoliYogi** [storj/storjshare-gui#657]
### Versions (newest from 25.07.2017)

Replace the values below with your own:

- **Operating System:** Ubuntu 16.04.2 LTS Server
- ****I USE ONLY CLI ON MY SERVER**

### Expected Behavior

Please describe the program's expected behavior.

Start Storjshare Node: 

storjshare-start --config /home/roland/storj/node1/config/config.json

### Actual Behavior

COMMAND:
storjshare-start --config /home/roland/storj/node1/config/config.json

ERROR: 
  failed to start share, reason: failed to parse config at /home/roland/storj/node1/config/config.json

- Just checked if the JASON is valid, and it is. 
- Copied the JSON File from a running installation and modified just the IP and Private KEY to make sure the file will work - same error.
- Tried both SNAP and "normal" installation on UBUNTU Server, both installations the same error.
- Storj Daemon is running
- i tried different folders within user context and the root path as well as 777 folder and file permission.
- I installed a new Server, same issue.
- I use the newest Version of Storj

Does anyone has any advice?

### Steps to Reproduce

Install new Ubuntu Server 16.04.2 LTS and i got the same error... Could be a Permission/JSON or SERVER Error.

**Comment by littleskunk** [comment]
Please upload your config file. Remove private key and payout address.

**Comment by TheRoliYogi** [comment]
{
  "paymentAddress": "0xPRIVAT",
  "opcodeSubscriptions": [
    "0f01020202",
    "0f02020202",
    "0f03020202"
  ],
  "maxOfferConcurrency": 3,
  "bridgeUri": "https://api.storj.io",
  "seedList": [],
  "rpcAddress": "MY PUBLIC IP WITHOUT ANY PROXY AND OPEN PORTS",
  "rpcPort": 4001,
  "doNotTraverseNat": true,
  "maxTunnels": 3,
  "maxConnections": 150,
  "tunnelGatewayRange": {
    "min": 4001,
    "max": 4003
  },
  "joinRetry": {
    "times": 3,
    "interval": 5000
  },
  "offerBackoffLimit": 4,
  "networkPrivateKey": "PRIVAT KEY",
  "loggerVerbosity": 3,
  "loggerOutputFile": "/home/roland/storj/node1/log/",
  "storagePath": "/home/roland/storj/node1/data",
  "storageAllocation": 120870912000,
  "enableTelemetryReporting": true
}

**Comment by TheRoliYogi** [comment]
i tried the same with 

"storageAllocation": "120GB",

**Comment by TheRoliYogi** [comment]
Filename = config.json

**Comment by TheRoliYogi** [comment]
And it even happens when i am using the GUI Version on this Server. 
So, it is possible a Problem with the Version von JSON.
How can i check the Version of JSON and how can i make sure to have the right version to parse that file? I am nearly 100% sure that it has to do with the installation of JSON.

When i typ into the console, i get the Version 9.0.6 - Is that a supported Version? How can i check the Version of JSON without installing it?

npm install -g json

/home/roland/.nvm/versions/node/v6.11.1/bin/json -> /home/roland/.nvm/versions/node/v6.11.1/lib/node_modules/json/lib/json.js
/home/roland/.nvm/versions/node/v6.11.1/lib
└── json@9.0.6

**Comment by TheRoliYogi** [comment]
I updated to the newest Version 6.4.0 and the same issue occured.

**Comment by jytou** [comment]
Your editor might have added a UTF8 BOM at the beginning of the file, and storj doesn't seem to like that very much. To check if you do have a BOM at the beginning of the file, try this command out:
>head -c 3 <your-config-file> | hexdump -C
If the result is something like:
>00000000  7b 0a 20                                          |{. |
00000003
then there is no BOM.
If the result is something like:
>00000000  ef bb bf                                          |...|
00000003
then you have a BOM (the signature is ef bb bf).
To remove the BOM, just open the file with vi and issue the following commands:
>:se nobomb
:wq
After that, the file will no longer have a BOM and storj should be able to read it again.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
