### ISSUE TITLE
Are the GBs of log files really necessary?

### ISSUE THREAD

**Issue by Deozaan** [Storj/storjshare-gui#661]
### Versions

Replace the values below with your own:

- **GUI Version:** 6.4.0
- Daemon 3.5.5
- Core 6.8.0
- Protocol 1.1.0
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
It shouldn't write GBs worth of data into an obscure directory on my OS drive. At the very least I should be able to configure where this huge amount of data is stored on my device. But ideally it would automatically delete old log files or find some way to keep the storage space of logfiles from ballooning out of control like this.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Storj writes GBs of data into an obscure directory on my OS drive. It doesn't seem to care how much drive space these log files use up, and it provides no means of configuring where they are stored.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run Storjshare GUI for a couple of months
2. ???
3. Profit!

### Screenshots (Optional)

![storj logs](https://user-images.githubusercontent.com/227734/28751579-9350e042-74c8-11e7-8bb5-0fd816e93501.png)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
You can change the loglevel for each node and you can delete old logfiles if you don't need them anymore.

**Comment by janpieterz** [comment]
I had a node crash because Storj Share had happily written over 20GB to a small SSD, blocking Windows.
