### ISSUE TITLE
Move storjshare-daemon outside of electron into it's own system service process

### ISSUE THREAD

**Issue by ElanHasson** [Storj/storjshare-gui#666]
### Versions
- **GUI Version:** all
- **Operating System:** all

### Expected Behavior

After it is configured, storjshare-gui should not be required to run in order for a node to be online.

### Actual Behavior

storjshare-gui should be able to farm after a machine reboots. Currently, farming only occurs when the storjshare-gui is running. This is because storjshare-daemon is hosted within the node process contain in the electron package.

This is contributes to overall network instability as machines reboot all the time for various reasons (windows updates for example) and the user isn't always around to login and ensure storjshare-gui is running.

### Proposed Solution

As part of the installation of storjshare-gui, a system service should be configured to host the storjshare-daemon so that farming can continue even if the storjshare-gui app isn't running.

1) provide option in nsis to use "standard install", which runs within electron <-- current state
2) provide option in nsis to use "service install", which GUI talks to installed farmer service on local host
3) provide option to only install farmer service on machine
4) in GUI, allow to configure farming service ip/port for RPC
5) in GUI, gather all nodes from all configured farming services and display as normal perhaps with farming node ip/port as a new column

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run storjshare-gui
2. Reboot your machine and do not login OR exit storjshare-gui
3. Observe that your farming node is offline.

**Comment by braydonf** [comment]
So to have the daemon not dependent on the gui running, and the daemon can have a systemd or similar script to keep it running? How that applies to multiple OS might be more complicated, what about a "start on boot" option?

**Comment by ElanHasson** [comment]
You could have the option, but *how* would it start?

For example, on the windows side, that can't really happen unless it's a service, otherwise you could have it start when the user logs in. While you *could* have it run GUI as a service on boot, you wouldn't have access to the UI without a client application that connects to it.

**Comment by littleskunk** [comment]
You can install storjshare-daemon, add a cronjob and maybe a watchdog script to keep daemon and nodes online and at the end start storjshare gui and connect to the already running daemon.

Once upon a time we had a setting to start the GUI on user login. We refactored the GUI and this option was not working anymore. We will fix that with https://github.com/Storj/storjshare-gui/issues/564
