### ISSUE TITLE
Unable to increase share size

### ISSUE THREAD

**Issue by Pandemik** [Storj/storjshare-gui#668]
### Versions

Replace the values below with your own:

CLI daemon 3.5.5, core 6.8.0, Protocol 1.1.0
- **Operating System:** Centos 7

### Expected Behavior

Please describe the program's expected behavior.

Modify config file to go from 300GB share to 1TB

```

### Actual Behavior

After increasing 300GB share (94% full) to 1TB, response from storjshare was a number of bytes were missing. If I decrease from 1TB to 800GB, the missing number of bytes was lower. I was only able to increase share size by 100GB (total: 400GB)
```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... set config to 300GB, fill to 94% and try to increase the size
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
You only have 100GB free space + 300GB used space = 400GB allowed for storjshare. If you try 1TB it should display an error message that 1TB is to high. 600GB are missing. I don't see any issue here. Works as expected.

**Comment by Pandemik** [comment]
I have 2tb available to assign to storj. I increased my share space from
300gb to 1tb and it threw an error. I could only increase it by 100gb to
make the total share space 400gb.

**Comment by Pandemik** [comment]
400gb share was running fine.

I edited config file to make the space to lease to the network = 1000GB and
got this:

  failed to start share, reason: invalid storage size: 607458342581 bytes
missing.

I edited the config file to lease 500GB and got this:
  failed to start share, reason: invalid storage size: 70587430581 bytes
missing

I edited the config back to 400GB and it started working fine.

I have over 2 TB free on this disk

**Comment by littleskunk** [comment]
full `df -k` output please and your storage location.

**Comment by Pandemik** [comment]
[matt@Mvpn ~]$ df -k
Filesystem          1K-blocks      Used Available Use% Mounted on
/dev/mapper/cl-root  52403200   6454260  45948940  13% /
devtmpfs              3989940         0   3989940   0% /dev
tmpfs                 4005528       172   4005356   1% /dev/shm
tmpfs                 4005528      9120   3996408   1% /run
tmpfs                 4005528         0   4005528   0% /sys/fs/cgroup
/dev/sda1             1038336    232440    805896  23% /boot
/dev/mapper/cl-home 466511300 315963316 150547984  68% /home
tmpfs                  801108        16    801092   1% /run/user/42
tmpfs                  801108        16    801092   1% /run/user/1000


Storage location is /home/matt/Node_1

**Comment by Pandemik** [comment]
Also, this is a virtual machine with 2TB available, thin provision

**Comment by Pandemik** [comment]
Thin provisioning is probably the issue, actually.

**Comment by littleskunk** [comment]
Your OS is not reporting 2TB free space. Nothing we can fix for you.

**Comment by Pandemik** [comment]
No worries, at least I know where the issue is now. Thanks!
