### ISSUE TITLE
Storjshare Drive Overage / Corruption Issue Still Occuring 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#669]
### Versions

Replace the values below with your own:

- **GUI Version:** latest
- **Operating System:** windows

### Expected Behavior

Please describe the program's expected behavior.

```
Storj Share GUI respects the allocated size
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Storj share fills the node beyond the allocated space: https://www.reddit.com/r/storj/comments/6stb7u/storjshare_drive_overage_corruption_issue_still/
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/675
