### ISSUE TITLE
Incorrect "invalid Storage size error"

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#670]
### Versions

Replace the values below with your own:

- **GUI Version:** latest
- **Operating System:** OSX

### Expected Behavior

Please describe the program's expected behavior.

```
User is able to run the node as there is enough free space
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
User is not able to run or import the node due to the incorrect "invalid storage size" error.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 

<img width="1203" alt="screen shot 2017-08-12 at 15 42 09" src="https://user-images.githubusercontent.com/11735738/29241382-7be97470-7f70-11e7-9908-653480cd533c.png">

<img width="377" alt="screen shot 2017-08-12 at 15 43 20" src="https://user-images.githubusercontent.com/11735738/29241381-7be8e1a4-7f70-11e7-8331-fd57b54ce568.png">

![screen shot 2017-08-12 at 15 35 29](https://user-images.githubusercontent.com/11735738/29241391-b07ca5e0-7f70-11e7-946d-41e31baad652.png)

<img width="335" alt="screen shot 2017-08-12 at 15 36 00" src="https://user-images.githubusercontent.com/11735738/29241383-7beadc2a-7f70-11e7-8be4-c19068e0ac4c.png">

<img width="377" alt="screen shot 2017-08-12 at 15 38 33" src="https://user-images.githubusercontent.com/11735738/29241385-7bec47fe-7f70-11e7-9261-2463e21162e3.png">

**Comment by littleskunk** [comment]
Please try 1B.

**Comment by littleskunk** [comment]
```
df -k
Filesystem                        1024-blocks      Used Available Capacity iused      ifree %iused  Mounted on
/dev/disk1                          243810304 222222688  21331616    92% 1434602 4293532677    0%   /
devfs                                     185       185         0   100%     640          0  100%   /dev
map -hosts                                  0         0         0   100%       0          0  100%   /net
map auto_home                               0         0         0   100%       0          0  100%   /home
localhost:/U0Oak77C8As5sa00xUWUNc   243810304 243810304         0   100%       0          0  100%   /Volumes/MobileBackups
/dev/disk2s1                         31627264  10089344  21537920    32%  315292     673060   32%   /Volumes/STORJ
/dev/disk3s1                        488370176  11580032 476790144     3%   90469    3724923    2%   /Volumes/STORJ-500
```

**Comment by simon66** [comment]
Hi @littleskunk 
I'm also having this issue. I have plenty of space yet it complains that I'm a couple of bytes short.
Based on assumption, 'storageAllocation' on the json is constantly changed to reflect the new hdd size (as shares are being accepted). What happens is that new shares gets accepted yet the the json is not saved. When you shutdown storj share or reboot your system, storj share complains about invalid storage share (I could be wrong)

I'm running Windows 7 x64 Home Premium and Windows 10 Pro and both OS are having the same issue.

**Comment by littleskunk** [comment]
@simon66 no that assumption is not correct. Storjshare will not change any config values.

The implementation is simple. Throw an error if free space + used space < storageAllocation. 

On Linux and OSX the free space has an issue. That could be the reason for this issue as well. More details here: https://github.com/Storj/storjshare-daemon/issues/235

Lets try again as soon as this one is fixed.
