### ISSUE TITLE
offers % goes over 100%

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#672]
### Versions

Replace the values below with your own:

- **GUI Version:** latest
- **Operating System:** windows

### Expected Behavior

Please describe the program's expected behavior.

```
offer % < 100%, **always**!
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
it goes over 100%
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 
![pic](https://user-images.githubusercontent.com/11735738/29243034-d3f10ed6-7f8d-11e7-8873-79f6e169bbc1.png)

**Comment by littleskunk** [comment]
That is expected. Restarting the GUI will reset the OFFER counter but not the queued OFFER on the bridge. The bridge will send mirror shards but they belong to old OFFER. If the bridge is sending mirrors shards faster than the farmer can send new OFFER it will be displayed as 100% or more.

**Comment by MeijeSibbel** [comment]
If its normal or not does not matter, then the display is incorrect, please reopen, change the title if needed.

**Comment by littleskunk** [comment]
Will be fixed with https://github.com/Storj/storjshare-daemon/issues/231
