### ISSUE TITLE
Hole punching not persistent through reboot

### ISSUE THREAD

**Issue by peterjkrey** [Storj/storjshare-gui#673]
### Versions

- **GUI Version:** v1.0.3
- **Operating System:** Ubuntu 16.04

### Expected Behavior

Please describe the program's expected behavior.

Hole punching using UDP should be re punched on application restart.

### Actual Behavior

Returned to default port 4000 uPNP.

### Steps to Reproduce

1. Start app
2. Select checkbox to restart share

**Comment by littleskunk** [comment]
GUI version 1.0.3 is far away from the latest version.
