### ISSUE TITLE
invalid storage size: 634852374 bytes are missing

### ISSUE THREAD

**Issue by rollingmonkey** [Storj/storjshare-gui#674]
### Versions

GUI 6.4.0
Daemon 3.5.5
Core 6.8.0
Protocol 1.1.0
Windows 10 64bit
### Expected Behavior

Getting error, when stopping and starting Storj Services.

invalid storage size: 634852374 bytes are missing

### Actual Behavior
do have lots
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. select service and restart.
2. will get error invalid storage size: 634852374 bytes are missing

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Please run `wmic logicaldisk get size,freespace,caption` and show us what you get.

**Comment by rollingmonkey** [comment]
Here is required details;

wmic logicaldisk get caption,description,drivetype,providername,volumename
Caption  Description       DriveType  ProviderName  VolumeName
C:       Local Fixed Disk  3                        1-OS
E:       Local Fixed Disk  3                        Storj2
N:       Local Fixed Disk  3                        Storj1

C:\Windows>wmic logicaldisk get size,freespace,caption
Caption  FreeSpace      Size
C:       24622522368    127441825792
E:       2969032916992  3000457166848
N:       2976296730624  3000457166848

**E:\ Drive**
Size 3TB .. i have assigned maximum but after error i have to reduce so current allocated size is:
"storageAllocation": "**2999565052784B**"

**N:\ Drive**
Size 3TB .. i have assigned maximum but after error i have to reduce so current allocated size is:
"storageAllocation": "**2999726424661B**"

Thanks.

**Comment by littleskunk** [comment]
Works as expected. The error message is correct. Reduce the storageAllocation and you can start.

**Comment by rollingmonkey** [comment]
What you are suggesting is workaround not a solution (and I am doing it from last 3-4 days). Every time services restart, I had to reduce the size and a day is not far when HDD will have no space to reduce.

Kindly reconsider.

Thanks.
