### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by drygoatair** [Storj/storjshare-gui#675]
### Versions

Replace the values below with your own:

- **GUI Version:** 
GUI 6.4.0
Daemon 3.5.5
Core 6.8.0
Protocol 1.1.0
- **Operating System:**
Windows 10

### Expected Behavior

Please describe the program's expected behavior.

Start all my nodes at program launch.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Does not start one node. Drive where share is on had a disconnect at one point. Log tells me this:

{"level":"info","timestamp":"1502647495265","message":"Log file created."}
{"level":"warn","message":"your address is public and traversal strategies are disabled","timestamp":"2017-08-13T18:05:30.047Z"}

events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: E:\storjstack\contracts.db/MANIFEST-001455: The system cannot find the file specified.

    at C:\Program Files\Storj Share\resources\app\node_modules\levelup\lib\levelup.js:125:34
    at C:\Program Files\Storj Share\resources\app\node_modules\abstract-leveldown\abstract-leveldown.js:39:16

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Disconnect drive when storj share is running
2. Reconnect drive

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
dissconnect the drive while storjshare is running is not a good idea. Now the database is currupted. Nothing storjshare-gui can solve for you.

Please take a look at: https://github.com/Storj/kfs/issues/55

**Comment by drygoatair** [comment]
@littleskunk If I can't repair my db, how should I proceed? Delete Storj data and create a new node?

**Comment by littleskunk** [comment]
This is still the wrong issue. Better use the KFS issue!
