### ISSUE TITLE
Error Assertion Failed

### ISSUE THREAD

**Issue by ne0ark** [Storj/storjshare-gui#676]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.4.0
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
No error
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Assertion Failed. See screenshot below.
```

### Screenshots (Optional)

![storj share_2017-08-14_08-12-29](https://user-images.githubusercontent.com/660607/29271651-8c5cfda8-80ca-11e7-9e75-a76d6da198ee.png)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-gui/issues/463
