### ISSUE TITLE
Storj take all Internet Connections

### ISSUE THREAD

**Issue by SiRomain** [Storj/storjshare-gui#678]
### Versions

Replace the values below with your own:

GUI 6.4.0
Daemon 3.5.5
Core 6.8.0
Protocol 1.1.0

I run 8 Storj node on a Windows 10 system with i7-3770 and 16 GB RAM. I use PC local disks and a NAS synology to store Storj datas.

### Expected Behavior

NA

### Actual Behavior

This morning when i tried to used my PC, I could not access Internet anymore (no more web , mails, ....).  

 - When the problem occurs, the first thing I did was to reboot my Internet router. It didn’t solve the problem. So, for me, it is not a router issue.

 - There was still traffic between StorjShare and the Internet (and my NAS): I could see that on my internet monitor (Networkx). So, I guess this cannot be a crash of the Internet driver/adapter.

 - And last, to solve the issue I only had to stop StorjShare. I didn’t had to reboot my PC. It is like if StorjShare had used all resources of something in Windows. But I don’t know what is this resource and if it is possible to raise it in Windows Registry.

### Steps to Reproduce

NA

### Screenshots (Optional)

NA

**Comment by littleskunk** [comment]
Did I understand it correct? You are running 8 nodes and they all point to one network drive?

**Comment by SiRomain** [comment]
- 2 nodes point on a local PC disk
 - 6 nodes point on a NAS with 3 disks

**Comment by 4Ykw** [comment]
What is your contracted ISP connection? 10Mbps/1Mbps?

**Comment by SiRomain** [comment]
It is 1 Gbps (mesured speed = 940Mbps downstream, 250 Mbps upstream)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/115

The problem is that after 24hours all 6 nodes will run the shard reaper at the same time and they all have to read from a network share.

Anyway even if we disable the reaper this is not a good idea. Long term better install and run storjshare on the nas. The aditional network communication will need to mouch resources.

**Comment by SiRomain** [comment]
@littleskunk 
On the Internet monitor I  was using "only" 50 to 200 Mbps (I ethernet network is GBps). So, I guess the ethernet network was not saturated.
My NAS is quite old (synology DS411) and has only 512MB memory. I dont think i can host StorjShare.

**Comment by littleskunk** [comment]
Remove the hard drives and install them on the PC would work as well.

The network drive is to slow for 6 nodes running the reaper job at the same time.

**Comment by SiRomain** [comment]
No more slots in the PC ....
How many nodes can I run from my PC with the drives on the NAS : 1, 2, more ?

**Comment by littleskunk** [comment]
My advice would be avoiding network shares even for only one node.

**Comment by SiRomain** [comment]
Too bad : my strategy is to have minimum disk on the PC (one SSD + on 1TB Hard drive) and large volume hard drive on the NAS.
If  I run StorjShare on the NAS, what is the recommanded configuration (RAM sizing).

**Comment by littleskunk** [comment]
https://community.storj.io/ is a better place for these questions.
