### ISSUE TITLE
Vue is running in development mode

### ISSUE THREAD

**Issue by velagand** [Storj/storjshare-gui#679]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.4.0
- **Operating System:** Windows 10 Pro Insider Preview

### Expected Behavior

```
Vue should be running in production mode
```

### Actual Behavior
```
In developer console:
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
```

### Steps to Reproduce

1. View -> Developer Tools
2. Errors

**Comment by RGBKey** [comment]
I believe this requires us to set the env. variable `NODE_ENV` to `production`. [Source](https://vuejs.org/v2/guide/installation.html#Development-vs-Production-Mode)

**Comment by littleskunk** [comment]
`setx NODE_ENV production` and restart the GUI will solve it.
