### ISSUE TITLE
Change text in GUI step 1 (payout address) to avoid confusion (users using a regular ETH exchange address)

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#680]
### Versions

Replace the values below with your own:

- **GUI Version:** latest
- **Operating System:** all

### Expected Behavior

Please describe the program's expected behavior.

```
Farmers are supposed to add a STORJ ERC20 address
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Farmers read only the ETH part in the text on window 1 and add a exchange address:

Storj uses an ERC20 token. Please provide your STORJ token address from a supported wallet to receive payments.

**It should state**

Step 1 - Payout Address
Storj uses an Ethereum ERC20 token. Please provide your Ethereum address from a supported wallet to receive payments.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
Working on it.

**Comment by littleskunk** [comment]
@MeijeSibbel how is this?

![image](https://user-images.githubusercontent.com/6333390/29683017-4e2410ee-890d-11e7-938a-5b94926155a1.png)

**Comment by heunland** [comment]
maybe in the greyed out text we should put "0xSTORJ_ERC20_wallet_address" instead. Also add to the text on top "Do NOT use an exchange deposit address, use an ERC20 wallet address of which you hold the private key yourself."

**Comment by littleskunk** [comment]
@heunland check this
![grafik](https://user-images.githubusercontent.com/6333390/29749806-ca73288c-8b34-11e7-94a4-9a63f6afdbf7.png)
