### ISSUE TITLE
100% disk usage but no traffic 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#682]
### Versions

Replace the values below with your own:

- **GUI Version:** latest
- **Operating System:** all
### Expected Behavior

Please describe the program's expected behavior.

```
Disk usage does not go to 100% when idle traffic?
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

https://www.reddit.com/r/storj/comments/6vymjv/periodic_episodes_of_very_high_disk_usage_without/

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
That is the shard reaper. Will be solved with https://github.com/Storj/storjshare-daemon/issues/115
