### ISSUE TITLE
OSX version support 

### ISSUE THREAD

**Issue by BLTrout** [Storj/storjshare-gui#684]
### Versionhttps://github.com/Storj/storjshare-gui/releases/download/v6.4.0/storjshare-gui.osx64.dmg
Replace the values below with your own:

- GUI Version: per download
- Operating System: OSX 10.8.5

### Expected Behavior

that it would work

is the above version compatible with the version of osx shown?
seems not to be - error message is:

Storj Share cannot be opened because of a problem.
Check with the developer to make sure Storj Share works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.
Click Report to see more detailed information and send a report to Apple.

any advice appreciated
```
here's some feedback - it took more than 24hrs to download the dmg file - must have been a server issue
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
OSX 10.8 is not supported: https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md#macos

You can install and run storjshare-daemon.
