### ISSUE TITLE
Storj suddenly stop 

### ISSUE THREAD

**Issue by Coolestcool** [Storj/storjshare-gui#685]
### Versions

- **GUI Version:** v 6.4.0
- **Operating System:** Windows 10

### Expected Behavior

Keep running or restart by itself

### Actual Behavior

It is not auto restarting, i need start it manually, if i dont do that it keep has stoped and it appears a restart when is not

### Steps to Reproduce

Just get it a day or two maximized

**Comment by littleskunk** [comment]
Works as expected. Storjshare-daemon will restart a farmer only 30 times as you can see here: https://github.com/Storj/storjshare-daemon/blob/863f33ef39591f1e1af1cb818186d3251b1a349a/lib/api.js#L412

Better take a look into your logfile and fix the reason for the restart.
