### ISSUE TITLE
Shared storage percentage goes over 100%

### ISSUE THREAD

**Issue by wilkenas** [Storj/storjshare-gui#701]
### Versions 

- **GUI Version:** v7.0.2
- **Operating System:** Windows 10

### Expected Behavior

Should stop accepting data after `storageAllocation `value is reached.

### Actual Behavior

Percentage value of shared storage keeps getting higher even after reaching 100%

### Steps to Reproduce

This behaviour occurred

 after updating GUI to 7.0.1

### Screenshots (Optional)

![screenshot 2017-09-25 13 29 48](https://user-images.githubusercontent.com/23121705/30804322-b068b754-a1f5-11e7-9b2a-7e1a4bf4a481.png)

**Comment by littleskunk** [comment]
Duplicate: #672 and fixed in GUI 7.0.2
