### ISSUE TITLE
Storj Farmer Contracts

### ISSUE THREAD

**Issue by jragan18** [Storj/storjshare-gui#705]
### Versions

Replace the values below with your own:

- **GUI Version:** vLATEST
- **Operating System:** Windows 10 Pro

### Expected Behavior

Please describe the program's expected behavior.

```
For those of us who are not very tech savvy and we are interested in calculating how many GBh we have accumulated, the script that was made by Jens Heimbürge: "Storj_farmer_contracts", should be integrated as a feature with a selection menu to input date fields and start the calculation. 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Storj Share GUI does not have a feature to show how much we are making/not making during the month.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...Open Storj Share GUI
2. ...Look for the feature
3. ...Notice it is not there.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/bridge/issues/432
