### ISSUE TITLE
Problem with share space (more than defined)

### ISSUE THREAD

**Issue by yepla** [Storj/storjshare-gui#708]
![storjshare](https://user-images.githubusercontent.com/13408573/31059689-ca763dcc-a706-11e7-9e51-e273ff2e4f92.png)
- **GUI Version:** v7.1.0
- **Operating System:** Debian testing

I have set a storage of 300Gb in the gui i can see Shared: 311Gb (104%) !

Does it mean it use more than 300Gb ? Bug ?

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/675
