### ISSUE TITLE
ERROR 0x0000000000000.. The memory could not be writen

### ISSUE THREAD

**Issue by Kar0le** [Storj/storjshare-gui#710]
GUI 7.1.0
Daemon 5.1.0
Core 8.1.0
Protocol 1.2.0

W10x64 
4nodes/4threads/8gbram
on a side ccminex64 ~2 gigs ram used

another rig 
2nodes/2threads/8 gigs ram, eth miner on a side ~2.5 gigs used

every 6-8 hours node crash with with error message
![capture](https://user-images.githubusercontent.com/32479750/31116878-58aa0dba-a830-11e7-88a0-2af1a97eba55.PNG)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/114
