### ISSUE TITLE
Storj Share is sharing more space than what was configured.

### ISSUE THREAD

**Issue by 4x4Rocket** [Storj/storjshare-gui#711]
### Versions

- **GUI Version:** v7.1.0
- **Operating System:** Windows 10 64-bit

### Expected Behavior

Set maximum data allocation limit so no more than what is specified is used.

### Actual Behavior

I have 200 GB shared.  Storj Share is showing "203.65GB (102%)".  This is over what I have specified as the maximum share size.

### Steps to Reproduce

Created a share. Limit was reached and maintained for a few weeks.  It has now gone over without any changes.  Updated to most recent version, no change.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/675
