### ISSUE TITLE
StorjShare GUI Memory HOG

### ISSUE THREAD

**Issue by NSAll** [Storj/storjshare-gui#712]
### Versions
Replace the values below with your own:

- **GUI Version:** v7.1.0
- **Operating System:** Windows 10 x64 - 8GB Memory
3 Nodes running on 1 Storj Share
GUI 7.1.0
Daemon 5.1.0
Core 8.1.0
Protocol 1.2.0
### Expected Behavior
Memory usage used to stay around 2-3 gb, but is using a lot more since update to 7.1.0
```

### Actual Behavior
I am noticing Storj Share gui hogs between 3 and 6gb of memory on average forcing my pc to throw an error and shut my nodes down along with other programs. This didn't happen in the previous version. Screenshot attached. The worst I've seen is 1,122,000 commit in task manager when looking at the memory usage for Storj Share's gui. this was at 6gb of memory usage. The screenshot is after I opened the program and let it run for 1 hour only. 
```

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... Using windows 10, with all updates, and only 8gb memory, run 3 nodes for 24 hours
2. ...wait for error out
3. ...
![56minutesstorj-100317](https://user-images.githubusercontent.com/30507319/31183784-35e11a7c-a8ed-11e7-9589-2260f48387c9.png)

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by NSAll** [comment]
This is 4 hours in, consuming almost all memory now. 
![4hours](https://user-images.githubusercontent.com/30507319/31188731-7de35e62-a8fb-11e7-9260-a624529e3471.png)
![mrmor](https://user-images.githubusercontent.com/30507319/31188730-7dc2465a-a8fb-11e7-9a14-286156a93733.png)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-daemon/issues/114

**Comment by NSAll** [comment]
This isn't solved. Not sure why it was marked as closed. 
Yes, it's a duplicate, but the problem isn't solved. The post were of no help here: 
https://github.com/Storj/storjshare-daemon/issues/114

The memory issue is a big deal and we should be able to edit a config file somewhere limiting the amount of memory usage based on the systems memory at the time. That should be automatically done, but it seems to be not as it's using 97% of memory at most times and crashes daily. 

I've tried editing the api.js file, along with the farmer.js files to limit memory, connections, and then set them back to default as the post in the linked post suggested, but that solved nothing. 

Any actual solution or workaround to this yet by chance?
