### ISSUE TITLE
StorjShare Memory Killer - Never Solved Problem

### ISSUE THREAD

**Issue by NSAll** [Storj/storjshare-gui#713]
NOT A DUPLICATE POST, DO NOT CLOSE W/O SOLUTION PLEASE. 

We all need a solution to this problem. 

![mrmor](https://user-images.githubusercontent.com/30507319/31238947-20b6f994-a9c1-11e7-97e6-566088e1a005.png)

![56minutesstorj-100317](https://user-images.githubusercontent.com/30507319/31238941-1b960bd0-a9c1-11e7-9b89-321ab036f322.png)
Versions

Replace the values below with your own:

GUI Version: v7.1.0
Operating System: Windows 10 x64 - 8GB Memory
3 Nodes running on 1 Storj Share
GUI 7.1.0
Daemon 5.1.0
Core 8.1.0
Protocol 1.2.0
Expected Behavior

Memory usage used to stay around 2-3 gb, but is using a lot more since update to 7.1.0

### Actual Behavior
I am noticing Storj Share gui hogs between 3 and 6gb of memory on average forcing my pc to throw an error and shut my nodes down along with other programs. This didn't happen in the previous version. Screenshot attached. The worst I've seen is 1,122,000 commit in task manager when looking at the memory usage for Storj Share's gui. this was at 6gb of memory usage. The screenshot is after I opened the program and let it run for 1 hour only. 

Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

... Using windows 10, with all updates, and only 8gb memory, run 3 nodes for 24 hours
...wait for error out
...
56minutesstorj-100317
Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.
![4hours](https://user-images.githubusercontent.com/30507319/31238937-189171ea-a9c1-11e7-8d23-50d6ce779c8a.png)

Furthermore, This was marked as 'Duplicate' but it is NOT A DUPLICATE POST.

This isn't solved. Not sure why it was marked as closed.
Yes, it's a duplicate, but the problem isn't solved. The post were of no help here:
Storj/storjshare-daemon#114

The memory issue is a big deal and we should be able to edit a config file somewhere limiting the amount of memory usage based on the systems memory at the time. That should be automatically done, but it seems to be not as it's using 97% of memory at most times and crashes daily.

I've tried editing the api.js file, along with the farmer.js files to limit memory, connections, and then set them back to default as the post in the linked post suggested, but that solved nothing.

Any actual solution or workaround to this yet by chance?

**Comment by littleskunk** [comment]
Still duplicate: https://github.com/Storj/storjshare-daemon/issues/114

**Comment by NSAll** [comment]
Really? Why did you close this again? THIS IS NOT A DUPLICATE. What are the next steps in support?

**Comment by littleskunk** [comment]
Let me answer you question. No it is not solved. No there is no workaround. No we will not keep 10 issue open all with the same problem. We will close 9 and use only 1 to track it.

**Comment by NSAll** [comment]
Thats fine, I understand keeping it all in once place, that's great for productivity, but the fact that it was closed, then nothing said about why and the other ticket isn't solved, is quite frustrating. Just trying to get an answer from someone on this.
