### ISSUE TITLE
Storj Share GUI not launching in Ubuntu

### ISSUE THREAD

**Issue by manojbalaji1** [Storj/storjshare-gui#717]
### Versions

- **GUI Version:** v7.1.0
- **Operating System:** Ubuntu 17.04

### Expected Behavior

The Storj Share GUI is expected to launch on clicking the icon in launch bar in Ubuntu 17.04 

### Actual Behavior

Storj Share GUI not launching on clicking the icon in Ubuntu 17.04

**Comment by TheRoliYogi** [comment]
Hi manojbalaji1!

I had the same issue on Ubuntu Server 16.04.2 LTS
There are some missing libraries Storj needs.

Here is the solution, hope it works for you too:

**sudo apt-get install libgtkextra-dev libgconf2-dev libnss3 libasound2 libxtst-dev**

If you have any other question, let me know it :)

Donations via BTC:
1DFmx6nTLoFMBagbnym3MmtNxuPiYHZNK3
