### ISSUE TITLE
Storj Share should check if firewall rule(s) was already added before deciding to add new rule

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#718]
### Versions

Replace the values below with your own:

- **GUI Version:** latest
- **Operating System:** Windows 

### Expected Behavior

Please describe the program's expected behavior.

```
Storj Share should check if it already added a firewall rule in the past, if so, don't add a new rule.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Storj Share adds a new rule even if the rule already exists. Thus users will get multiple firewall entries for Storj Share every time they install a update.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
I am not able to reproduce it. The installer is working as expected. Even if you run the installer multiple times it will overwrite the old firewall rule.

I would expect up to 2 firewall rules for the 32bit binary and 64bit binary. They need different firewall rules.

If you have more than 2 they are most likely old firewall rules created by windows and not by the installer.
