### ISSUE TITLE
Storj Won't Install on 10.7.5 but works on 10.8? Mac OS X...

### ISSUE THREAD

**Issue by darkskilled** [Storj/storjshare-gui#735]
So, when trying to drag the application aka the dmg it won't work as it says you need 10.8. I know you guys can make it work. There are many hacks that people do to install the latestest mac os x or versions that can't be installed. I don't have time to research that, it is fun and all but I will like to just share my drive space.... ### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md#macos
