### ISSUE TITLE
Error: Cannot find module 'electron'

### ISSUE THREAD

**Issue by syntropysoftware** [Storj/storjshare-gui#740]
################ Versions ################

- **GUI Version:** v1.0.3
- **Operating System:** Linux manjaro 4.9.61-3
- **npm version: 5.5.1
- ** Node version: v9.2.0

################ Expected Behavior ################
```
Tried to install with instructions: https://github.com/Storj/storjshare-gui
```
################ Actual Behavior ################
```
After running the npm production start command I get the following error that module 'electron' can not be found...

npm --production start

> @ start /root/storjshare-gui
> node ./tasks/start

module.js:544
    throw err;
    ^

Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/storjshare-gui/tasks/start.js:5:16)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node ./tasks/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-03T02_48_05_960Z-debug.log

```

################  Steps to Reproduce ################

1. ... tried installing the module electron: 
npm install --save electron-npm-install

2. ...
npm install electron --save-dev

and I get the following error:
npm install electron --save-dev

> electron@1.6.2 postinstall /root/storjshare-gui/node_modules/electron
> node install.js

sh: node: command not found
npm WARN storjshare-gui No repository field.
npm WARN storjshare-gui No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron@1.6.2 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron@1.6.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-03T02_53_31_569Z-debug.log

############
Thanks very much for your help!

**Comment by littleskunk** [comment]
Are you sure you run the install command correct?

```
git clone https://github.com/Storj/storjshare-gui.git && cd storjshare-gui
npm install
```

**Comment by syntropysoftware** [comment]
Hey, thanks a lot for your help!

1. The clone works good:

git clone https://github.com/Storj/storjshare-gui.git && cd storjshare-gui

2. It brings me into: /root/storjshare-gui

3. Then when I do "npm install": 

It gives me the following error:

######################
[root@manjaro storjshare-gui]# npm install

> electron@1.6.2 postinstall /root/storjshare-gui/node_modules/electron
> node install.js

module.js:544
    throw err;
    ^

Error: Cannot find module '/root/storjshare-gui/node_modules/electron/install.js'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
npm WARN storjshare-gui No repository field.
npm WARN storjshare-gui No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.3.10 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.3.10: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.6.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-03T18_50_13_362Z-debug.log
########################################

4. When I go into here:
[root@manjaro node_modules]# pwd
/root/storjshare-gui/node_modules

and do a "ls -l" it gives me the following list of files:

drwxr-xr-x 6 root root 4096 Dec  3 13:50 asar
drwxr-xr-x 4 root root 4096 Dec  3 13:50 chai
drwxr-xr-x 7 root root 4096 Dec  3 13:50 coveralls
drwxr-xr-x 3 root root 4096 Dec  3 13:50 devuan
drwxr-xr-x 5 root root 4096 Dec  3 13:50 electron-mocha
drwxr-xr-x 4 root root 4096 Dec  3 13:50 esprima-fb
drwxr-xr-x 6 root root 4096 Dec  3 13:50 fs-jetpack
drwxr-xr-x 6 root root 4096 Dec  3 13:50 gulp
drwxr-xr-x 3 root root 4096 Dec  3 13:50 gulp-babel
drwxr-xr-x 3 root root 4096 Dec  3 13:50 gulp-less
drwxr-xr-x 4 root root 4096 Dec  3 13:50 gulp-sourcemaps
drwxr-xr-x 4 root root 4096 Dec  3 13:50 gulp-util
drwxr-xr-x 4 root root 4096 Dec  3 13:50 istanbul
drwxr-xr-x 7 root root 4096 Dec  3 13:50 jshint
drwxr-xr-x 6 root root 4096 Dec  3 13:50 mocha
drwxr-xr-x 6 root root 4096 Dec  3 13:50 proxyquire
drwxr-xr-x 2 root root 4096 Dec  3 13:50 q
drwxr-xr-x 4 root root 4096 Dec  3 13:50 rcedit
drwxr-xr-x 5 root root 4096 Dec  3 13:50 sinon
drwxr-xr-x 3 root root 4096 Dec  3 13:50 tree-kill
drwxr-xr-x 4 root root 4096 Dec  3 13:50 uuid
drwxr-xr-x 5 root root 4096 Dec  3 13:50 yargs

------
5. Please note that the file: /root/storjshare-gui/node_modules/electron/install.js

simply does not exist. The only electron module in there is "electron-mocha".

6. I tried installing Electron using: 

npm install --save-dev electron

7. I even tried removing the node_modules and reinstalling electron:

rm -rf node_modules
npm install electron

But I get the same error: 
Error: Cannot find module '/root/storjshare-gui/node_modules/electron/install.js'

#########
Thanks again for your help!

**Comment by syntropysoftware** [comment]
I also tried a suggestion I found online:

[root@manjaro storjshare-gui]# npm install --unsafe-perm

and I get the following error: 
--------------------------------------------------
> electron@1.6.2 postinstall /root/storjshare-gui/node_modules/electron
> node install.js


> undefined postinstall /root/storjshare-gui
> node ./tasks/app_npm_install

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/littleskunk/node-ip.git
npm ERR! 
npm ERR! fatal: failed to stat '/root/storjshare-gui/app': Permission denied
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-03T19_06_42_244Z-debug.log
npm WARN storjshare-gui No repository field.
npm WARN storjshare-gui No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.3.10 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.3.10: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 243 packages in 24.362s
-------------------------------------------------------------

Could the issue be that I am running Manjaro / Arch Linux and should be running Ubuntu or Debian?

Thanks!

**Comment by tempestb** [comment]
You could run the Daemon, which is the command line version.  Then you dom't have to deal with electron.  You can do an npm install -g storjshare-daemon

**Comment by syntropysoftware** [comment]
That is a good idea. I tried that however and got the following error:

-------------------
[root@manjaro ~]# npm install -g storjshare-daemon
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/zipang/daemon.node.git
npm ERR! 
npm ERR! fatal: Cannot come back to cwd: Permission denied
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-03T21_56_09_566Z-debug.log

-------------------------------
I am running as "root", I even tried to create a new folder: /root/storjshare-daemon  and then make it wide open:

chown -R ug+w storjshare-daemon/
chmod 777 -R storjshare-daemon

but have the same error: 

-------------------
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/zipang/daemon.node.git
npm ERR! 
npm ERR! fatal: failed to stat '/root/storjshare-daemon': Permission denied
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-03T21_55_08_137Z-debug.log
--------------

Thanks again.

**Comment by tempestb** [comment]
You can't install it as root.  Create a user and install it under the user.  You may need to reinstall npm under the new user.

**Comment by syntropysoftware** [comment]
Ahhh, it is always the easy fix! Sorry for the dumb question, I usually do everything as root so I took it for granted that it could have just been user / non-root only. 

Thanks for your help! Closing ticket.
