### ISSUE TITLE
Closing Storjshare window with the X icon breaks it

### ISSUE THREAD

**Issue by jytou** [Storj/storjshare-gui#746]
### Versions

- **GUI Version:** v7.3.1
- **Operating System:** Ubuntu 16.04.3 LTS
- **Daemon 5.3.0**
- **Core 8.5.0**
- **Protocol 1.2.0**
Installed from provided .deb package.

### Expected Behavior

Run storjshare UI. Close the window using the system's icon (NOT the File/Quit) menu. It should end and return to the prompt when the window is closed. Added drives should come up again on subsequent launches of storjshare.

### Actual Behavior

When closing the window without going through the menu, storjshare never stops, and then the whole configuration is broken (on next restart, storj prompts for a new config as if it was never configured before). Even reading existing config files fail.

### Steps to Reproduce

It seems I can reproduce this systematically on my system. Just close the window with the X icon rather than with File/Quit.

**Comment by littleskunk** [comment]
> It should end and return to the prompt when the window is closed.

That is not correct. The GUI should keep running in system tray. Only Quit will close it.
