### ISSUE TITLE
No Allocs Received

### ISSUE THREAD

**Issue by 88plug** [Storj/storjshare-gui#748]
I have been connected for 2 days now with all green status and can see 232 peers but I have not received any files.  How long does it usually take to see some network activity if any?  Is anyone using the network for storage now?

**Comment by littleskunk** [comment]
First let me answer your questions. You should receive alloc within hours. I can cofirm they are renter uploading shards right now.

Ok now the bad new. Github is not the place for these questions. Next time please use http://community.storj.io/
