### ISSUE TITLE
changing recieving wallet to jaxx edit button and get 

### ISSUE THREAD

**Issue by bitminer2017** [Storj/storjshare-gui#749]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

SyntaxError: JSON.parse: expected property name or '}' at line 2 column 3 of the JSON data.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
config file invalide.
