### ISSUE TITLE
Unable to install Storj on Ubuntu

### ISSUE THREAD

**Issue by lmannyr** [Storj/storjshare-gui#753]
### Versions 7.3.1

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** Ubuntu 17.10 with latest upgrades.

### Expected Behavior:

Should insatll and run.

Please describe the program's expected behavior.

```

```

### Actual Behavior

Install is very quick as if nothing actually installed.   Clicking on the app icon after install, the app apears to try to start, but the app icon disapears after about 10 seconds with no further screens popping up.
```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... easily reproducable.  Just click the Storj app icon after install and watch it not do anything.

**Comment by littleskunk** [comment]
Ubuntu 17.10 is not supported by electron. https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md#linux

Better use storjshare-daemon or try to find out which libraries you need to install to get the GUI running.

**Comment by lmannyr** [comment]
I tried again using Ubuntu 12.04 per the above link and get the same response.  Installation is done on a VM with using 2 cores and 4gb ram with 10 TB HD space.
