### ISSUE TITLE
AssertionError: Invalid storage size

### ISSUE THREAD

**Issue by jaylagorio** [Storj/storjshare-gui#755]
### Versions

Replace the values below with your own:

- **GUI Version:** v7.3.1 and v7.3.2
- **Operating System:** Windows Server 2016 (x64)

### Expected Behavior

When setting up a new drive on an empty disk, which has 10.09 TB of space, the operation is expected to succeed as it has in previous versions.

### Actual Behavior

A red bar appears at the top of the window that says "AssertionError: Invalid storage size" and the Storj logo continues to spin until I exit the program.

### Steps to Reproduce

1. Open Storj Share GUI
2. Click Start Setup
3. Enter Etherium address, click Next
4. Click Choose Files (in this case S:\, an empty drive with 10.09 TB of storage on it), click Select Location
5. Choose TB from the drop down menu, see that the label on the right changes to "10.00968 TB Available", enter "10" in the text box and click Next
6. Don't change connection settings, click Next
7. Observe red error bar and spinning logo

### Logs
Not sure which logs to attach, let me know and I'm happy to attach them.

**Comment by braydonf** [comment]
8TiB is the max size currently.
