### ISSUE TITLE
ERROR {"error":"Invalid farmer data (spaceUsedBytes)"}

### ISSUE THREAD

**Issue by skimanner** [Storj/storjshare-gui#758]
![2018-03-12 6](https://user-images.githubusercontent.com/6972551/37266773-ef1d9840-2592-11e8-9e1a-8a8bacf93eee.png)
### Versions

- **GUI Version:** v7.3.2
- **Operating System:** Windows 10 Pro

### Expected Behavior

Please describe the program's expected behavior.

To continue receiving allocs and shards and reputation on original node

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

After shutting computer down for a few hours to install new hardware including a new hard drive I started it back up, added the new hard drive as a node which is working fine but the old node does not get any alloc, shards and reputation just kept going down until 0.  the storjstat monitor keeps giving me 
ERROR {"error":"Invalid farmer data (spaceUsedBytes)"} The storj GUI still says I have 2.01MB worth of shards but apparently storj don't think I should have those shards. its still being seen although storjstat shows my original node as 127.0.0.1:4000 now but when I click on node it shows my IP and port correctly {"spaceAvailable":true,"lastSeen":"2018-03-12T05:03:56.201Z","port":4000,"address":"98.4.111.157","protocol":"1.2.0","responseTime":10108.54176826571,"reputation":0,"userAgent":"8.6.0","nodeID":"86bca327d89721e31abd25fd57e718f4a6554025"}

When I first tried restarting old node I get a message that said insufficient resources.  I closed that and clicked start on node and it started back up.

Logs are filled with same error a lot 
{"level":"warn","message":"error returned from remote host: request timeout after 30000ms","timestamp":"2018-03-12T04:00:00.150Z"}
{"level":"warn","message":"error returned from remote host: request timeout after 30000ms","timestamp":"2018-03-12T04:00:00.165Z"}
{"level":"warn","message":"missing or empty reply from contact"

but also plenty of receive valid message from and publish

I just started using this yesterday so I can't think of what else you might want.

### Steps to Reproduce

1. ...  Not so sure this is applicable 
2. ...
3. ...

### Screenshots (Optional)

![2018-03-12](https://user-images.githubusercontent.com/6972551/37266711-801f4dc6-2592-11e8-8d16-3a0db2988bba.png)
![2018-03-12 5](https://user-images.githubusercontent.com/6972551/37266715-8491dbb2-2592-11e8-8bb1-7808d1fdd706.png)
![2018-03-12 4](https://user-images.githubusercontent.com/6972551/37266719-87d51b86-2592-11e8-9990-d73bb8a313d3.png)
![2018-03-12 3](https://user-images.githubusercontent.com/6972551/37266721-8af5f574-2592-11e8-9907-48e2f2bb5fa5.png)
![2018-03-12 2](https://user-images.githubusercontent.com/6972551/37266723-8db79330-2592-11e8-9d71-cdefe4fba374.png)
![2018-03-12 1](https://user-images.githubusercontent.com/6972551/37266724-9167cebe-2592-11e8-9178-da9837a0131d.png)

**Comment by skimanner** [comment]
Everything seems more normal now.  Getting allocs/rep and its showing a real IP in storjstat but the error is still showing in the monitor but I dont see it at the bottom of the logs at all anymore.  So logs seem good now.

**Comment by stefanbenten** [comment]
@skimanner This issue is because your seconds node hasnt any shared bytes yet.
Also thats an issue of the StorjMonitor and not of StorjShare.
You can see the issues here: https://github.com/calxibe/StorjMonitor/issues/7
