### ISSUE TITLE
Ubuntu 17.10 unable to start : diskusage.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 54

### ISSUE THREAD

**Issue by schwab** [Storj/storjshare-gui#759]
### Versions
Distributor ID:	Ubuntu
Description:	Pop!_OS 17.10 (Artful Aardvark)
Release:	17.10
Codename:	artful

### Expected Behavior

Following the instructions in the readme should allow the code to start and run, however, on 17.10 this does not work as expected.  These steps were performed in the cloned git directory...

```
git clone https://github.com/Storj/storjshare-gui.git && cd storjshare-gui
npm install
npm --production start
```
### Actual Behavior
Application crashes on startup...: 
```
> @ start /mnt/extradrive1/projects/storjshare-gui
> node ./tasks/start

[10:04:09] Using gulpfile /mnt/extradrive1/projects/storjshare-gui/gulpfile.js
[10:04:09] Starting 'clean'...
[10:04:10] Finished 'clean' after 325 ms
[10:04:10] Starting 'copy'...
[10:04:12] Finished 'copy' after 2.39 s
[10:04:12] Starting 'build'...
[10:04:12] Finished 'build' after 20 μs
ELECTRON_ASAR.js:172
        return old.apply(this, arguments)
                   ^

Error: The module '/mnt/extradrive1/projects/storjshare-gui/build/node_modules/diskusage/build/Release/diskusage.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
```

### Steps to Reproduce

1. Clean install on ubuntu 17.10
2. Attempted fixes: 
```
sudo apt upgrade npm
rm -rf build/node_modules/diskusage
npm rebuild diskusage --update-binary
npm  uninstall diskusage
npm install diskusage
```
All the above have the same effect.

### Screenshots (Optional)
UI window opens, but is completely blank.

**Comment by schwab** [comment]
After some digging around, looks like ubuntu's default install of nodejs is from version 6.x but storjshare requires nodejs 8.  I used the fThe following steps remove
```
# from http://nodesource.com/blog/installing-node-js-8-tutorial-linux-via-package-manager/
sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
npm uninstall
npm install 
npm --production start
```
which got rid of the error : diskusage.node was compiled against a different Node.js version
``` npm --production start

> @ start /mnt/extradrive1/projects/storjshare-gui
> node ./tasks/start

[10:33:53] Using gulpfile /mnt/extradrive1/projects/storjshare-gui/gulpfile.js
[10:33:53] Starting 'clean'...
[10:33:53] Finished 'clean' after 190 ms
[10:33:53] Starting 'copy'...
[10:33:55] Finished 'copy' after 1.52 s
[10:33:55] Starting 'build'...
[10:33:55] Finished 'build' after 18 μs
mcstar@oryx-pro:~/projects/storjshare-gui$ 
```

But the ui still opens and is completely blank.  No further error messages appear in the terminal, so I'm pretty stuck again.  Also tried the compiled .deb file which give also an empty window.

**Comment by tempestb** [comment]
Just as an FYI, most Linux users run the Command Line Daemon version.   Which works fine and is easy to install if you want to go that route.  

The GUI does work on Ubuntu, as some have gotten it to work, but I am not sure what is wrong with your current implementation.  We do have a community chat at https://community.storj.io and a channel titled #storjshare where we can assist with these setup issues if needed.
