### ISSUE TITLE
GUI is gone after upgrade. Storj Share.exe is running.

### ISSUE THREAD

**Issue by whotheff** [Storj/storjshare-gui#761]
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by crunchyNYC** [comment]
Same here.
Reported by multiple users in storj community chat.

**Comment by gsmachado** [comment]
Exactly same here. :-(

**Comment by crunchyNYC** [comment]
![capture](https://user-images.githubusercontent.com/11727035/37316314-aa953a3c-2634-11e8-9829-9713505d40e2.PNG)

**Comment by whotheff** [comment]
Atleast you have a blank screen :D 

Steps to reproduce:
1. Stop share
2. Quit application
3. Install new version
4. Nothing
5. Nothing
6. Kill Storj Share.exe
7. Start it manually
8. Nothing
9. Reboot PC
10. Nothing
11. Write here
12. Nothing but confirmation it is a bug.
13. Learn the lesson again: Next time wait atleast a week and then update.

**Comment by Darkangeel-hd** [comment]
this is what it returns in a debian 9 amd64
Its about nodejs versions in the package

```
ELECTRON_ASAR.js:172
        return old.apply(this, arguments)
                   ^

Error: The module '/tmp/.org.chromium.Chromium.gV9n9j'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/storjshare/resources/app.asar/node_modules/diskusage/index.js:1:169)
    at Object.<anonymous> (/opt/storjshare/resources/app.asar/node_modules/diskusage/index.js:17:3)

```

**Comment by crunchyNYC** [comment]
Works. Thanks!!!

**Comment by whotheff** [comment]
Ugh... any.. guide how to fix it? It is offline since the update.
