### ISSUE TITLE
Allocs :0 received  Shared:324B for many days

### ISSUE THREAD

**Issue by hantong006** [Storj/storjshare-gui#766]
### Versions

Replace the values below with your own:

- **GUI Version:** v17.3.2
- **Operating System:** Win7

### Expected Behavior

Please describe the program's expected behavior.
The reputation is creasing, but my allocs still 0 received, and the shared is still 324B have no increase for many days.
```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical i
![image](https://user-images.githubusercontent.com/37741471/38219870-55eaa5bc-370a-11e8-97ef-fafedaec9a52.png)
n nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
I don't see a GUI issue here. Reputation is far away from 5000 -> I would not expect any mirror shards.

At the same time you are running an outdated GUI version without the latest performance improvements.
