### ISSUE TITLE
Why is the latest storjshare-gui.win64.exe flagging WisdomEyes Trojan? False Positive!?

### ISSUE THREAD

**Issue by LooseConcentrate** [storj/storjshare-gui#769]
I haven't installed it yet. I am pretty sure this is a false positive but am wondering why.

### Expected Behavior

Not to be flagged by VirusTotal for WisdomEyes Trojan.

### Actual Behavior

The latest storjshare-gui.win64.exe is flagging WisdomEyes Trojan on VirusTotal.
https://www.virustotal.com/#/file/5037151ce1358fad0cca83cedc44ac69da5668239456c149721152687c6c1f2d/detection

### Steps to Reproduce

Drap and drop storjshare-gui.win64.exe in VirusTotal.

**Comment by littleskunk** [comment]
You are reading the VirusTotal Report wrong. If only one scanner detects something it is most likely a false positives. https://www.howtogeek.com/180162/how-to-tell-if-a-virus-is-actually-a-false-positive/
